### ISSUE TITLE
This content failed to load.

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#1000]
This content failed to load.
pop up box

when trying to edit multiple nzbs via checkboxes on all browse pages.

**Comment by DariusIII** [comment]
For now this does not work. Tried to fix it couple of times but failed.

**Comment by gardner** [comment]
Can you point a dev in the right direction? Thanks

**Comment by DariusIII** [comment]
Since i am planning to change the frontend i will close this issue.
