### ISSUE TITLE
Can't complete installation, fails at adding admin user

### ISSUE THREAD

**Issue by cspencer49519** [NNTmux/newznab-tmux#1015]
When attempting installation, when I reach the portion of the install that attempts to create the admin user, I get his error:

Seeded:  ContentTableSeeder (0 seconds)
Seeding: GenresTableSeeder
Seeded:  GenresTableSeeder (0.02 seconds)
Seeding: GroupsTableSeeder
Seeded:  GroupsTableSeeder (0.11 seconds)
Seeding: ReleaseNamingRegexesTableSeeder
Seeded:  ReleaseNamingRegexesTableSeeder (3.2 seconds)
Seeding: SettingsTableSeeder
Seeded:  SettingsTableSeeder (0.19 seconds)
Seeding: RolesAndPermissionsSeeder
Seeded:  RolesAndPermissionsSeeder (0.16 seconds)
Database seeding completed successfully.
Settings table updated successfully
Adding admin user to database
password_hash(): A thread value other than 1 is not supported by this implementationUnable to add admin user!
NNTmux installation failed. Fix reported problems and try again

 - OS: CentOS 7
 - PHP version 7.4
 - NNTmux version latest

**Comment by DariusIII** [comment]
I am not sure what kind of php 7.4 (which is still not GA) is in CentOS. Does it have argon/argon2id compiled into php?

**Comment by cspencer49519** [comment]
It's from the remi repository: https://rpms.remirepo.net/

I was not aware that PHP 7.4 is not GA yet, I'm guessing a downgrade to 7.3 will solve my issue?

**Comment by Fossil01** [comment]
Try it and report back here.

**Comment by cspencer49519** [comment]
OK, will do, could it be related to this:

https://wiki.php.net/rfc/sodium.argon.hash

**Comment by DariusIII** [comment]
This is 99% the cause of your problem.

**Comment by cspencer49519** [comment]
PHP 7.3 indeed fixed the issue, thanks.
