### ISSUE TITLE
Postprocessing failure

### ISSUE THREAD

**Issue by cspencer49519** [NNTmux/newznab-tmux#1019]
Running /misc/update/postprocess.php all true results in a failure. Here is the exact error:

Skipping processing of rar [155/155] - "5324SXEbf0mA04D2tN63.vol448+003.par2" yEnc(1/3) it has a password.
[76405][661MB](cB)DEBUG: ArchiveInfo: Compressed file has a password.
Skipping processing of rar (20/20) "shlmxTfgTzyN0VAbeGbtM.vol63+16.par2" - 637,93 MB - yEnc(1/11) it has a password.
[76388][2.2GB](cB)DEBUG: ArchiveInfo: Compressed file has a password.
Skipping processing of rar 39b87b605ce04db3a5bf1d805f7cad84 [50/50] "39b87b605ce04db3a5bf1d805f7cad84.vol255+012.par2" yEnc(1/13) it has a password.
[76394][2.2GB]
[75834][55.6MB](cB)r(cB)r(cB)r(cB)rDEBUG: ERROR: Could not open temp dir: Array to string conversion

   ErrorException  : Invalid argument supplied for foreach()

  at /var/www/cos7-mediaserver.local/NNTmux/Blacklight/processing/post/ProcessAdditional.php:1253
    1249| 
    1250|             // Get all the compressed files in the temp folder.
    1251|             $files = $this->_getTempDirectoryContents('/.*\.([rz]\d{2,}|rar|zipx?|0{0,2}1)($|[^a-z0-9])/i');
    1252| 
  > 1253|             foreach ($files as $file) {
    1254| 
    1255|                 // Check if the file exists.
    1256|                 if (File::isFile($file[0])) {
    1257|                     $rarData = @File::get($file[0]);

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Invalid argument supplied for foreach()", "/var/www/cos7-mediaserver.local/NNTmux/Blacklight/processing/post/ProcessAdditional.php", [])
      /var/www/cos7-mediaserver.local/NNTmux/Blacklight/processing/post/ProcessAdditional.php:1253

  2   Blacklight\processing\post\ProcessAdditional::_processExtractedFiles()
      /var/www/cos7-mediaserver.local/NNTmux/Blacklight/processing/post/ProcessAdditional.php:734

  Please use the argument -v to see more details.

I have tried to reset the processed status of all releases, to no avail.

**Installation (please complete the following information):**
 - OS: CentOS 7
 - PHP 7.3.12
 - NNTmux latest dev

**Comment by DariusIII** [comment]
There are no files that match the regex, so foreach loop fails.
