### ISSUE TITLE
Time zone could not be found

### ISSUE THREAD

**Issue by silverfiler** [NNTmux/newznab-tmux#1025]
get this error in backfill pane

`__construct(): Failed to parse time string (backfill_target) at position 0 (b): The time zone 
could not be found in the database2019-12-06`

don't know how to solve this. 
time zone in .env is like in php.ini
TZ = "Europe/Amsterdam"

**Comment by DariusIII** [comment]
This is not an error in your. env but bug in backfill code.

**Comment by silverfiler** [comment]
ok, found this commit
[https://github.com/NNTmux/newznab-tmux/commit/86504ba2764c967feaf050f2404e8caf8fd2fb7b](url)

but, now i get 
`undefined offset error02019-12-06 ...`

**Comment by silverfiler** [comment]
ok, going back to nZEDb ... don't want to waste my time even more for this collection of bugs.

**Comment by Fossil01** [comment]
Ok bye.
