### ISSUE TITLE
Private profiles

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1058]
Opening a users profile as admin doesn't work. You just get your own profile.

Looks like the only data passed to the view is `$this->userdata` and not $user from line 49. Also the check if a user page is opened by ID doesn't return a User object.

**Comment by DariusIII** [comment]
I am aware of the issue, but it's not top priority. Will be fixed anyway.

**Comment by Fossil01** [comment]
Fixed
