### ISSUE TITLE
Sphinx: Syntax error

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1059]
`SQLSTATE[42000]: Syntax error or access violation: 1064 index releases_rt: syntax error, unexpected ')' near ' \/)' [SELECT * FROM releases_rt WHERE MATCH('(@searchname \\/)') ORDER BY id DESC LIMIT 0, 10000 OPTION max_matches = 10000, ranker = 'sph04', sort_method = 'pq']`

Trace:
vendor/foolz/sphinxql-query-builder/src/SphinxQL.php:274
Blacklight/SphinxSearch.php:216
Blacklight/Releases.php:571
app/Http/Controllers/Api/ApiController.php:147

**Comment by wimjan123** [comment]
Did this get fixed?

**Comment by DariusIII** [comment]
No, as this is search related and how library used handles them.
