### ISSUE TITLE
Better TV matching

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1066]
https://github.com/NNTmux/newznab-tmux/blob/dev/Blacklight/processing/tv/TV.php#L480

I think if it doesn't find a show in the DB with the year, try without? I have several shows in DB without a year in the title but the releasenames sometimes have a year.

**Comment by DariusIII** [comment]
The line you linked is just for shows that don't have an airdate, so we try to add it by checking for year in the name.

**Comment by Fossil01** [comment]
Oh. Well it happens a lot with TV shows for which the code looks up: Showname (2019) but in the videos table it's just called Showname.

Might match wrong stuff if there was a reboot of the show which doesn't have the year in the title. But I think it'll match more correctly than incorrectly?


Also as discussed on IRC:

postprocess looks for entries like: John and Doe but sometimes the videos table has it listed as John + Doe or John & Doe and the other way around. Best would be to regex the and,&,+ out of the titles and interchange them with eachother to match more.
