### ISSUE TITLE
[request] categorizing releases

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#1079]
any chance of bringing back categorizing releases page.

as would be use full as say some releases from say erotica are going to hd/movies
also releases from mp3's are going to books/games etc

it would be handy to say force a group say alt.binaries.music.80s goto mp3 or mp3 other

![req](https://user-images.githubusercontent.com/3258413/73163177-5079bd00-40e7-11ea-95cf-3cfe325549bb.png)

**Comment by DariusIII** [comment]
I need to check if i removed support completely, or just that page.
