### ISSUE TITLE
Ebook: Undefind property stdclass:: $description

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#1083]
![ebook](https://user-images.githubusercontent.com/3258413/74304187-1f8ac080-4d54-11ea-8c60-6c655f21ac50.png)

error with php 7.3 & 7.4

**Comment by DariusIII** [comment]
This is actually a bug in php-itunes-api package. I have pushed a fix and pulled the new release into NNTmux. This bug should be fixed now.

I will close this issue, but if the error persists feel free to reopen it.
