### ISSUE TITLE
Mediainfo/ffmpeg error

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#1084]
![mediainfo](https://user-images.githubusercontent.com/3258413/74306215-d473ac00-4d59-11ea-801d-9478b53baefc.png)

when using php postprocess.php additional true from update folder.

debian 
php 7.3 & 7.4

**Comment by DariusIII** [comment]
Do you have LAME installed? This error is actually not an NNTmux related error, but error in package used.

**Comment by m0rse** [comment]
using LAME 64bits version 3.99.5
