### ISSUE TITLE
install failure   inkedcurtis/omnipay-coinpayments

### ISSUE THREAD

**Issue by gjm76** [NNTmux/newznab-tmux#1086]
i ran composer install on ubuntu 16.04 following the install guide and got this error ;

nntmux:/var/www/NNTmux$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 131 installs, 0 updates, 0 removals
  - Installing inkedcurtis/omnipay-coinpayments (1.0): Downloading (failed)    Failed to download inkedcurtis/omnipay-coinpayments from dist: The "https://api.github.com/repos/InkedCurtis/omnipay-coinpayments/zipball/3eac0d9f70486d55ba1a8eba72dd1a2381d538e1" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing inkedcurtis/omnipay-coinpayments (1.0): Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+nntmux+2020-02-18+1217
to retrieve a token. It will be stored in "/home/gjm/.composer/auth.json" for future use by Composer.
Token (hidden):
Token stored successfully.
Cloning 3eac0d9f70

  [RuntimeException]
  Failed to execute git clone --no-checkout 'https://***:***@github.com/Inked
  Curtis/omnipay-coinpayments.git.git' '/var/www/NNTmux/vendor/inkedcurtis/om
  nipay-coinpayments' && cd '/var/www/NNTmux/vendor/inkedcurtis/omnipay-coinp
  ayments' && git remote add composer 'https://***:***@github.com/InkedCurtis
  /omnipay-coinpayments.git.git' && git fetch composer && git remote set-url
  origin 'https://github.com/InkedCurtis/omnipay-coinpayments.git.git' && git
   remote set-url composer 'https://github.com/InkedCurtis/omnipay-coinpaymen
  ts.git.git'

  Cloning into '/var/www/NNTmux/vendor/inkedcurtis/omnipay-coinpayments'...
  remote: Repository not found.
  fatal:***@github.com/InkedCurtis/omnipay-coinpayments.git.git/' not found

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by DariusIII** [comment]
This package has been removed in dev, as it was removed from github.

**Comment by DariusIII** [comment]
I have just tagged a new release with this issue fixed.
