### ISSUE TITLE
No nzbs 

### ISSUE THREAD

**Issue by gjm76** [NNTmux/newznab-tmux#1087]
Ive installed nntmux on a fresh 18.04 system, can login etc and i get releases indexed, but i get a error 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="300" description="NZB file not found!"/>

i followed the ubuntu guide exactly.

**Comment by gjm76** [comment]
just to add to this im using nginx and php7.3

The full error i get is This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="300" description="NZB file not found!"/>

also noticing this in tmux in post processing,

![2020-02-19](https://user-images.githubusercontent.com/61190341/74835079-8ee44f80-5314-11ea-89fd-e8435d0b0605.png)

**Comment by gjm76** [comment]
also get this when i command line nzbimport 

nntmux@Nntmux:/var/www/NNTmux/misc/testing$ php nzb-import.php /home/nntmux/nzbs true false false 1000

   Foolz\SphinxQL\Exception\DatabaseException  : SQLSTATE[42000]: Syntax error or access violation: 1064 no such local index 'releases_rt' [REPLACE INTO releases_rt (id, name, searchname, fromname, filename) VALUES (945, '[01/61] - \"9JiZPWi35o17bhFtCl31.par2\" yEnc', '', 'CPP-gebruiker@domein.nl (CPP-Gebruiker)', '\'\'')]

  at /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php:28
    24|
    25|         try {
    26|             $statement->execute();
    27|         } catch (PDOException $exception) {
  > 28|             throw new DatabaseException($exception->getMessage() . ' [' . $query . ']', $exception->getCode(), $exception);
    29|         }
    30|
    31|         return new ResultSet(new ResultSetAdapter($statement));
    32|     }

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 no such local index 'releases_rt'")
      /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php:26

  2   PDOStatement::execute()
      /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php:26

  Please use the argument -v to see more details.
nntmux@Nntmux:/var/www/NNTmux/misc/testing$

**Comment by DariusIII** [comment]
There are 2 things you missed:
1. storage/framework/cache needs to be accessible by your user (755 or even 777 if you are sure that nobody will compromise your server)
2. You need to install manticore search and run appropriate scripts to create tables.

**Comment by gjm76** [comment]
i think i found the issue, seems nginx was using the wrong user to run. These issues are fixed, theres a few new ones that have popped up, ill check closed issues before posting them up
