### ISSUE TITLE
docker compose build failure

### ISSUE THREAD

**Issue by piwi3910** [NNTmux/newznab-tmux#1091]
docker compose build fails at the following step:

Step 5/25 : ENV HASH a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1
 ---> Using cache
 ---> f02176ac8db1
Step 6/25 : RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echstaller verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&     php composer-setup.php --install-dir=/usr/local/bin --fie=composer && composer global require hirak/prestissimo
 ---> Running in 8dd1b3ca11d2
Installer corrupt
Could not open input file: composer-setup.php
ERROR: Service 'nn-tmux' failed to build: The command '/bin/sh -c cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r "if (hash_file(84', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&     php cor-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo' returned a non-zero code: 1

**Comment by DariusIII** [comment]
I am not using docker at all, so i cannot help with this one. Docker support was added by @wolfgang-s  and i hope he will see this issue.

**Comment by piwi3910** [comment]
found the bug already, and send you a pull request.
it's the hash in for composer that is wrong

**Comment by DariusIII** [comment]
Seen the PR, please send all PR's against dev branch.
