### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1096]
after installation i get logiin screen
but admin or register gives error 500

follow your install guide on ubuntu 16.04 and then you will get this error
I used apache2

**Expected behavior**
register and admin working

**Screenshots**

**Installation (please complete the following information):**
 - OS: [e.g. Ubuntu] ubuntu 16.04
 - PHP version [e.g. PHP 7.3
 - NNTmux version or commit [e.g. 1.0]

**Additional context**

**Comment by HengeDK** [comment]
I enabled debug and get this error

Illuminate\Container\Container::build
vendor/laravel/framework/src/Illuminate/Container/Container.php:805

throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);

**Comment by DariusIII** [comment]
1. Have you installed manticore search or elasticsearch?
2. For cache, please use redis, or anything that is not default file driver.

And always check permissions on folders like storage/framework, bootstrap/cache etc.

**Comment by HengeDK** [comment]
no
because the guide said to check your website ;-)
i will do

**Comment by DariusIII** [comment]
You followed this guide? https://github.com/NNTmux/newznab-tmux/wiki/Ubuntu-Install-guide

**Comment by HengeDK** [comment]
yes
right before it says "Open your web browser and point it to your site." ;-)

**Comment by DariusIII** [comment]
Yeah, need to edit that.

**Comment by HengeDK** [comment]
now I get this error

Target class [PragmaRX\Firewall\Middleware\FirewallBlacklist] does not exist

**Comment by HengeDK** [comment]
did composer require pragmarx/firewall
but now I can register but 
login redirects to login and same for register

**Comment by DariusIII** [comment]
pragmarx/firewall is a package that was removed from NNTmux, try to download latest dev and install from there.
