### ISSUE TITLE
Tmux Update Binaries

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#1099]
update binaries in tmux throws this error on nearly every cycle.
![binaries](https://user-images.githubusercontent.com/3258413/78340879-b3c41780-758e-11ea-8e0a-d4d183cf9af8.png)

*dev

**Comment by m0rse** [comment]
*raised timeout in config - error my end as usual :)

**Comment by m0rse** [comment]
nope still throwing error :(

**Comment by DariusIII** [comment]
This is actually more of an issue with your database and server setup, than issue with NNTmux.
Simply put, your database cannot cope with amount of data sent, so everything halts and timeouts eventually.

**Comment by m0rse** [comment]
yes seems it :(
have added a extended timeout on update binaries for now,. seems to have worked while i sort out setup.
thanks
