### ISSUE TITLE
apilimits response uses different datetime format

### ISSUE THREAD

**Issue by theotherp** [NNTmux/newznab-tmux#1101]
A typical `apilimits` field in the API response looks like this:

```
  <newznab:apilimits apicurrent="338" apimax="8000" grabcurrent="3" grabmax="8000" apioldesttime="Sun, 19 Apr 20 13:52:30 +0200" graboldesttime="Mon, 20 Apr 20 03:20:41 +0200"/>
```
and a typical pubdate looks like this
```
   <pubDate>Fri, 17 Apr 2020 06:53:56 +0200</pubDate>
``` 

Would be great if the tags in the `apilimits` could use the same format (i.e. 2020 instead of 20 for the year).

**Comment by DariusIII** [comment]
Weird, i don't recall changing format there. Will check and fix.

**Comment by theotherp** [comment]
I implemented a dirty quick fix where I add 2000 years to the date if it's too old :-D

**Comment by DariusIII** [comment]
You could have just prefixed the year with 20 :)

**Comment by theotherp** [comment]
I thought about it but I wanted it to be compatible with your potential fix.

**Comment by DariusIII** [comment]
It is fixed now in dev branch.

**Comment by theotherp** [comment]
Thank you!
