### ISSUE TITLE
MediaInfo Throws Error

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#1109]
Mediainfo throws error:
Debian
Latest mediainfo.

![mediainfo](https://user-images.githubusercontent.com/3258413/80720428-c7fb2600-8af4-11ea-9966-7cdfe2916d4c.png)

**Comment by DariusIII** [comment]
This is not an NNTmux issue, but Mediainfo and mhor/php-mediainfo one.
Mediainfo generated xml is bad for some reason.

**Comment by Fossil01** [comment]
It probably was just one release.

**Comment by m0rse** [comment]
nope :(
throws error on a different release each time I run php postprocess.php additional true to check.

![mediainfo](https://user-images.githubusercontent.com/3258413/80753688-95b5ec80-8b25-11ea-9e0a-4274b921bac9.png)

**Comment by DariusIII** [comment]
Its malformed Mediainfo xml. What version of mediainfo are you running?

**Comment by m0rse** [comment]
0.7.91-1

**Comment by DariusIII** [comment]
Oh, dear. You are running an old version.

https://github.com/mhor/php-mediainfo#support-old-mediainfo-version-1710

**Comment by m0rse** [comment]
Dam missed that :(
Fixed thanks
