### ISSUE TITLE
Different case usages for "apiCurrent"

### ISSUE THREAD

**Issue by theotherp** [NNTmux/newznab-tmux#1110]
I'm not sure if that's a problem with the code base but I noticed different indexers using different cases for the API limit responses.

Tabula Rasa: `<newznab:apilimits apicurrent="763" apimax="8000" grabcurrent="4" grabmax="8000" apioldesttime="Thu, 30 Apr 2020 12:39:38 +0200" graboldesttime="Thu, 30 Apr 2020 19:54:30 +0200"/>`

Drunken Slug: `<newznab:apilimits apiCurrent="44" apiMax="50" grabMax="5"/>`

**Comment by DariusIII** [comment]
nZEDb (drunkenslug is based on it) has older code for that, while i followed newznab with the changes.
If this causes an issue for hydra, i will do a change in nZEDb (i am one of the devs there), and make it comply with newznab and NNTmux.

**Comment by theotherp** [comment]
I've already added code to NZBHydra to read both, so it's fixed there. But it will probably confuse other software that isn't aware of the issue. Hydra will work with either format, I just thought I should let you know. It's probably best if you fix it in nZEDB. Cheers.

**Comment by Wally73** [comment]
all i can find in nzedb is https://github.com/nZEDb/nZEDb/commit/517d6286569c89a9a1538c2540640f066624d3a0

**Comment by DariusIII** [comment]
Yeah, that was added by me :) I will fix the case usage.
