### ISSUE TITLE
BadMethodCallException This cache store does not support tagging. http://192.168.1.100/login

### ISSUE THREAD

**Issue by FONMaster** [NNTmux/newznab-tmux#1115]
After chasing this for two weeks - I think I've found why logins are always bouncing back to the login screen. I enabled debugging, and after I enter credentials into nntmux, It's throwing this error:

BadMethodCallException This cache store does not support tagging. http://192.168.1.100/login

My quick research on laravel (of which I know nothing) says that tagging isn't supported in the cache. I added:

CACHE_DRIVER=array

to the .env and cleared the cache, and I thought that fixed it... but no joy when I changed browsers. (Here's where I found the original post. https://stackoverflow.com/questions/37462365/laravel-cache-store-does-not-support-tagging) 

The good thing is that I can now at least log in and configure and run, so I'm better than I was... but it looks like an opportunity for a quick upgrade.

Am I on to something?

Russell

**Comment by DariusIII** [comment]
You are right, tagging is supported only with memcached and redis. But i am on the way of removing tagging from NNTmux, as it slows down things and is not used as i wanted it to be.
Will implement better tagging in the future, probably based on Elasticsearch.

**Comment by FONMaster** [comment]
I'm wondering if the .env in the repository (or the installation instructions) should be updated with CACHE_DRIVER=array. Yes?

This has sent me on a mission now to figure out how to configure redis. I think I've figured out I have to:

composer require predis/predis

and 

CACHE_DRIVER=redis

Wish me luck. What an adventure!

Russell
