### ISSUE TITLE
Issues Setting up NNTmux Database

### ISSUE THREAD

**Issue by brando56894** [NNTmux/newznab-tmux#1117]
**Describe the bug**
I've tried both the docker-compose setup and doing it manually but in either setup I have issues with the mysql database. Using docker, the issue is that root can't login locally or remotely. Doing it manually I get the following error at **Step 11: Setting up NNTmux**

> bran@newznab:/var/www/NNTmux$ php artisan nntmux:install
> 
>  Are you sure you want to install NNTmux? This will wipe your database!! (yes/no) [no]:
>  > yes
> 
> Migrating tables and seeding them with initial data
> 
>    Illuminate\Database\QueryException 
> 
>   SQLSTATE[HY000] [2002] No such file or directory (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')
> 
>   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
>     667|         // If an exception occurs when attempting to run a query, we'll format the error
>     668|         // message to include the bindings with SQL, which will make this exception a
>     669|         // lot more helpful to the developer instead of just the database's errors.
>     670|         catch (Exception $e) {
>   > 671|             throw new QueryException(
>     672|                 $query, $this->prepareBindings($bindings), $e
>     673|             );
>     674|         }
>     675| 
> 
>       +42 vendor frames 
>   43  app/Console/Commands/InstallNntmux.php:72
>       Illuminate\Console\Command::call()
> 
>       +14 vendor frames 
>   58  artisan:35
>       Illuminate\Foundation\Console\Kernel::handle()

I am able to login to the database using the socket as root, and via my user nntmux, the nntmux database exists, but has no tables.

**To Reproduce**
Continue through the guide and after configuring your .env file execute **php artisan nntmux:install**

**Expected behavior**
It should connect to the database, import the schema, and then continue with the setup

**Installation (please complete the following information):**
 - OS: Ubuntu 19.04 Eoan
 - PHP version 7.4.7
 - NNTmux version or commit: dev branch - latest commit 8ff618dd08fcac3835131d788bb347df37a4adc7

**Additional context**
I'm pretty competent with LAMP stacks and have setup NewzNab before, so I have an idea about what I'm doing, but since the majority of this is in PHP it's kinda hard for me to debug. I've been trying on and off for weeks to get this working to no avail. First trying the master branch, then docker, then dev, then docker again.

**Comment by DariusIII** [comment]
Have you created the database before you tried to install NNTmux?

**Comment by brando56894** [comment]
Yes, the database exists

> MariaDB [(none)]> use nntmux;
> Database changed
> MariaDB [nntmux]> show tables;
> Empty set (0.000 sec)
> 
> MariaDB [nntmux]>

**Comment by DariusIII** [comment]
Try to start all over again, as install cannot find table needed to continue.
