### ISSUE TITLE
Some existing releases missing from Web-interface.

### ISSUE THREAD

**Issue by FzeroE** [NNTmux/newznab-tmux#1118]
**Describe the bug**
Some releases are missing from the web-interface and search. But they do exist in the DB. 
**To Reproduce**
Find a missing release in the DB
ex "SELECT * FROM nntmux.releases where searchname like '%.YourReleaseName.%' "
copy the GUID
open your server and add the /details/guid to the URL and the server opens the release. 
ex https://servername/details/37dbf9cc-e005-4de8-8ac5-bc4ab0f20254
Edit of the release and download works fine.

**Expected behavior**
To have all releases show up in their categories and be findable with search.

**Additional context**
Using Master 
Dist Centos7 with MariaDB 10.4.6

Have tried to use "populate_rt_indexes.php" script to fix the search index for both releases_rt and predb_rt.
And i have also turned off the blacklist function.

Any pointers what can be the problem?

**Comment by DariusIII** [comment]
Sorry for late response. If the release havent been processed by additional post processing, it will not show up on frontend.

**Comment by DariusIII** [comment]
You need to reset postprocessing completely.
