### ISSUE TITLE
Login not possible after installing v1.7.0 (also older version) not working

### ISSUE THREAD

**Issue by teaborn2** [NNTmux/newznab-tmux#1126]
**Describe the bug**
It's not possible login with the default ".env" after a fresh installation. Tested on multiple hosts and many different attempts.

**To Reproduce**
1. Cloned the repository and checked out "v1.7.0".

2. Configured the ".env" file based on ".env.example"
diff -y /opt/newznab-tmux/.env /opt/newznab-tmux/.env.example | grep "|" | egrep -v "^NNTP|ADMIN_PASS|ADMIN_EMAIL"
DB_HOST=mariadb                                               | DB_HOST=127.0.0.1
DB_ROOTPASSWORD=root                                          | DB_ROOTPASSWORD=  #only needed for install.sh for docker base
DB_USERNAME=nntmux                                            | DB_USERNAME=
DB_PASSWORD=nntmux                                            | DB_PASSWORD=
SPHINX_HOST=manticore                                         | SPHINX_HOST=localhost
ADMIN_USER=admin                                              | ADMIN_USER=
APP_TZ=Europe/Vienna                                          | APP_TZ=Europe/Paris
APP_KEY=base64:DLS5Bgw8HK6GDtCs0dGONqEzl91XeK6UpnKJI4K3Jeo=   | APP_KEY=
REDIS_HOST=redis                                              | REDIS_HOST=127.0.0.1
REDIS_CLIENT=phpredis                                         | REDIS_CLIENT = phpredis
RENAME_PAR2=false                                             | RENAME_PAR2 = false

3. Configured "docker-compose.yml" to make it outside accesible
diff -y docker-compose.yml.orig docker-compose.yml | grep "|"
      - 127.0.0.1:8089:80                                     |       - 0.0.0.0:8089:80

4. docker-compose to install application

5. Logged in into Container "nn-tmux" and fixed permissions in "/var/www/NNTmux" and "/var/lib/php/sessions"

6. Set apache log level to "debug"

7. Run install scipt "docker/install.sh" to setup database (predb import was ignored)

8. Setup manticore
mysql -u root -proot -e "INSTALL SONAME 'ha_sphinx'"

php /var/www/NNTmux/misc/manticoresearch/create_se_tables.php manticore 9312"
php /var/www/NNTmux/misc/manticoresearch/populate_rt_indexes.php releases_rt"
php /var/www/NNTmux/misc/manticoresearch/populate_rt_indexes.php predb_rt"

9.  Made some debugging commands:
docker logs nn-tmux
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.6. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.6. Set the 'ServerName' directive globally to suppress this message
[Tue Aug 25 08:41:36.642343 2020] [core:warn] [pid 8] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Aug 25 08:41:36.664355 2020] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Aug 25 08:41:36.664788 2020] [core:notice] [pid 8] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.5. Set the 'ServerName' directive globally to suppress this message
[Tue Aug 25 08:43:24.126874 2020] [core:warn] [pid 7] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Aug 25 08:43:24.139383 2020] [mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Aug 25 08:43:24.144263 2020] [core:notice] [pid 7] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Tue Aug 25 08:44:19.051168 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of Require all granted: granted
[Tue Aug 25 08:44:19.051456 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of <RequireAny>: granted
[Tue Aug 25 08:44:19.052612 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of Require all granted: granted
[Tue Aug 25 08:44:19.052652 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of <RequireAny>: granted
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:19 +0200] "GET / HTTP/1.1" 302 1013 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 08:44:19.742353 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of Require all granted: granted
[Tue Aug 25 08:44:19.742399 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of <RequireAny>: granted
[Tue Aug 25 08:44:19.742556 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of Require all granted: granted
[Tue Aug 25 08:44:19.742593 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of <RequireAny>: granted
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:19 +0200] "GET /login HTTP/1.1" 200 1747 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 08:44:19.871241 2020] [deflate:debug] [pid 8] mod_deflate.c(854): [client my_hidden_ip_adress:49653] AH01384: Zlib: Compressed 4910 to 1477 : URL /index.php
[Tue Aug 25 08:44:19.968798 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:19.968846 2020] [authz_core:debug] [pid 8] mod_authz_core.c(809): [client my_hidden_ip_adress:49653] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:19.996560 2020] [deflate:debug] [pid 8] mod_deflate.c(854): [client my_hidden_ip_adress:49653] AH01384: Zlib: Compressed 373351 to 55142 : URL /assets/css/all-css.css, referer: http://my.personal-domain.xxx:8089/login
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:19 +0200] "GET /assets/css/all-css.css HTTP/1.1" 200 55499 "http://my.personal-domain.xxx:8089/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 08:44:20.003900 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client my_hidden_ip_adress:49654] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:20.004310 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client my_hidden_ip_adress:49654] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:20.333506 2020] [deflate:debug] [pid 9] mod_deflate.c(854): [client my_hidden_ip_adress:49654] AH01384: Zlib: Compressed 2183338 to 744383 : URL /assets/js/all-js.js, referer: http://my.personal-domain.xxx:8089/login
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:20 +0200] "GET /assets/js/all-js.js HTTP/1.1" 200 745462 "http://my.personal-domain.xxx:8089/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 08:44:20.872608 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client my_hidden_ip_adress:49654] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/assets/css/all-css.css
[Tue Aug 25 08:44:20.872673 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client my_hidden_ip_adress:49654] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/assets/css/all-css.css
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:20 +0200] "GET /assets/css/green@2x.png HTTP/1.1" 200 3402 "http://my.personal-domain.xxx:8089/assets/css/all-css.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 08:44:39.264454 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.264566 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.264825 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.264838 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/login
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:39 +0200] "POST /login HTTP/1.1" 302 1013 "http://my.personal-domain.xxx:8089/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 08:44:39.456494 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.456539 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.456670 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of Require all granted: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.456693 2020] [authz_core:debug] [pid 10] mod_authz_core.c(809): [client my_hidden_ip_adress:49655] AH01626: authorization result of <RequireAny>: granted, referer: http://my.personal-domain.xxx:8089/login
[Tue Aug 25 08:44:39.527483 2020] [deflate:debug] [pid 10] mod_deflate.c(854): [client my_hidden_ip_adress:49655] AH01384: Zlib: Compressed 4910 to 1477 : URL /index.php, referer: http://my.personal-domain.xxx:8089/login
localhost:80 my_hidden_ip_adress - - [25/Aug/2020:08:44:39 +0200] "GET /login HTTP/1.1" 200 1747 "http://my.personal-domain.xxx:8089/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"

docker exec -it newznab-tmux_mariadb_1 sh -c "mysql -unntmux -pnntmux nntmux -e \"select created_at, content from telescope_entries\" -BNr"
-> Nothing

docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                         NAMES
d73af16255bb        newznab-tmux_nn-tmux          "apachectl -D FOREGR…"   19 minutes ago      Up 5 minutes        0.0.0.0:8089->80/tcp                          nn-tmux
49a546c1c83a        newznab-tmux_nn-tmux-ui       "sudo -E -u notroot …"   19 minutes ago      Up 5 minutes        80/tcp, 127.0.0.1:12345->12345/tcp            nn-tmux-ui
6d507f085764        manticoresearch/manticore:3   "docker-entrypoint.s…"   19 minutes ago      Up 5 minutes        9306/tcp, 9308/tcp, 9312/tcp, 9315-9325/tcp   newznab-tmux_manticore_1
f6975a616d78        mariadb:10                    "docker-entrypoint.s…"   19 minutes ago      Up 5 minutes        3306/tcp                                      newznab-tmux_mariadb_1
70dfc5e51267        redis:5                       "docker-entrypoint.s…"   19 minutes ago      Up 5 minutes        6379/tcp                                      newznab-tmux_redis_1

root@f6975a616d78:/# ping -c 4 redis
PING redis (172.25.0.2): 56 data bytes
64 bytes from 172.25.0.2: icmp_seq=0 ttl=64 time=0.687 ms
64 bytes from 172.25.0.2: icmp_seq=1 ttl=64 time=0.282 ms
64 bytes from 172.25.0.2: icmp_seq=2 ttl=64 time=0.163 ms
64 bytes from 172.25.0.2: icmp_seq=3 ttl=64 time=0.181 ms
--- redis ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.163/0.328/0.687/0.212 ms

root@f6975a616d78:/# ping -c 4 manticore
PING manticore (172.25.0.4): 56 data bytes
64 bytes from 172.25.0.4: icmp_seq=0 ttl=64 time=0.507 ms
64 bytes from 172.25.0.4: icmp_seq=1 ttl=64 time=0.208 ms
64 bytes from 172.25.0.4: icmp_seq=2 ttl=64 time=0.251 ms
64 bytes from 172.25.0.4: icmp_seq=3 ttl=64 time=0.174 ms
--- manticore ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.174/0.285/0.507/0.131 ms

root@f6975a616d78:/# ping -c4 mariadb
PING mariadb (172.25.0.3): 56 data bytes
64 bytes from 172.25.0.3: icmp_seq=0 ttl=64 time=0.179 ms
64 bytes from 172.25.0.3: icmp_seq=1 ttl=64 time=0.152 ms
64 bytes from 172.25.0.3: icmp_seq=2 ttl=64 time=0.105 ms
64 bytes from 172.25.0.3: icmp_seq=3 ttl=64 time=0.119 ms
--- mariadb ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.105/0.139/0.179/0.029 ms

root@f6975a616d78:/# telnet redis 6379
Trying 172.25.0.2...
Connected to redis.
Escape character is '^]'.
ehlo
-ERR unknown command `ehlo`, with args beginning with:
quit
+OK
Connection closed by foreign host.

root@f6975a616d78:/# telnet manticore 9306
Trying 172.25.0.4...
Connected to manticore.
Escape character is '^]'.
a
3.5.0 1d34c491@200722 releas(▒!
mysql_native_password

root@f6975a616d78:/# telnet manticore 9312
Trying 172.25.0.4...
Connected to manticore.
Escape character is '^]'.
ehlo
].
quit
].Connection closed by foreign host.

root@f6975a616d78:/# mysql -unntmux -pnntmux nntmux -e "show tables"
+------------------------+
| Tables_in_nntmux       |
+------------------------+
| anidb_episodes         |
...
| xxxinfo                |

**Expected behavior**
I Don't see any misconfiguration. It should be possible to login

**Installation (please complete the following information):**
 - OS: Debian 10 Buster
 - PHP version 7.3 -> nntmux is running via docker-compose
 - NNTmux version or commit 1.7.0 Stable

**Additional context**
All was mentioned before

**Comment by DariusIII** [comment]
I really can't help you with docker as i never used it and support was added by other users through PR.

**Comment by Fossil01** [comment]
Bash into the container and check the Laravel logs.

**Comment by teaborn2** [comment]
I've checked the laravel logs and see only db connection error before the tables were created.

Full logs are here, but if prefered i can post them in this thread: https://cl1p.net/uqzcvedgafbxo

-rwxrwxrwx 1 www-data www-data 406606 Aug 25 08:43 /opt/newznab-tmux/storage/logs/laravel-2020-08-25.log
-> The log is before my login attempt 08:44. So i assume nothing has been logged there. Are there any switches or settings to see more details.

Thanks in advance for your support.

**Comment by teaborn2** [comment]
Here you can see the tables are there:
root@f6975a616d78:/# mysql -unntmux -pnntmux nntmux -e "select * from settings limit 10" -BNr
                addpar2 0       When going through PAR2 files, add them to the RAR file content list of the NZB.        addpar2
                alternate_nntp  0       This sets Postproccessing Additional/Nfo to use the alternate NNTP provider as set in config.php.       alternate_nntp
                backfillthreads 1       The number of threads for backfill.     backfillthreads
                binarythreads   1       The number of threads for update_binaries. If you notice that you are getting a lot of parts into the partrepair table, it is possible that you USP is not keeping up with the requests. Try to reduce the threads to safe scripts or stop using safe scripts until improves. Ar least until the cause can be determined.    binarythreads
                book_reqids     7010    Categories of Books to lookup information for (only work if Lookup Books is set to yes).        book_reqids
                checkpasswordedrar      0       Whether to attempt to peek into every release, to see if rar files are password protected.      checkpasswordedrar
                completionpercent       95      The minimum completion % to keep a release. Set to 0 to disable.        completionpercent
                compressedheaders       0       Some servers allow headers to be sent over in a compressed format.  If enabled this will use much less bandwidth, but processing times may increase.<br />If you notice that update binaries or backfill seems to hang, look in htop and see if a group is being processed. If so, first try disabling compressed headers and let run until it processes the group at least once, then you can re-enable compressed headers.      compressedheaders
                crossposttime   2       The time in hours to check for cross-posted releases.   crossposttime
                currentppticket 0               currentppticket

**Comment by Fossil01** [comment]
The reason is in the logs:

```
Base table or view not found: 1146 Table 'nntmux.settings' doesn't exist
Base table or view not found: 1146 Table 'nntmux.telescope_entries' doesn't exist
```

Your database was not setup (correctly).

**Comment by teaborn2** [comment]
As stated before. I knew the database wasn't in place. The errors are not from a login try. There are from the setup, because application was started and the right tables aren't in place.
I tried your suggestion and made a new installation with these settings for debug/log:
egrep -i "log|debug" .env
ELASTICSEARCH_LOGGING=false
NN_MULTIPROCESSING_LOG_TYPE=6
APP_DEBUG=true
LOG_CHANNEL=stack
BROADCAST_DRIVER=log
SMARTY_DEBUG=false
TMDB_LOG=false
TELESCOPE_LOG_WATCHER=true

After that i tried 2 logins with webgui, but nothing happend. I didn't see anything in the lavendel logs. Only apache web-servers gives some output and these results are good: authorization result of <RequireAny>: granted, referer...

Are there any more settings in ".env" that i can made. Yesterday i tried with "APP_DEBUG=true" and "APP_ENV=local" without success.

**Comment by Fossil01** [comment]
run `php artisan config:cache` and try again.

**Comment by teaborn2** [comment]
root@a3b18d629f4b:/var/www/NNTmux# php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!

root@a3b18d629f4b:/var/www/NNTmux# ls -al storage/logs/laravel-2020-08-25.log
-> Tried login with user "admin. Nothing happens and the logfile wasn't filled.
-rwxrwxrwx 1 www-data www-data 407231 Aug 25 14:39 storage/logs/laravel-2020-08-25.log

Only apache2 tells something:
[Tue Aug 25 14:59:26.154758 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client hidden_client:54498] AH01626: authorization result of <RequireAny>: granted, referer: http://hidden_server:8089/login
localhost:80 hidden_client - - [25/Aug/2020:14:59:26 +0200] "POST /login HTTP/1.1" 302 1013 "http://hidden_server:8089/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
[Tue Aug 25 14:59:26.310609 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client hidden_client:54498] AH01626: authorization result of Require all granted: granted, referer: http://hidden_server:8089/login
[Tue Aug 25 14:59:26.310654 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client hidden_client:54498] AH01626: authorization result of <RequireAny>: granted, referer: http://hidden_server:8089/login
[Tue Aug 25 14:59:26.311117 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client hidden_client:54498] AH01626: authorization result of Require all granted: granted, referer: http://hidden_server:8089/login
[Tue Aug 25 14:59:26.311155 2020] [authz_core:debug] [pid 9] mod_authz_core.c(809): [client hidden_client:54498] AH01626: authorization result of <RequireAny>: granted, referer: http://hidden_server:8089/login
[Tue Aug 25 14:59:26.363135 2020] [deflate:debug] [pid 9] mod_deflate.c(854): [client hidden_client:54498] AH01384: Zlib: Compressed 4910 to 1479 : URL /index.php, referer: http://hidden_server:8089/login
localhost:80 hidden_client - - [25/Aug/2020:14:59:26 +0200] "GET /login HTTP/1.1" 200 1749 "http://hidden_server:8089/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"

**Comment by Fossil01** [comment]
Then I don't know. Sounds like the Docker setup is broken.

**Comment by teaborn2** [comment]
@Fossil01 You're right the docker setup was broken, because some file locations has changed from the past to now. I've managed to correct the necessary setup files. Here are the commands for fixing (path must maybe changed):

`sed -i -e "s/sphinxsearch/manticoresearch/g" /opt/newznab-tmux/docker/install.sh`

`sed -i -e "/sphinx.conf/s/-.*/- \$PWD\/misc\/manticoresearch\/manticore.conf:\/etc\/manticoresearch\/manticore.conf/" /opt/newznab-tmux/docker-compose.yml`

After all containers are build and ready you've to fix the cache permissions:

`# docker exec -it nn-tmux bash`

`sudo -E -u www-data php artisan config:cache`

I've also upgraded the docker files to use newer versions (Ubuntu 20.04 ...). Here is the code.

docker-compose.yml

version: '3.4'
services:
  redis:
    image: redis:5
    restart: unless-stopped
    volumes:
      - $PWD/docker/redis-data;/data
      - $PWD/docker/redis.conf:/usr/local/etc/redis/redis.conf
  manticore:
    image: manticoresearch/manticore:3.5.0
    restart: unless-stopped
    volumes:
      - $PWD/docker/manticore-data;/var/lib/manticore/data
      - $PWD/misc/manticoresearch/manticore.conf:/etc/manticoresearch/manticore.conf
  mariadb:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - $PWD/docker/my.cnf:/etc/mysql/conf.d/newsnab-tmux.cnf
      - $PWD/docker/mariadb-data:/var/lib/mysql
      - $PWD:/var/www/NNTmux/
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${APP_TZ}
  nn-tmux: &nn-tmux
    build:
      context: .
    restart: unless-stopped
    container_name: nn-tmux
    command: apachectl -D FOREGROUND
    volumes:
      - /var/www/NNTmux/vendor/
      - $PWD:/var/www/NNTmux/
    env_file: .env
    ports:
      - 0.0.0.0:8088:80
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}
    depends_on:
      - mariadb
      - redis
      - manticore
  nn-tmux-ui:
    <<: *nn-tmux
    container_name: nn-tmux-ui
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}
      COLUMNS: "`tput cols`"
      LINES: "`tput lines`"
    command: sudo -E -u notroot php artisan tmux-ui:start
    ports:
      - 127.0.0.1:12345:12345

Dockerfile:

FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -q update && \
    apt-get -qy upgrade && \
    apt-get install -qy screen time sudo unzip software-properties-common nano git make automake build-essential pkg-config libevent-dev libncurses5-dev fonts-powerline powerline mariadb-client libmysqlclient-dev bison byacc unrar p7zip-full mediainfo lame ffmpeg apache2 libapache2-mod-php7.4 php-pear php7.4 php7.4-cli php7.4-dev php7.4-common php7.4-curl php7.4-json php7.4-gd php7.4-mysql php7.4-mbstring php7.4-xml php7.4-intl php7.4-fpm php7.4-bcmath php7.4-zip php-imagick

RUN git clone https://github.com/tmux/tmux.git && \
    cd tmux && \
    git fetch --all --tags --prune && \
    git checkout 3.1 && \
    sh autogen.sh && \
    ./configure && make && \
    make install && \
    cd .. && \
    rm -rf tmux

ENV HASH e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a
RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo
COPY docker/php.ini /etc/php/7.4/apache2/conf.d/99-nn-tmux.ini
COPY docker/php.ini /etc/php/7.4/cli/conf.d/99-nn-tmux.ini
COPY docker/NNTmux.conf /etc/apache2/sites-available/NNTmux.conf
RUN ln -sf /dev/stdout /var/log/apache2/access.log
RUN ln -sf /dev/stdout /var/log/apache2/other_vhosts_access.log
RUN ln -sf /dev/stderr /var/log/apache2/error.log
RUN a2dissite 000-default && a2ensite NNTmux && a2enmod rewrite && service apache2 restart
RUN chown -R www-data:www-data /var/www
RUN useradd -ms /bin/bash notroot && usermod -aG www-data notroot && usermod -aG notroot www-data

USER www-data
RUN mkdir /var/www/NNTmux/ && chmod 775 /var/www/NNTmux/
WORKDIR /var/www/NNTmux
COPY composer.json composer.lock /var/www/NNTmux/
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader
COPY . ./
RUN composer dump-autoload

USER root
COPY docker/install.sh /tmp/install.sh
EXPOSE 80

docker/install.sh:

#!/bin/bash
mysqladmin ping --wait=30 --host=$DB_HOST --port=$DB_PORT --user=root --password=$DB_ROOTPASSWORD
mysql --host=$DB_HOST --user=root --password=$DB_ROOTPASSWORD -e "INSTALL SONAME 'ha_sphinx';"
mysql --host=$DB_HOST --user=root --password=$DB_ROOTPASSWORD -e "GRANT ALL PRIVILEGES ON *.* TO $DB_USERNAME@'%' WITH GRANT OPTION;"
sudo -E -u www-data php artisan nntmux:install
sudo -E -u www-data php /var/www/NNTmux/misc/manticoresearch/create_se_tables.php $SPHINX_HOST 9312
sudo -E -u www-data php /var/www/NNTmux/misc/manticoresearch/populate_rt_indexes.php releases_rt
sudo -E -u www-data php /var/www/NNTmux/misc/manticoresearch/populate_rt_indexes.php predb_rt
read -p "Do you want to batch import predb now (this will take an hour or two)? (y/n): " yn
case $yn in
    [Yy]* ) sudo -E -u notroot php /var/www/NNTmux/cli/data/predb_import_daily_batch.php 0 remote false
esac

One more thing to mention. My ".env"-file was wrong. I've set "SESSION_DOMAIN=" to blank value.
