### ISSUE TITLE
Indicate obfuscated results

### ISSUE THREAD

**Issue by theotherp** [NNTmux/newznab-tmux#1133]
I read a discussion on reddit where somebody said that automation tools aren't sophisticated enough to choose obfuscated results over non-obfuscated ones (which might increase the chance of download completion). But in order to so they'd need to know which results are obfuscated first.

I wonder if the indexer could add a newznab attribute to results indicating if their obfuscated (e.g. `<newznab:attr name="obfuscated" value="1"/>` or whatever.

I admit that I know next to nothing how an indexer works but the software has to actively deobfuscate releases somehow and so it could the information with the search results.

That information could then by used by automation tools and I could mark it somehow in NZBHydra.

**Comment by Fossil01** [comment]
Hardly anything is not obfuscated right now so I don’t think  a change is needed IMHO.

**Comment by DariusIII** [comment]
I have answered there, but short and final answer would be a hard NO. 
I have explained my stance in that thread in more detail.

**Comment by theotherp** [comment]
Alright.
