### ISSUE TITLE
git pull breaks admin/group-list breaks activate, backfill, and options selectors

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1134]
Git pull killed some functionality.  Toggling group options activate, backfill, and options selectors on admin/group-list page returns:

"Error in ajax_group_status:error"

Did this:
1) drake@machine:/var/www/NNTmux$ git stash
Saved working directory and index state WIP on master: ad55222a3 Merge branch 'dev'

2) drake@machine:/var/www/NNTmux$ git pull
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 298 (delta 142), reused 286 (delta 133), pack-reused 0
Receiving objects: 100% (298/298), 839.89 KiB | 1.72 MiB/s, done.
Resolving deltas: 100% (142/142), completed with 74 local objects.
From https://github.com/NNTmux/newznab-tmux
   ad55222a3..632805254  master     -> origin/master
   86bd58f8e..78a4da686  dev        -> origin/dev
Updating ad55222a3..632805254
Fast-forward

/var/www/NNTmux$ git pull
remote: Enumerating objects: 298, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 298 (delta 142), reused 286 (delta 133), pack-reused 0
Receiving objects: 100% (298/298), 839.89 KiB | 1.72 MiB/s, done.
Resolving deltas: 100% (142/142), completed with 74 local objects.
From https://github.com/NNTmux/newznab-tmux
   ad55222a3..632805254  master     -> origin/master
   86bd58f8e..78a4da686  dev        -> origin/dev
Updating ad55222a3..632805254
Fast-forward...
<<snip!>>
Package manifest generated successfully.

**Comment by DariusIII** [comment]
Those are all javascript based controls, will have to investigate what caused the braking change.

**Comment by DariusIII** [comment]
Fixed in commit https://github.com/NNTmux/newznab-tmux/commit/ee6d5ac485fc8c5f114d9a41d3772fe3f4a87875

**Comment by DrakeJones** [comment]
Thank you.
