### ISSUE TITLE
Login does not work after setup

### ISSUE THREAD

**Issue by do0zer** [NNTmux/newznab-tmux#1135]
**Describe the bug**
After setting up the login set in .env does not function

**To Reproduce**
1. Install
2. attempt to login using the account specified in the .env

**Expected behavior**
Login to work

**Screenshots**

**Installation (please complete the following information):**
Ubuntu NNTMUX master

**Additional context**
None

**Comment by Fossil01** [comment]
Check the logs

**Comment by do0zer** [comment]
There is nothing related in the system or php logs

**Comment by do0zer** [comment]
Install reddis and am able to login
You should put a reddis install comment in the install docs maybe

**Comment by Fossil01** [comment]
Laravel logs are in storage/logs
