### ISSUE TITLE
Error while building docker image file

### ISSUE THREAD

**Issue by gazaz** [NNTmux/newznab-tmux#1136]
**Describe the bug**
Getting an error while building a docker image 

I am using Docker desktop for windows in windows 10

I'm getting an error in the Dockerfile at the point where it installs composer. I'm competely new to docker so I could be doing soemthing wrong. Stops at this point each time.

[4/20] RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&     php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo:
#6 0.904 Installer corrupt
#6 0.939 Could not open input file: composer-setup.php

**Comment by gazaz** [comment]
Tried agaun wth a fresh install of Ubuntu18.04 running docker. Just incase the windows install of docker was a problem. Same error thiugh builiding the image.

Step 6/25 : RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else
 { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&     php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/presti
ssimo
 ---> Running in 62f686d26569
Installer corrupt
Could not open input file: composer-setup.php
The command '/bin/sh -c cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'
; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&     php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hira
k/prestissimo' returned a non-zero code: 1

**Comment by stayupthetree** [comment]
edit the Dockerfile

Change 
`RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo`

to
`RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r 'if (hash_file("SHA384", "composer-setup.php") === preg_filter("#^.*?<pre>|</pre>.*$#s", "", file_get_contents("https://composer.github.io/pubkeys.html"))) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;' && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo`

Also change anywhere you see a reference to php 7.3 to 7.4


also 

change
`RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader`


to

`RUN /usr/local/bin/composer install --prefer-dist --no-scripts --no-dev --no-autoloader
`

**Comment by gazaz** [comment]
Thanks for helping. I got slightly further, but still getting an error. Couldn't get past this point .

I did make the recommended changes and updated all the 7.3 to 7.4

Am I missing something simple ?

Here is the error ,.....

[ 4/20] RUN cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r 'if (hash_file("SHA384", "composer-setup.php") === preg_filter("#^.*?<pre>|</pre>.*$#s", "", file_get_contents("https://composer.github.io/pubkeys.html"))) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;' &&  php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo:
#7 0.945 Installer verified
#7 0.982 /bin/sh: 1:  php: not found
------
executor failed running [/bin/sh -c cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php && php -r 'if (hash_file("SHA384", "composer-setup.php") === preg_filter("#^.*?<pre>|</pre>.*$#s", "", file_get_contents("https://composer.github.io/pubkeys.html"))) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;' && \ php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer global require hirak/prestissimo]: runc did not terminate successfully

**Comment by stayupthetree** [comment]
I'm working on something trying to get it 100% working. I'll respond back when I am finished, got it MOST of the way through. Having some struggles with the mariadb part.

**Comment by gazaz** [comment]
> I'm working on something trying to get it 100% working. I'll respond back when I am finished, got it MOST of the way through. Having some struggles with the mariadb part.

Any luck getting it to work?

**Comment by stayupthetree** [comment]
I can get it completely installed but run into the same issue that I have another post about. No matter how many times I try to login it just keeps going to the login screen. Can't make it past /login

**Comment by gazaz** [comment]
> I can get it completely installed but run into the same issue that I have another post about. No matter how many times I try to login it just keeps going to the login screen. Can't make it past /login

Thanks for trying. If you manage to get it working can you post the update ?

**Comment by DrakeJones** [comment]
This may not be the cause of your login issue, but in my case I can't log in via any route other then that set specifically in the .env APP_URL; i.e., "localhost" or local machine IP address for intranet login, or your FQDN or external IP address if your trying to login via the internet.  You can **see** the login screen from the other addresses, but not actually log in that way.

**Comment by stayupthetree** [comment]
> > I can get it completely installed but run into the same issue that I have another post about. No matter how many times I try to login it just keeps going to the login screen. Can't make it past /login
> 
> Thanks for trying. If you manage to get it working can you post the update ?

Absolutely! I haven't given up yet. Going to tinker with the suggestion from Drake below!
