### ISSUE TITLE
Can't login at all ever

### ISSUE THREAD

**Issue by stayupthetree** [NNTmux/newznab-tmux#1138]
I have no logs that say why. Tell me where to find them and I will.

I have done a fresh intall about 10 times on different versions of Ubuntu. Following all the steps. I load the webpage, type in the admin creds I put in .env and then click login. It just loops. Never actually logs in. Just loops over and over and over. Please help I want to scream.

**Comment by HengeDK** [comment]
same here

**Comment by DariusIII** [comment]
What are you using for caching? Redis works best, file is wonky.

**Comment by HengeDK** [comment]
yes redis
but no matter what. keeps looping to login page
same if you choose register

**Comment by Fossil01** [comment]
Have you checked the webserver, PHP and/or Laravel logs?

**Comment by egyptianbman** [comment]
Looking at recent commits, I see 2fa was recently added. I wonder if you pulled the code in the midst of related commits. Make sure your env file contains `OTP_ENABLED=false`. If not, maybe that is what's causing an auth loop.

**Comment by DrakeJones** [comment]
Thank you both.

Thnks F01 - It's been happening for a month or so... Nothing telling in PHP error log or Nginx error log, but lots of this gripping in laravelerror log:

020-12-29 05:51:49] NNTmux.ERROR: Trying to access array offset on value of type int {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type int at /var/www/NNTmux/Blacklight/processing/Videos.php:172)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/processing/Videos.php(172): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/processing/tv/TVDB.php(108): Blacklight\\processing\\Videos->getByTitle()
#2 /var/www/NNTmux/Blacklight/processing/PostProcess.php(243): Blacklight\\processing\\tv\\TVDB->processSite()
#3 /var/www/NNTmux/misc/update/postprocess.php(123): Blacklight\\processing\\PostProcess->processTv()
#4 {main}
"} 
```

**Comment by Fossil01** [comment]
That has nothing to do with not being able to login.Is there any information in Redis? (redis-cli info)

**Comment by DariusIII** [comment]
Edit your .env and changhe your environment from production to local and enable debugging and telescope. That should give you a lot more data to work with and will help pinpoint the issue.
