### ISSUE TITLE
Problems with TVDB: TVDB call is locking up post processing. 

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1146]
TVDB call is locking up post processing.  As you, know TVDB is monetizing their service and implemented their API "V4".  Is there a workaround?  An alternate default service, perhaps? Do I have to buy a license or user subscription from TVDB?

Thankx for your time.

Install
 - OS: Ubuntu 20.10
 - PHP version PHP 7.4.7
 - NNTmux version or commit [e.g. 1.0]
drake@onfront:/var/www/NNTmux/misc/update$ php postprocess.php all true
```
Processing TVDB lookup for 100 release(s).
   ErrorException 
  Trying to access array offset on value of type int
  at /var/www/NNTmux/Blacklight/processing/Videos.php:172
    168|         $title2 = str_ireplace('er', 're', $title);
    169|         if ((string) $title !== (string) $title2) {
    170|             $res = $this->getTitleExact($title2, $type, $source);
    171|             if ($res) {
  > 172|                 return $res['id'];
    173|             }
    174|             $pieces = explode(' ', $title2);
    175|             $title2 = '%';
    176|             foreach ($pieces as $piece) {
  1   /var/www/NNTmux/Blacklight/processing/Videos.php:172
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()
  2   /var/www/NNTmux/Blacklight/processing/tv/TVDB.php:108
      Blacklight\processing\Videos::getByTitle()
```

**Comment by Fossil01** [comment]
The v4 API is a completely new API, that is not backwards compatible. So the package used needs to be updated.

**Comment by DrakeJones** [comment]
I must have misinterpreted their announcement.  I just reread their email, which reads in part:

> v4 API Launch
> 
> ((snip)) 
>     The v4 API will launch the week of 11/9.
>     All previous API versions will be deprecated approximately 6 months later, at the end of March 2021. This will allow projects time to convert.
>     Later in 2021, we’ll be adding writable interfaces to the API, allowing projects to push data back into the site.
>     Developers will need to create a new key for v4, which can be done from your TheTVDB dashboard under API Keys.
>     The v4 API is NOT backwards compatible.

So how might I remedy my pp error?

**Comment by egyptianbman** [comment]
FWIW, I ran into the same issue and noticed that all the other surrounding returns just `return $res:` so I removed the `['id']` from that line, making the assumption that whatever is calling is is likely satisfied with an array response.

https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/Videos.php#L172

**Comment by DrakeJones** [comment]
Thank you.  Looks like a recurring time out - but why?
Some logs entries...

**laravel**
[2020-12-31 02:10:36] NNTmux.ERROR: cURL error 28: Operation timed out after 150000 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 28: Operation timed out after 150000 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200)
[stacktrace]
#0 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Client.php(351): GuzzleHttp\\HandlerStack->__invoke()
#11 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\\Client->transfer()
#12 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\\Client->requestAsync()
#13 /var/www/NNTmux/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\\Client->request()
#14 /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/TheTVDbAPI.php(324): GuzzleHttp\\Client->__call()
#15 /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/TheTVDbAPI.php(349): CanIHaveSomeCoffee\\TheTVDbAPI\\TheTVDbAPI->performAPICall()
#16 /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/Route/AuthenticationRoute.php(73): CanIHaveSomeCoffee\\TheTVDbAPI\\TheTVDbAPI->performAPICallWithJsonResponse()
#17 /var/www/NNTmux/Blacklight/processing/tv/TVDB.php(59): CanIHaveSomeCoffee\\TheTVDbAPI\\Route\\AuthenticationRoute->login()
#18 /var/www/NNTmux/Blacklight/processing/PostProcess.php(243): Blacklight\\processing\\tv\\TVDB->__construct()
#19 /var/www/NNTmux/misc/update/postprocess.php(123): Blacklight\\processing\\PostProcess->processTv()
#20 {main}
"} 
[2020-12-31 02:21:01] NNTmux.ERROR: Wrong parameters for Foolz\SphinxQL\Exception\DatabaseException([string $message [, long $code [, Throwable $previous = NULL]]]) {"exception":"[object] (Error(code: 0): Wrong parameters for Foolz\\SphinxQL\\Exception\\DatabaseException([string $message [, long $code [, Throwable $previous = NULL]]]) at /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php:28)
[stacktrace]
#0 /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php(28): Exception->__construct()
#1 /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/SphinxQL.php(274): Foolz\\SphinxQL\\Drivers\\Pdo\\Connection->query()
#2 /var/www/NNTmux/Blacklight/SphinxSearch.php(221): Foolz\\SphinxQL\\SphinxQL->execute()
#3 /var/www/NNTmux/Blacklight/IRCScraper.php(300): Blacklight\\SphinxSearch->searchIndexes()
#4 /var/www/NNTmux/Blacklight/IRCScraper.php(282): Blacklight\\IRCScraper->_insertNewPre()
#5 /var/www/NNTmux/Blacklight/IRCScraper.php(271): Blacklight\\IRCScraper->_checkForDupe()
#6 /var/www/NNTmux/Blacklight/IRCClient.php(429): Blacklight\\IRCScraper->processChannelMessages()
#7 /var/www/NNTmux/Blacklight/IRCScraper.php(202): Blacklight\\IRCClient->readIncoming()
#8 /var/www/NNTmux/Blacklight/IRCScraper.php(148): Blacklight\\IRCScraper->_startScraping()
#9 /var/www/NNTmux/misc/IRCScraper/scrape.php(29): Blacklight\\IRCScraper->__construct()
#10 {main}
"} 

**redis-cli info**
root@oceanfront:~# redis-cli info
# Server
redis_version:5.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:636cde3b5c7a3923
redis_mode:standalone
os:Linux 5.4.0-58-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.2.1
process_id:1145
run_id:9c95e8d4005ef1ae9eb5ccc8b84da0577bed05de
tcp_port:6379
uptime_in_seconds:60094
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:15566570
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:144
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:25507552
used_memory_human:24.33M
used_memory_rss:28467200
used_memory_rss_human:27.15M
used_memory_peak:34456176
used_memory_peak_human:32.86M
used_memory_peak_perc:74.03%
used_memory_overhead:4361116
used_memory_startup:796240
used_memory_dataset:21146436
used_memory_dataset_perc:85.57%
allocator_allocated:25708400
allocator_active:26738688
allocator_resident:30588928
total_system_memory:16763031552
total_system_memory_human:15.61G
used_memory_lua:40960
used_memory_lua_human:40.00K
used_memory_scripts:1560
used_memory_scripts_human:1.52K
number_of_cached_scripts:3
maxmemory:134217728
maxmemory_human:128.00M
maxmemory_policy:allkeys-lru
allocator_frag_ratio:1.04
allocator_frag_bytes:1030288
allocator_rss_ratio:1.14
allocator_rss_bytes:3850240
rss_overhead_ratio:0.93
rss_overhead_bytes:-2121728
mem_fragmentation_ratio:1.12
mem_fragmentation_bytes:2981608
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:3059436
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:3951
rdb_bgsave_in_progress:0
rdb_last_save_time:1609401902
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:856064
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:50644
total_commands_processed:5246886
instantaneous_ops_per_sec:96
total_net_input_bytes:1316997291
total_net_output_bytes:27547406
instantaneous_input_kbps:24.12
instantaneous_output_kbps:0.38
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:1290
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:9180
keyspace_misses:2006728
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:997
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:6fd6108a77bd1f87d849cefd42367b4d595b5c59
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:842.329021
used_cpu_user:234.258532
used_cpu_sys_children:4.680372
used_cpu_user_children:19.339747

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=9300,expires=8,avg_ttl=28586
db1:keys=4,expires=3,avg_ttl=377586
root@nottelling:~#

**Comment by egyptianbman** [comment]
Do you have any php experience? If not, I wouldn't bother running a project like this, where the app communicates with many services and random failures are likely to never end -- (this is and likely will never be a polished app).

According to that stack trace, it seems to be failing here: https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/tv/TVDB.php#L59 which would indicate it's likely an issue with your configuration.

**Comment by DrakeJones** [comment]
Beshoy - Please don’t condescend.  How you do think people learn?  If there is a consensus among the deves that I shouldn’t bother them, tell me now and I won’t post here again.   I’m not a coder, but that doesn’t make me stupid – just ignorant, and that’s transitory.

This is my hobby.  I setup and ran a nZEDb as my personal indexer for about 4 years before I tried to tackle NNTmux.  I’ve been running NNTmux successfully for over year now.  It was and is still a challenge, but I am really enjoying it.  I learn something new almost every day.  The devs have been GREAT about support, but virtually everything I need to know is out there somewhere in the very generous open source community and I can solve virtually any issue myself with enough research - which is what I try to do before posting a request for support.

Albert Einstein used to explain the Theory of Relativity to drunks at the local pub.  He taught people how to learn.  

_FWIW, per you, you had the same problem.  So I removed ['id'] per your suggestion above, https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/Videos.php#L172.  To your credit, that fixed the specific post processing error I originally asked about._

**Comment by DrakeJones** [comment]
Beshoy - Please don’t condescend.  How you do think people learn?  If there is a consensus among the deves that I shouldn’t bother them, tell me now and I won’t post here again.   I’m not a coder, but that doesn’t make me stupid – just ignorant, and that’s transitory.

This is my hobby.  I setup and ran a nZEDb as my personal indexer for about 4 years before I tried to tackle NNTmux.  I’ve been running NNTmux successfully for over year now.  It was and is still a challenge, but I am really enjoying it.  I learn something new almost every day.  The devs have been GREAT about support, but virtually everything I need to know is out there somewhere in the very generous open source community and I can solve virtually any issue myself with enough research - which is what I try to do before posting a request for support.

Albert Einstein used to explain the Theory of Relativity to drunks at the local pub.  He taught people how to learn.  

_FWIW, per you, you had the same problem.  So I removed ['id'] per your suggestion above, https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/Videos.php#L172.  To your credit, that fixed the specific post processing error I originally asked about._

**Comment by Fossil01** [comment]
That's quite the essay. He wasn't being condescending at all tbh. If you don't have a some PHP experience, then running something like NNTmux is going to be a major pain in the ass. There are so many moving parts and external services, plus it's using a PHP Framework which could look even more daunting if you're not familiair.

**Comment by egyptianbman** [comment]
That escalated quickly. First. I don't dev here in any official capacity. Second, I wasn't being condescending. I was simply letting you know that this project isn't for the faint of heart or anyone who doesn't have experience running infrastructure and/or writing php.

Regarding the open source community, every minute spent providing support is a minute spent away from writing code. Too much support from devs can quickly lead to burnout and eventually, abandoned projects. This is why you'll often find devs who refuse to provide support for the sake of maintaining their sanity. If you've appreciated this project I would urge you to support the dev financially if you aren't able to provide support via other means.

Nobody is telling you to stop using this or any other open source software, I would just urge you to spend more time researching the errors and/or looking into the code to see if you can solve the problem yourself and possibly providing a patch instead of just posting every error you get.

**Comment by DariusIII** [comment]
Ok. Lets put the ball down a bit. @DrakeJones enable debugging in .env and set environment to local instead of production. You can additionally enable telescope so you will have nice exceptions view and from there you can follow and check for errors. 
Most of the times these kind of errors come from bad configuration and permissions on folders (even those you think are not used at all).

Now to something that is not related to this issue:

I agree with both @Fossil01 and @egyptianbman . Projects like this will never be polished because NNTmux uses a lot of external libraries that have their own  issues, parts of code are taken from nZEDb as i was one of the devs there (still am but did not contribute any code for a long time now as development there has stalled and i am focused on my own project). NNTmux is just a fun project i like doing as a side job - a hobby to me i love working on.

**Comment by DrakeJones** [comment]
All is well.  I'm familiar with your work, Darius.  And, thank you.  Enabling debugging and setting environment to local instead of production.  (Per Ubuntu-Install-guide I had them disabled for security) .  I do have telescope enabled.  I just have to remind myself to take advantage of it.
