### ISSUE TITLE
releases.php - Could not open input file: misc/update/multiprocessing/.do_not_run/switch.php

### ISSUE THREAD

**Issue by skygnome** [NNTmux/newznab-tmux#1147]
**Describe the bug**
Manually running php releases.php in the misc/update/multiprocessing folder gives an error:

Could not open input file: misc/update/multiprocessing/.do_not_run/switch.php
Task #10 Finished performing release processing

**To Reproduce**
cd /var/www/NTTmux/misc/update/multiprocessing
PHP ./releases.php

**Expected behavior**
for releases to complete when manually run

**Screenshots**
n/a

**Installation (please complete the following information):**
 - OS: Ununto 20.04
 - PHP version 7.4.3
 - NNTmux version or commit [e.g. 1.0]

**Additional context**
Changed line 129 in Blacklight\libraries\Forking.php and added full path to fix the error.
$this->dnr_path = PHP_BINARY.' /var/www/NNTmux/misc/update/multiprocessing/.do_not_run/switch.php "php  ';

I guess most use the tmux script provided but noticed it was killing my CPU and RAM with multiple things running at the same time. Revered back to running a sh script and looping the binaries and releases scripts which was giving me the error. Just flagging up in case someone else comes across the same problem.

**Comment by DariusIII** [comment]
This is not an NNTmux issue but your configuration error.
