### ISSUE TITLE
Misc Category

### ISSUE THREAD

**Issue by egyptianbman** [NNTmux/newznab-tmux#1150]
76% of the releases I have are in the misc category. I'm not certain on whether or not I'm missing something or if these releases just need to be purged. Running `misc/testing/Releases/recategorize.php` at random times seems to move some releases from the misc category. Do you have any tips on how to get more releases to be categorized? Thanks!

**Comment by DrakeJones** [comment]
Just for ducks you might want to try running /misc/testing/Releases/fixReleaseNames.php.  Not the solution you're looking for, but depending on the group, you may get quite few extra properly categorized releases.  Fixed release names are also re-categorized.

**Comment by egyptianbman** [comment]
Thanks for the tip, @DrakeJones. I've run `fixReleaseNames.php` with all the options against the full set and it renamed a few. I've also run `misc/testing/Releases/recategorize.php` -- I actually did quite a bit of work on that script as it seems to have a memory leak and isn't able to complete without an OOM. I've written a script and made modifications that allow me to run through batches at a time to get through the full set without failure.

Sadly, both of those options didn't make a dent in the ratio of misc/other.

**Comment by DariusIII** [comment]
Releases end up in misc if there is no way to properly match them to categories, rename them from hashed name etc.

**Comment by DrakeJones** [comment]
@egyptianbman, can I get a copy of your batch recat script?  I get about 10K recats (5% of my total) before the process slows to a crawl and times out.  Thanks.

**Comment by lamars79** [comment]
@egyptianbman would it be possible to get a copy of your script as well?  I am running into the OOM error when I run recategorize.php as well.

**Comment by egyptianbman** [comment]
I'll push up a PR with my changes to recategorize once #1154 is merged. Since I'm using this checkout for my indexer, switching to different branches causes issues with missing code during execution. :)
