### ISSUE TITLE
Undefined index: api_token

### ISSUE THREAD

**Issue by lamars79** [NNTmux/newznab-tmux#1151]
**Describe the bug**
When running postProcess_TV the following error occurs:
  
Undefined index: api_token
  at vendor/php-tmdb/api/lib/Tmdb/Client.php:175
    171|                 'null'
    172|             ]
    173|         );
    174|
  > 175|         if (is_string($options['api_token'])) {
    176|             $options['api_token'] = new ApiToken($options['api_token']);
    177|         }
    178|
    179|         $this->options = $this->postResolve(
      +2 vendor frames
  3   Blacklight/processing/tv/TMDB.php:53
      Tmdb\Client::__construct()
  4   misc/testing/Tests/test_tmdb_API.php:7
      Blacklight\processing\tv\TMDB::__construct()

**To Reproduce**
1. Running Tmux Console
2. goto 'post'
3. In second pane 'postProcess_tv'
4. the error occurs.  This can also be replicated by running test_tmdb_API.php in misc/testing/Tests

**Expected behavior**

**Installation (please complete the following information):**
 - OS: Ubuntu 16.04
 - PHP version PHP 7.4
 - NNTmux version running latest version.  First step prior to submitting this report was to update nntmux install.

**Additional context**
I verified that my .env file has the correct TMDB api key configured.

**Comment by DariusIII** [comment]
I am aware of the issue and i'm working on the fix. Thanks for the report.

**Comment by lamars79** [comment]
No problem.  Thanks for all the work you do.
