### ISSUE TITLE
Docker Outdated

### ISSUE THREAD

**Issue by devonzara** [NNTmux/newznab-tmux#1152]
I was looking to spin this up and see what it was all about... looks like the Docker files are outdated though. For whatever reason, an old Composer file verification hash is hardcoded... also, if you edit it to get past that, it still appears to fail due to installing PHP 7.3.26 while some dependencies require ^7.4.
```
  Problem 1
    - Root composer.json requires php >=7.4.0 but your php version (7.3.26) does not satisfy that requirement.
  Problem 2
    - dborsatto/php-giantbomb is locked to version v2.1.0 and an update of this package was not requested.
    - dborsatto/php-giantbomb v2.1.0 requires php ^7.4 -> your php version (7.3.26) does not satisfy that requirement.
```
Upgraded to PHP 7.4 and still was unable to get things running due to permission errors or something. The ui container was stuck in a restart loop and kept throwing an error: `The stream or file "/var/www/NNTmux/storage/logs/laravel-2021-01-18.log" could not be opened in append mode: chmod(): No such file or directory`

Lastly, I'm not sure if there's a reason for it, but using Ubuntu 18.04 seems quite excessive when, in most cases, you can use a lightweight alpine build and install what's needed.

I spent a good bit of time trying to figure it out and get everything working, but I'm afraid my linux and apache knowledge is insufficient. I may try again when I have more time to spare.

**Comment by egyptianbman** [comment]
I run nntmux in docker and ran into similar issues when I first set it up. I ended up writing my own Dockerfile that's built on arch instead of Ubuntu and utilizes nginx instead of apache. @DariusIII let me know if you'd like me to push up a PR with the update.

**Comment by devonzara** [comment]
@egyptianbman, I'd appreciate a share even if it's not merged...

I spent some time this afternoon making a Dockerfile with php:7.4-fpm-alpine, but didn't have time to complete it.

**Comment by wimjan123** [comment]
I have the same problem, lot of errors when trying docker-compose probably due to being outdated..

**Comment by DariusIII** [comment]
I am not using docker at all and i have no intention of maintaining it. If anyone is interested, feel free to open a PR and i will check and merge it. @egyptianbman Feel free to create a PR with your working solution.
