### ISSUE TITLE
Issue with populate_rt_indexes.php

### ISSUE THREAD

**Issue by Adenn** [NNTmux/newznab-tmux#1156]
When trying to run the "php populate_rt_indexes.php releases_rt" command I get the following output / error:

Truncating index releases_rt finished.
[Starting to populate sphinx RT index releases_rt with 126 releases.]

   Foolz\SphinxQL\Exception\ConnectionException

  SQLSTATE[HY000] [2002] Connection refused

  at /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php:59
    55|
    56|         try {
    57|             $con = new PDO($dsn);
    58|         } catch (PDOException $exception) {
  > 59|             throw new ConnectionException($exception->getMessage(), $exception->getCode(), $exception);
    60|         }
    61|
    62|         $this->connection = $con;
    63|         $this->connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

      +9 vendor frames
  10  /var/www/NNTmux/Blacklight/SphinxSearch.php:73
      Foolz\SphinxQL\SphinxQL::execute()

  11  populate_rt_indexes.php:85
      Blacklight\SphinxSearch::insertRelease()

I can run the "php populate_rt_indexes.php predb_rt" command and it seems to run correct.  I don't get any errors and it says it is finished.  It does however say that the "RT index predb_rt with 0 releases."  I don't know if that is normal or not.

Running on Ubuntu Server 20.10.

**Comment by egyptianbman** [comment]
> SQLSTATE[HY000] [2002] Connection refused

This indicates your credentials aren't correct. Check your configuration.

**Comment by Adenn** [comment]
> > SQLSTATE[HY000] [2002] Connection refused
> 
> This indicates your credentials aren't correct. Check your configuration.

Is this in the .env file or another location that I missed in the instructions?

**Comment by egyptianbman** [comment]
Yes. Make sure you have the correct sphinx configuration https://github.com/NNTmux/newznab-tmux/blob/543cc0512fcb6c367d122749f52327b40a560ea3/.env.example#L10-L11

and mysql configuration https://github.com/NNTmux/newznab-tmux/blob/543cc0512fcb6c367d122749f52327b40a560ea3/.env.example#L1-L8

**Comment by Adenn** [comment]
I have double checked those settings, they look correct.

The "php create_se_tables.php 0 9312" command and the "php populate_rt_indexes.php predb_rt" both appear to connect and run properly.

When I look at my nntmux database, it has both the tables that are created in the create_se_tables script, so that much appears to be working.

**Comment by egyptianbman** [comment]
How are you running manticore?

**Comment by Adenn** [comment]
I have it running, as instructed in the Ubuntu install guide, with the exception of this line "sudo systemctl enable manticore.service"  When I run this command, I get the following message: "Failed to enable unit: Unit /run/systemd/generator.early/manticore.service is transient or generated."  Which I haven't been able to resolve yet.

This is running on the same server as NNTMux install.

I also tried to use Elasticsearch, however, the following file seems to be missing: "php create_es_tables.php"  even when looking through the repository, it seems to be missing.

**Comment by DariusIII** [comment]
> I have it running, as instructed in the Ubuntu install guide, with the exception of this line "sudo systemctl enable manticore.service" When I run this command, I get the following message: "Failed to enable unit: Unit /run/systemd/generator.early/manticore.service is transient or generated." Which I haven't been able to resolve yet.
> 
> This is running on the same server as NNTMux install.
> 
> I also tried to use Elasticsearch, however, the following file seems to be missing: "php create_es_tables.php" even when looking through the repository, it seems to be missing.

You mean this file?

https://github.com/NNTmux/newznab-tmux/blob/master/misc/elasticsearch/create_es_indexes.php

**Comment by egyptianbman** [comment]
Regarding manticore, it seems something may have gone wrong with the installation, that's why it you weren't able to run the command to enable it. Personally, I have both installed and choose to use elasticsearch as it seems to perform better anyway.

**Comment by Adenn** [comment]
> You mean this file?
> 
> https://github.com/NNTmux/newznab-tmux/blob/master/misc/elasticsearch/create_es_indexes.php

No, in looking at the Ubuntu instructions, you are supposed to run a "php create_es_tables.php" command.  There is no way, that I can see, to create the actual DB tables for Elasticsearch.

This is the section from the document:

`Follow install instruction from here: https://tecadmin.net/setup-elasticsearch-on-ubuntu/

cd /var/www/NNTmux/misc/elasticsearch/

php create_es_tables.php  #<<< this file right here

php populate_es_indexes.php releases

php populate_es_indexes.php predb

enable elasticsearch in your .env by setting ELASTICSEARCH_ENABLED=true`

**Comment by Adenn** [comment]
> Regarding manticore, it seems something may have gone wrong with the installation, that's why it you weren't able to run the command to enable it. Personally, I have both installed and choose to use elasticsearch as it seems to perform better anyway.

Elasticsearch is reported to work better, so I wanted to use that, but can't the tables created.

I did start over with my install, completely, os and everything, on 16.04 and while trying to install manticore I received some errors.  I probably had the same problem on 20.10, which over-all the entire process is pretty different, but didn't notice the errors.  I've been fighting this for 4 days now, so I am going to take a break and work on a different project and then go back and try and fix things.

It would be nice if the missing "create_es_tables.php" file for elasticsearch could be found so I could try that instead.

Thank you everyone for your assistance.

**Comment by DariusIII** [comment]
> > You mean this file?
> > https://github.com/NNTmux/newznab-tmux/blob/master/misc/elasticsearch/create_es_indexes.php
> 
> No, in looking at the Ubuntu instructions, you are supposed to run a "php create_es_tables.php" command. There is no way, that I can see, to create the actual DB tables for Elasticsearch.
> 
> This is the section from the document:
> 
> ``Follow install instruction from here: https://tecadmin.net/setup-elasticsearch-on-ubuntu/
> 
> cd /var/www/NNTmux/misc/elasticsearch/
> 
> **php create_es_tables.php** <<< this line
> 
> php populate_es_indexes.php releases
> 
> php populate_es_indexes.php predb
> 
> enable elasticsearch in your .env by setting ELASTICSEARCH_ENABLED=true``

That ES table creation is an error in guide .

**Comment by Adenn** [comment]
thank you, that is helpful to know.
