### ISSUE TITLE
My unrar tmpfs just started filling up.

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1157]
My unrar tmpfs just started filling up after the last update - at least I didn't see it if it was happening before that.  Upped tmpfs to 1G and it's still not enough.

**Comment by Fossil01** [comment]
Yes I had the same, the cleanup does not work often. I added some lines to config/laravel-directory-cleanup.php:

```php
        Settings::settingValue('..tmpunrarpath') => [
             'deleteAllOlderThanMinutes' => 60,
         ],
```

**Comment by DrakeJones** [comment]
Thanks.  I'll try that.  I saw that it was an issue in the past [https://github.com/NNTmux/newznab-tmux/issues/806](url) but it was closed.

**Comment by DrakeJones** [comment]
It looks like the cleanup timer is already in config/laravel-directory-cleanup.php.

**Comment by Fossil01** [comment]
That's not the same path as in the .env file mostly. Mines on a RAM disk.

**Comment by DrakeJones** [comment]
I haven't changed anything permissions-wise.  I just disabled "Check For Passworded Releases".  We'll see if resources/tmp/unrar still fills up.
