### ISSUE TITLE
Syntax Error When Loading Site

### ISSUE THREAD

**Issue by lamars79** [NNTmux/newznab-tmux#1158]
When I try to load my nntmux webpage I get the following error:

/media/bigdisk/www/nntmux/vendor/laravel/framework/src/Illuminate/Testing/Concerns/TestDatabases.php
 

>     /**
>      * Switch to the given database.
>      *
>      * @param  string $database
>      * @return void
>      */
>     protected function switchToDatabase($database)
>     {
>         DB::purge();
>  
>         $default = config('database.default');
>  
>         $url = config("database.connections.{$default}.url");
>  
>         if ($url) {
>             config()->set(
>                 "database.connections.{$default}.url",
>                 preg_replace('/^(.*)(\/[\w-]*)(\??.*)$/', "$1/{$database}$3", $url),
>             );
>         } else {
>             config()->set(
>                 "database.connections.{$default}.database",
>                 $database,
>             );
>         }
>     }
>  
>     /**
>      * Returns the test database name.
>      *
>      * @return string
>      */
>     protected function testDatabase($database)
>     {
>         $token = ParallelTesting::token();
>  
>         return "{$database}_test_{$token}";
>     }
> }

**Arguments
"syntax error, unexpected ')'"**

**Expected behavior**
I am expecting that the default landing page will load.

**Installation (please complete the following information):**
 - OS: Ubuntu 18.
 - PHP version: 7.4.13
 - NNTmux version or commit: 3110d82

**Comment by DariusIII** [comment]
I don't know what you are doing, but testing database is something not used in production.

**Comment by lamars79** [comment]
That is very weird then.  I will dig around and see what I could have changed to cause this.  Thx.
