### ISSUE TITLE
 500 Server Error After First Install

### ISSUE THREAD

**Issue by goran251** [NNTmux/newznab-tmux#1163]
After first install I go to http://localhost/login and after I put in my details I get the error " 500 Server Error " on a blank screen.
Thanks in advance to anyone can help.

**Comment by DariusIII** [comment]
You should enable debugging and change your environment in .env from production to local. Then you will see the actual error.

**Comment by goran251** [comment]
Hey, Thanks for the suggestion!
This is what it shows now after enabling: https://flareapp.io/share/47qXMDBP#F53.

**Comment by DariusIII** [comment]
You need to switch away from file cache.

**Comment by goran251** [comment]
How do I do that?

**Comment by DariusIII** [comment]
Install redis server and change cache driver in your env file.

**Comment by goran251** [comment]
I have done that but now it is giving me this error: You have a missing class import. Try importing this class: Illuminate\Support\Facades\Redis.

In the code it also says this: 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'

                        : 'Please make sure the PHP Redis extension is installed and enabled.'

**Comment by goran251** [comment]
Thanks for your help! I was able to fix it by changing the redis clinet from phpredis to predis.
