### ISSUE TITLE
Check installation

### ISSUE THREAD

**Issue by ictinc** [NNTmux/newznab-tmux#1167]
Hi there,
I think I just managed to install newznab-tmux. After running into several issues (mainly some dumb mistakes from my side) I can now login to the admin account.
I'm not sure what the expected behaviour is after this. I can see all the menu items including my username in the top right menu. However when I click on any of the menu items nothing happens.
The categories are empty, which is to be expected on a new site.
For example when I click on the arrow next to my username I expect something like a submenu with a link to profile or settings. Instead if I click there there's only a # added to the website URL.

If I go to http://www.mysite.com/admin/tmux-edit there's a whole list of menu items on the left side but non of them go anywhere.
For example "edit site" does change the url in the address bar to http://www.sitename.com/admin/tmux-edit#submenu1 but it stays at the tmux-edit form.

I'm not sure which behaviour is normal after installation. It feels like this is not what is supposed to happen, which I'd like to know.
I'm also not sure where to check for any errors except for the regular apache logs path or syslog.

Cheers

**Comment by DariusIII** [comment]
To be sure what is going on, enable debugging in your .env file. While you are there, enable telescope too. That will give you and me much more info about what is the issue.

**Comment by Fossil01** [comment]
`storage/logs` in root dir of NNTmux.

**Comment by ictinc** [comment]
After checking there I see most errors are related to the following:
NNTmux.ERROR: Call to undefined function App\Models\config() (View:/var/www/NNTmux/resources/views/errors/403.blade.php)

In this one it refers to 403.blade.php but there's similar errors all referring to different php files.
