### ISSUE TITLE
Since my last, update basic  Search function is dead.  Advanced Search works fine.

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1168]
**Describe the bug**
Since my last, update basic  Basic Search function is dead.  Advanced Search works fine. (I also upgraded Composer to V2).

**To Reproduce**
Self explanatory.

**Expected behavior**
Self explanatory.

**Installation (please complete the following information):**
 - OS:  Ubuntu
 - PHP version PHP 7.4.7
 - Composer version 2.0.14 2021-05-21 17:03:37
 - NNTmux version or commit [e.g. 1.0]

<<Edit-Addendum>> Basic Search is working with Google Chrome, but not Firefox.  (It's obviously the giant brains at Mozilla protecting us from ourselves, but any suggestions would be welcome).

**Comment by DariusIII** [comment]
Basic Search is broken since i have upgraded Bootstrap to version 5. I am working on new theme, which should fix this, and many other broken stuff in current theme (and probably will come with its own set of broken stuff :) )

**Comment by DrakeJones** [comment]
lol.  Looking forward to the new stuff.
