### ISSUE TITLE
ERROR: Trying to access array offset on value of type int...

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1170]
Is this indicative of a data/db corruption or something else?  Will it clear up on its own?  Seems to have started while backfilling a.b.teevee. Been happening for while. 

[2021-06-25 11:55:29] NNTmux.ERROR: Trying to access array offset on value of type int {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type int at /var/www/NNTmux/Blacklight/processing/Videos.php:172)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/processing/Videos.php(172): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/processing/tv/TVDB.php(108): Blacklight\\processing\\Videos->getByTitle()
#2 /var/www/NNTmux/Blacklight/processing/PostProcess.php(243): Blacklight\\processing\\tv\\TVDB->processSite()
#3 /var/www/NNTmux/misc/update/postprocess.php(123): Blacklight\\processing\\PostProcess->processTv()
#4 {main}
"}

**Comment by DariusIII** [comment]
Probably the returned value isn't one of the expected ones.

**Comment by DrakeJones** [comment]
I can live with that.  Thnks.
