### ISSUE TITLE
Can't edit or delete nzb

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1174]
**Describe the bug**
Can't delete or edit nzb. Nothing happens when pushing button

**To Reproduce**
Choose menu Other and mark a nzb file. Push edit or delete
nothing happen

**Expected behavior**
function on buttons

**Screenshots**

**Installation (please complete the following information):**
 - OS: ubuntu
 - PHP version 7.4
 - NNTmux version or commit [e.g. 1.0]

**Additional context**

**Comment by DariusIII** [comment]
This is a known issue that will be fixed with new theme i am working on.

**Comment by HengeDK** [comment]
excellent

**Comment by ShivamB25** [comment]
> This is a known issue that will be fixed with new theme i am working on.

any updates on this?

**Comment by DariusIII** [comment]
> > This is a known issue that will be fixed with new theme i am working on.
> 
> any updates on this?

I have lost a drive where i was working on the theme and i had no backup. But i plan to work on it again very, very soon.
