### ISSUE TITLE
Can't send invite

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1175]
**Describe the bug**
can't send invite from profile page

**To Reproduce**
1. Go to profile page
2. Click on 'Send Invite
3. Nothing happens
4. 

**Expected behavior**
Send invite page will show

**Screenshots**

**Installation (please complete the following information):**
 - OS: ubuntu
 - PHP version 7.4
 - NNTmux version or commit [e.g. 1.0]

**Additional context**

**Comment by DariusIII** [comment]
Is site set to invite only? Have you enabled and adjusted everything related to sending emails? 

https://github.com/NNTmux/newznab-tmux/wiki/Email-queue

**Comment by HengeDK** [comment]
yes
all other e-mails are working
upgrade account, welcome and so
the link for invite is domain/#
so there much be an bug somewhere
what is the route for invite. I can't find it in web.php ?

**Comment by DariusIII** [comment]
That is because invites are handled by this package: https://github.com/junaidnasir/larainvite

**Comment by HengeDK** [comment]
ok
would you check you mail
when you have time

**Comment by HengeDK** [comment]
Can you check where the problem is
I can’t find it
Sins where is no error. Just dead link
