### ISSUE TITLE
sabnzbd queue not working

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1176]
**Describe the bug**
integration with sabnzbd api is not working

**To Reproduce**
1. Go to profile and add your setting for sabnzbd
2. Click on profile and my queue
3. on the queue page see the status
4. Could not contact your queue. "Refresh"

**Expected behavior**
listing queue from sabnzbd

**Screenshots**

**Installation (please complete the following information):**
 - OS: [e.g. ubuntu
 - PHP version 7.4
 - NNTmux version or commit [e.g. 1.0]

**Additional context**
excatly same setting and api key is working on same host in newznab
sometime you can see in the log on sabnzbd, incorrect api key
but the key is thecorrect one

**Comment by DariusIII** [comment]
I will have a look at it. This is a long time bug i did not have time to fix.

**Comment by HengeDK** [comment]
any news on this bug ?

**Comment by Wally73** [comment]
just check it in sabnzb itself much easier :p

**Comment by HengeDK** [comment]
don't think you ever used that function ;-)

**Comment by HengeDK** [comment]
DariusIII
please check your protonmail

**Comment by DariusIII** [comment]
SabNzbd and NZBGet queues have been removed from NNTmux, so this issue is not relevant anymore.
