### ISSUE TITLE
Forum with subforum

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1177]
**Is your feature request related to a problem? Please describe.**
No. but the forum included now. dosen't support subforums

**Describe the solution you'd like**
A forum with more functions like support for moderation and so

**Describe alternatives you've considered**
.

**Additional context**

**Comment by DariusIII** [comment]
This is not going to be implemented. For features like this, feel free to fork NNTmux and work from there. Forums in NNTmux are basic on purpose.
