### ISSUE TITLE
Rename script for Other>Misc with obfuscated or nonsense names - sometimes have proper name in rar file.  

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1182]
I have to manually go through old backfilled releases that wind up as Other>Misc.  NNTmux shows rar content for many of those misnamed/miscategorized releases.  That's a nice feature.  Can it be leveraged to rename/categorize releases? 

I'd like to be able to manually run a release rename on Other>Misc category that will pull and rename using files names _inside_ the rars that would only use file names with meaningful extensions; i.e., .mkv, .flac, nfo, etc.   

My alternative solutions is one-by-one manual rename.

Is there already a feature that does that in NNTmux?  I don't think recategorize.php or 

Thanks.

**Comment by DariusIII** [comment]
I am going to push a commit to PPA so it renames files on addition to indexer.

**Comment by DrakeJones** [comment]
Thank you very much!
