### ISSUE TITLE
Uninitialized string offset: 1616 {"exception":"[object] (ErrorException(code: 0): Uninitialized string offset: 1616 at /var/www/NNTmux/app/Extensions/util/PhpYenc.php:121)

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1184]
I have a monkey on my back.  I'm backfilling a.b.movies and I'm getting the error below.  Will it die/iterate away? Is there a workaround?  Should I (my guess) just ignore it? 

NNTmux.ERROR: Uninitialized string offset: 1616 {"exception":"[object] (ErrorException(code: 0): Uninitialized string offset: 1616 at /var/www/NNTmux/app/Extensions/util/PhpYenc.php:121)
[stacktrace]
#0 /var/www/NNTmux/app/Extensions/util/PhpYenc.php(121): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/NNTP.php(1161): App\\Extensions\\util\\PhpYenc::decodeIgnore()
#2 /var/www/NNTmux/Blacklight/NNTP.php(602): Blacklight\\NNTP->_getMessage()
#3 /var/www/NNTmux/Blacklight/NZBContents.php(111): Blacklight\\NNTP->getMessages()
#4 /var/www/NNTmux/Blacklight/Nfo.php(332): Blacklight\\NZBContents->getNfoFromNZB()
#5 /var/www/NNTmux/Blacklight/processing/PostProcess.php(217): Blacklight\\Nfo->processNfoFiles()
#6 /var/www/NNTmux/misc/update/postprocess.php(109): Blacklight\\processing\\PostProcess->processNfos()
#7 {main}
"}

**Comment by DariusIII** [comment]
I need more info, but my guess is that issue will go away on its own.

**Comment by DrakeJones** [comment]
[https://imgur.com/a/ZFTEGmD](url)

A screen capture of the error.

**Comment by DariusIII** [comment]
This has to do with type of posts you're indexing. Not much i can do about it.

**Comment by DrakeJones** [comment]
Then I'll close the issue.  Thanks for taking the time to look at it.
