### ISSUE TITLE
predb not finding any matches 

### ISSUE THREAD

**Issue by jjaomni** [NNTmux/newznab-tmux#1191]
i can't get the predb data to match up with any releases. and i'm not seeing any errors about it. 

<img width="453" alt="Clipboarder 2021 10 19" src="https://user-images.githubusercontent.com/13040380/137952625-7138f78e-61a7-4d48-b3cb-a8b3d00a10c2.png">
.
php 7.4 
ubuntu 20.04
on master

**Comment by DariusIII** [comment]
Predb matching works on filenames, and most of the names are obfuscated even if you see them properly.
