### ISSUE TITLE
Too many groups issue

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#1195]
So I finally figured out my issue.  I tried to add 500 groups and it does not pull headers from that many.  In tmux, the binaries box says starting, and then after a few minutes it just clears and then the timer starts, and it repeats.
When I dropped the groups to 200, it works.  Is there a setting either in tmux or in the code that has a hard limit on number of groups?  This is easy to replicate, just add 500 groups and let it run.  I even lowered the # of headers to 5k max and it still did not run.

Nothing in the laravel logs as to why that happens.  Could it be in another log?

**Comment by Fossil01** [comment]
How many groups are you trying to do at once? The number of threads should be something like 5 or 10.

**Comment by DariusIII** [comment]
Number of groups is not an issue. Maybe your provider does not have them all? Also as @Fossil01 said, how many threads are you using? This also means that your database should be able to cope with the amount of data you are sending.

**Comment by blimeybloke** [comment]
I am trying about 2000 in total.  I  have played with threads up to 5, never higher than that.  There may be a few my provider does not have but it does not try.

**Comment by DariusIII** [comment]
You need to check if maybe your database is being bogged down. Check running processes inside your database to get a clue.

**Comment by blimeybloke** [comment]
I actually decided to just purge things a bit.   I have about 520 and it seems to be running.  Many of the other groups were not updated in a VERY long time so quite pointless atm.
