### ISSUE TITLE
API v2 or V1 give error 500

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#1196]
Last question, promise. :)

I have gotten some release data, however, the api gives error 500.

I do get the nzb but the page itself shows error 500 with the apache2 error log:

[Wed Nov 17 06:43:51.440459 2021] [proxy_fcgi:error] [pid 29544] (22)Invalid argument: [client MY_IP:57254] AH01075: Error dispatching request to :
[Wed Nov 17 06:43:54.106439 2021] [proxy_fcgi:error] [pid 29545] [client MY_IP:57259] malformed header from script 'index.php': Bad header:
[Wed Nov 17 06:43:54.106506 2021] [proxy_fcgi:error] [pid 29545] [client MY_IP:57259] AH01070: Error parsing script headers
[Wed Nov 17 06:43:54.106513 2021] [proxy_fcgi:error] [pid 29545] (22)Invalid argument: [client MY_IP:57259] AH01075: Error dispatching request to : 

For caching, I am set to file.  I have tried to just change that to redis but then every page gives error 500.
I can click download nzb on the actual release page with no errors.  It is just the api that gives the error 500 when attempting to grab the nzb.
Hoping this is a permission issue or something silly

**Comment by Fossil01** [comment]
Don't use file, use Redis. I would also advise to use nginx with php-fpm instead of Apache2 and make sure to use PHP 7.4.

Make sure you have all the needed php extensions installed too.

**Comment by blimeybloke** [comment]
I will look to change over to nginx.  How do I switch to redis?  Is that the last step in the install guide titled "Redis server stats"
Once I do that do I just change from file to redis in the .env file?
Thank you

**Comment by blimeybloke** [comment]
Ok, I installed redis and reconfigured .env to use redis instead of file.  Same issue. :( 
I am also on php 7.4 too.

**Comment by blimeybloke** [comment]
Well I need more coffee apparently.   I needed to chown -R the main directory.  All working well now.
Thank you for the assist
