### ISSUE TITLE
required for each reboot?

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#1197]
If I reboot my server, I seem to looks Sphinx as an engine in mysql.  So each reboot, I need to do the following:
Empty mysql.plugin table (phpmyadmin)
then log into mysql on shell and run this
INSTALL SONAME 'ha_sphinx';
quit;
After execute these
cd /var/www/NNTmux/misc/manticoresearch/
php create_se_tables.php 0 9312
php populate_rt_indexes.php releases_rt
php populate_rt_indexes.php predb_rt

Is this normal or am I missing something (the 2nd part is most likely the issue lol)

**Comment by DariusIII** [comment]
If you need to install the sphinx engine after every reboot, there is an issue with your database install.

**Comment by blimeybloke** [comment]
I don't see how I screwed that part up.  With all the issues, I have completed 4 fresh builds, but this particular issue was with each build.

**Comment by blimeybloke** [comment]
More info:
indexer --all
Manticore 3.2.2 afd60463@191226 release
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2019, Manticore Software LTD (http://manticoresearch.com)

using config file '/etc/manticoresearch/manticore.conf'...
FATAL: no indexes found in config file '/etc/manticoresearch/manticore.conf'

This was after a reboot

**Comment by blimeybloke** [comment]
ahhhh here is the issue:
[Wed Nov 17 19:39:03.619 2021] [1538] FATAL: failed to parse config file '/etc/sphinxsearch/sphinx.conf'

This is when I do "service sphinx status" 

strange that config is not there, am I supposed to do a cp?

**Comment by blimeybloke** [comment]
lol, progress:
I did: cp /var/www/NNTmux/docker/sphinx.conf /etc/sphinxsearch/sphinx.conf   
now when I try to start I get:

Nov 17 19:57:16 rikers3 systemd[1]: sphinxsearch.service: Can't open PID file /var/run/sphinxsearch/searchd.pid (yet?) after start: No such file or directory
Nov 17 19:57:16 rikers3 systemd[1]: sphinxsearch.service: Failed with result 'protocol'.
Nov 17 19:57:16 rikers3 systemd[1]: Failed to start SphinxSearch Search Engine.

**Comment by blimeybloke** [comment]
I am running manticore.. from the guide... do I need sphinx and manticore?

**Comment by blimeybloke** [comment]
I finally figured this out.  I needed to add 2 lines (1 was mandatory) and now the plugin loads at boot:
[mysqld]
plugin_maturity=gamma
plugin_load = ha_sphinx

**Comment by DariusIII** [comment]
> I am running manticore.. from the guide... do I need sphinx and manticore?

Manticore is a fork of Sphinx so you do not need both. Manticore is preferred as Sphinx, in its free version, is older and not maintained anymore.

**Comment by DariusIII** [comment]
> I finally figured this out. I needed to add 2 lines (1 was mandatory) and now the plugin loads at boot: [mysqld] plugin_maturity=gamma plugin_load = ha_sphinx
> 
> Closing the issue in a few hours unless you beat me to it or had questions for me.

I wasn't aware you ran this through docker. While there is support for docker in the repo, i am not doing docker support as i never tested it.

**Comment by blimeybloke** [comment]
I am not running this in docker.  I just needed to add that plugin info to mysql.conf

**Comment by DariusIII** [comment]
You shouldn't need to do that if plugin is installed once. In all these years i never needed to reinstall sphinx plugin once i have installed it. Are you using MariaDB, Percona or MySQL?

**Comment by blimeybloke** [comment]
Server version: 10.5.13-MariaDB-1:10.5.13+maria~bionic

**Comment by DariusIII** [comment]
I am closing this issue as it is not related to NNTmux but database itself.
