### ISSUE TITLE
Path to Lame won't save

### ISSUE THREAD

**Issue by buurman** [NNTmux/newznab-tmux#120]
The path to lame won't save, probably because the lamepath entry is missing in de database after a fresh install.

**Comment by DariusIII** [comment]
Will fix that ASAP

**Comment by buurman** [comment]
There are more missing parameters, at least header retention, minimum complete percentage and update telease threads are also missing.

**Comment by DariusIII** [comment]
Header retention is unused completely in code and i will remove it, as it is an remnant of nn+ raw search feature that never worked, update release threads is misnamed and completion percent is there.

**Comment by buurman** [comment]
Thanks, I noticed they were blank and I couldn't changed them.. thanks for answering

**Comment by buurman** [comment]
Well they maybe there but I can't change them from the webinterface
Minimum Completion Percent to Make a Release: Is blank, in the DB it's 95
Max Messages Per Run: Blank in the webinterface,, can;t find it in the DB

**Comment by DariusIII** [comment]
Max messages per run <-- another setting not used anywhere, another leftover from nn+
As for Minimum Completion Percent to Make a Release it is both in DB and edit site and that should work.

**Comment by buurman** [comment]
Thanks, min completion percentage can't be filled out/saved on 'edit site', the setting is however in the database so I should be ok.

**Comment by DariusIII** [comment]
When i was testing it worked, but anything can happen. Thanks for reporting the issues.
About those Max Messages Per Run, you still have another setting with same name that works (Max Messages).

**Comment by buurman** [comment]
I'll keep an eye on it, thanks for helping.
