### ISSUE TITLE
ERROR: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by jjaomni** [NNTmux/newznab-tmux#1201]
when I import files from the cmd line i get to this point and it wont import anything else in the folder.. 

[2021-12-21 18:19:22] NNTmux.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/NNTmux/Blacklight/ReleaseCleaning.php:165)

[stacktrace]

#0 /var/www/NNTmux/Blacklight/ReleaseCleaning.php(165): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()

#1 /var/www/NNTmux/Blacklight/NZBImport.php(390): Blacklight\\ReleaseCleaning->releaseCleaner()

#2 /var/www/NNTmux/Blacklight/NZBImport.php(360): Blacklight\\NZBImport->insertNZB()

#3 /var/www/NNTmux/Blacklight/NZBImport.php(183): Blacklight\\NZBImport->scanNZBFile()

#4 /var/www/NNTmux/misc/testing/nzb-import.php(79): Blacklight\\NZBImport->beginImport()

#5 {main}

"}

**Comment by DariusIII** [comment]
Need to check the script, as switch to PHP8 uncovered some serious errors in code.

**Comment by DariusIII** [comment]
I had a look at the code and i think that title of the release from NZB is empty. Either the NZB itself is erroneous or you have selected an option to pull the name from NZB and not from filename (or vice versa). Try to change one of those options and check the result. I cannot find any error in code.

**Comment by jjaomni** [comment]
i finally got past it by not doing the import from the cli. 

but i got another error now..

**Comment by jjaomni** [comment]
hang on let me get back to you about that. i did the by filename option for importing and some of the errors went away..

**Comment by jjaomni** [comment]
[2021-12-27 14:30:35] NNTmux.ERROR: Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php:1113)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1113): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1044): Blacklight\\processing\\post\\ProcessAdditional->_processCompressedData()
#2 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(750): Blacklight\\processing\\post\\ProcessAdditional->_processNZBCompressedFiles()
#3 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(568): Blacklight\\processing\\post\\ProcessAdditional->_processReleases()
#4 /var/www/NNTmux/Blacklight/processing/PostProcess.php(281): Blacklight\\processing\\post\\ProcessAdditional->start()
#5 /var/www/NNTmux/misc/update/postprocess.php(87): Blacklight\\processing\\PostProcess->processAdditional()
#6 {main}
"} 
[2021-12-27 14:30:39] NNTmux.ERROR: Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php:1113)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1113): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1044): Blacklight\\processing\\post\\ProcessAdditional->_processCompressedData()
#2 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(750): Blacklight\\processing\\post\\ProcessAdditional->_processNZBCompressedFiles()
#3 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(568): Blacklight\\processing\\post\\ProcessAdditional->_processReleases()
#4 /var/www/NNTmux/Blacklight/processing/PostProcess.php(281): Blacklight\\processing\\post\\ProcessAdditional->start()
#5 /var/www/NNTmux/misc/update/postprocess.php(87): Blacklight\\processing\\PostProcess->processAdditional()
#6 {main}
"} 
[2021-12-27 14:31:32] NNTmux.ERROR: Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php:1113)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1113): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1044): Blacklight\\processing\\post\\ProcessAdditional->_processCompressedData()
#2 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(750): Blacklight\\processing\\post\\ProcessAdditional->_processNZBCompressedFiles()
#3 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(568): Blacklight\\processing\\post\\ProcessAdditional->_processReleases()
#4 /var/www/NNTmux/Blacklight/processing/PostProcess.php(281): Blacklight\\processing\\post\\ProcessAdditional->start()
#5 /var/www/NNTmux/misc/update/postprocess.php(87): Blacklight\\processing\\PostProcess->processAdditional()
#6 {main}
"} 




getting this over and over again.. about a 5 meg log file

**Comment by DariusIII** [comment]
NZB does not have information we are looking for (rarfilename is missing the info):

https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/post/ProcessAdditional.php#L1113

`if (preg_match(NameFixer::PREDB_REGEX, $rarFileName[0], $hit)) {`

**Comment by jjaomni** [comment]
How can i get the list of files that is effected by this?? i have yet to be able to track that down in the debug stuff. i hope it not part of those 200,000 that seem to be stuck.. 


<img width="491" alt="Clipboarder 2021 12 27" src="https://user-images.githubusercontent.com/13040380/147515303-df11c23b-5a46-4a0c-b050-1bb188100d0c.png">

**Comment by DariusIII** [comment]
No such list exists, unless you write your own query and code to check it.
