### ISSUE TITLE
install php broken

### ISSUE THREAD

**Issue by nrk666** [NNTmux/newznab-tmux#121]
Hey Dar, thought I'd give your fork a try. 

OS: Ubuntu 16.04, fresh install, all updates applied. 
Branch: git branch -v
- (HEAD detached at v0.6.1.1) 7b2c450 Merge branch 'dev' into 0.x
  0.x  7b2c450 Merge branch 'dev' into 0.x

The http://server/install script seems broken when using a fresh 16.04 install following the guide on the front page. I deviated a little to use MariaDB 10.1 and nginx. When you input the usenet server login/pw/port using the install steps and click the button to go to the next step, a little red "-1" appears at the bottom and the script doesn't advance to the next step. I manually skipped to the next step to setup admin user, but when I got done, there was no server listed in config.php. I manually editted config.php but I can't fetch any binaries if I use encryption. If I switch to not use encryption, it works, but if you use encryption, all you get is a bunch of "PHP Notice:  Only variables should be assigned by reference in /usr/share/php/PEAR.php on line 601" and finally 
"Error: Unable to connect to usenet" when running update_binaries.php. No more specific php_errors.log was generated.

**Comment by DariusIII** [comment]
-1 means failed USP test. SSL needs to be configured properly to work (certs and stuff), but honestly i could never make it work on NNTmux (will try and fix). The PEAR line 601 notices are actualy not NNTmux but PEAR related problems (fixed by removing & from lines 601 and 603 in PEAR.php

**Comment by nrk666** [comment]
Is this part different than nZEDb? I've always just put in my USP with port 563 + SSL on every other indexer software (newznab/nZEDb) and it just worked on a fresh install of 16.04. I've never actually configured a certificate in any instance. 

Thanks for the tip on PEAR.php.

**Comment by DariusIII** [comment]
You don't need to configure certificates, just set allow self-signed certificates to 1 in config.php.
define('NN_SSL_ALLOW_SELF_SIGNED', '1');

**Comment by nrk666** [comment]
Yeah, it's set that way by default I think. Just wondering why it works on newznab and nZEDb, but not here.

**Comment by DariusIII** [comment]
I wonder too, as code is same for NNTP.

**Comment by nrk666** [comment]
Interesting, which USP? I can't seem to get it to work with Frugal. But, all my USP's are all pointed back at Highwinds now and my main nZEDb indexer uses newshosting, which is also the same highwinds backend  (69.16.179.29 vs 69.16.179.48).

**Comment by DariusIII** [comment]
Testing VM's use usenet.farm while main one uses newsgroup.ninja

**Comment by nrk666** [comment]
newsninja is Highwinds, so same company/backend as frugal/newshosting. So, we have that in common, but still odd af b/c my straight newznab/nZEDb instances both use highwinds and work.

**Comment by jeevcat** [comment]
I can confirm that I'm having the same issue, however I don't use SSL on my newserver (using port 119).
I get a little red `• 1` at the bottom of the screen.

**Comment by DariusIII** [comment]
I have installed NNTmux couple of times after this issue was started, and it always completed successfully. You can enable debugging in nntmux/config/settings.php (enable all the options, including CLI and WEB debugging) so more info is provided.

**Comment by nrk666** [comment]
Just an observation : You are one of the devs of a couple of forks (thank you btw, we appreciate it). You might very well be doing something that isn't in the install documentation without even realizing it because to you, its second nature. It's very possible you are doing something during installation (or even OS installation) that seems perfectly natural for you to do, but if it isn't in the docs, the rest of us are probably missing that step. 

Can you take the Ubuntu Install Guide and do a fresh 16.04 install following it step by step? Don't cheat. Follow it, verbatim. Because that's how the rest of us do installs. 

I'd also be willing to do a fresh install and document my results on the wiki for comparison, maybe we can nail down the delta that way. I can't contribute codewise much, its been over twenty years since I did any kind of real programming (yeah, I'm old) but I can help straighten out documentation easily enough.

**Comment by DariusIII** [comment]
Oh, i know SSL does not work, it is on my TODO list to fix. Btw, i am using mariadb 10.1 and apache, so no big difference to your setup. (also apache on onedev  VM and nginx on another dev VM). Both run on Ubuntu 16.04 with ondrej sury ppa for PHP.

**Comment by nrk666** [comment]
I've been using Maria 10.1 as well, I don't think that's the problem, that seems rather benign.  In my notes from installing nntmux (yay, I took notes) I did not use Ondrej's external ppa. I used the standard PHP7 from Ubuntu default PPA's much like with nZEDb on 16.04. I used nginx, but I can use apache if needed, thats no big deal, I doubt that's the issue either, its just a webserver, it wouldn't account for the php backend at all. 

When I get some time, I'll retry using Ondrej's PPA, but you weren't clear on if you used PHP7 or PHP5.6?

**Comment by jeevcat** [comment]
I also am using PHP7, am on Ubuntu 16.04 and used nginx. Perhaps a bad combination?

**Comment by nrk666** [comment]
Very small sample size to jump to that conclusion, but if I try out Ondrej's ppa later this week (saturday maybe?) and it works, then we might be on to something. 

Neither Apache or Nginx should affect what PHP does in the background, I mean, if you get the little red "-1" like Darius said, that just means there was an error connecting to the USP (if you had SSL on) - you can get the same error running it by hand on the CLI, so I doubt that Apache vs Nginx is the root cause here. I wouldn't think there would be that kind of difference between stock PHP7 and ondrej's PHP7, so thats why I asked if Darius was still using 5.6 or 7. nZEDb is moving to 7, but if this is a closer fork of newznab, I think newznab is still on 5.6, or at the very least, not dev'ing out enough to warrant moving to 7 like nZEDb does. I haven't been paying that close of attention to it. I mainly just do what the nZEDb guys recommend, Darius being one of them, hehe. Of course, I could be totally wrong about stock vs ondrej, so I'll try to give it a test later this weekend maybe.

**Comment by DariusIII** [comment]
This is no longer an issue, as NNTmux uses new install process, introduced in commit 52cb2ec048af76066dd56e04285d5617d05977ab

**Comment by nrk666** [comment]
thanks, I'll give it another look this weekend maybe
