### ISSUE TITLE
Getting many errors when running decrypt_hashes.php all

### ISSUE THREAD

**Issue by jeevcat** [NNTmux/newznab-tmux#122]
I get the following error hundreds of times when I run `php NNTmux/misc/update/decrypt_hashes.php full`:

```
PHP Notice:  Undefined index: releases_id in /var/www/NNTmux/nntmux/NameFixer.php on line 1133
```

Any ideas what could be causing this?

**Comment by DariusIII** [comment]
Because it should be id not releases_id. Will fix it.
