### ISSUE TITLE
Unexpected failure hashing password Unable to add admin user!

### ISSUE THREAD

**Issue by Goeny** [NNTmux/newznab-tmux#1222]
**Describe the bug**
While running artisan nntmux:install it stops with an error

**To Reproduce**
Run the install process as described.
run artisan nntmux:install 

**Expected behavior**
Finished install

**Screenshots**
<img width="488" alt="nntmux" src="https://user-images.githubusercontent.com/3872395/151675295-18c1757a-bd63-46fb-832b-b671d7781eeb.png">

**Installation (please complete the following information):**
 - OS: CentOS 7
 - PHP version: 8.0.15
 - NNTmux version or commit: master

**Additional context**
Used the Ubuntu install instructions on a running CentOS webhost.
Skipped al the apache, mysql and .deb parts and made sure to install all dependencies.
I expected this to be a missing libargon2. But everything is installed. 

[EDIT]
Just changed the password hashing to bcrypt and now install works

Still not sure why argon is not working

**Comment by DariusIII** [comment]
Maybe it's something related to PHP in CentOS itself.

**Comment by BakasuraRCE** [comment]
FYI: It is a bug in PHP 8.x

Just change the PASSWORD_HASH env to "argon2id" or "bcrypt"

**Comment by BakasuraRCE** [comment]
@DariusIII Hi! Can you add this strange problem as a tip in Readme?
