### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by alexmateescu** [NNTmux/newznab-tmux#1232]
hi. i have noticed this on the tmux ui and was curios how to fix it.
![Screenshot 2022-03-09 at 23 03 31](https://user-images.githubusercontent.com/22677210/157554045-767f0c8d-1e80-4595-8ac3-23f38988cf25.png)

any idea what it could be related to or how to find out?

**Comment by DariusIII** [comment]
Some release is creating this issue, but without more data i am unable to help.

**Comment by alexmateescu** [comment]
If you can point me in the right direction or log i can provide them

**Comment by alexmateescu** [comment]
[2022-03-12 14:31:54] NNTmux.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/NNTmux/Blacklight/ReleaseCleaning.php:165)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/ReleaseCleaning.php(165): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Trying to acces...', '/var/www/NNTmux...', 165)
#1 /var/www/NNTmux/Blacklight/NZBImport.php(390): Blacklight\\ReleaseCleaning->releaseCleaner('[309964]-[FULL]...', 'r@ndom.tv (r@nd...', 'alt.binaries.te...')
#2 /var/www/NNTmux/Blacklight/NZBImport.php(360): Blacklight\\NZBImport->insertNZB(Array)
#3 /var/www/NNTmux/Blacklight/NZBImport.php(183): Blacklight\\NZBImport->scanNZBFile(Object(SimpleXMLElement), false)
#4 /var/www/NNTmux/misc/testing/nzb-import.php(79): Blacklight\\NZBImport->beginImport(Array, false, true, true)
#5 {main}
"}

**Comment by alexmateescu** [comment]
[2022-03-12 21:54:29] NNTmux.ERROR: Cannot assign null to property Blacklight\Categorize::$groupName of type string {"exception":"[object] (TypeError(code: 0): Cannot assign null to property Blacklight\\Categorize::$groupName of type string at /var/www/NNTmux/Blacklight/Categorize.php:94)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/NZBImport.php(405): Blacklight\\Categorize->determineCategory(0, '', '')
#1 /var/www/NNTmux/Blacklight/NZBImport.php(360): Blacklight\\NZBImport->insertNZB(Array)
#2 /var/www/NNTmux/Blacklight/NZBImport.php(183): Blacklight\\NZBImport->scanNZBFile(Object(SimpleXMLElement), false)
#3 /var/www/NNTmux/misc/testing/nzb-import.php(79): Blacklight\\NZBImport->beginImport(Array, false, true, true)
#4 {main}
"}

**Comment by DariusIII** [comment]
Which option did you select on nzb import, with filenames or without filenames? Issue could be there.

**Comment by alexmateescu** [comment]
initially when i imported the nzbz from nZEDb i ticked without filename but since that import is over i have disabled the import. 
another thing is that compared to nZEDb the logging does not work so i can't see exactly what is happening. i've ticket the option to log each thing individually but no log files are created. the above are from the laravel log. any hints on how to fix that?

**Comment by DariusIII** [comment]
Group name is not used in NNTmux anymore, maybe the problem lies there. Logs are located in storage/logs folder, but to have more info you need to edit your .env file and set APP_ENV from production to local and enable all the debugging options (set them to true).

**Comment by alexmateescu** [comment]
I will enable the logs and see if i can get more. Something is strange
though. I am chasing a particular post from a.b.multimedia and it does not
appear to be indexed even though is not passworded and it is posted within
the backfill period.

**Comment by Fossil01** [comment]
Can be tons of reasons. Low completion on specific provider, NNTmux blacklists, etc.

**Comment by jjaomni** [comment]
```
2022-07-17 17:56:05] NNTmux.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/NNTmux/Blacklight/ReleaseCleaning.php:165)
[stacktrace]
#0 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/NNTmux/Blacklight/ReleaseCleaning.php(165): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/NNTmux/Blacklight/NZBImport.php(390): Blacklight\\ReleaseCleaning->releaseCleaner()
#3 /var/www/NNTmux/Blacklight/NZBImport.php(360): Blacklight\\NZBImport->insertNZB()
#4 /var/www/NNTmux/Blacklight/NZBImport.php(183): Blacklight\\NZBImport->scanNZBFile()
#5 /var/www/NNTmux/misc/testing/nzb-import.php(79): Blacklight\\NZBImport->beginImport()
#6 {main}
"} 
```


Still getting this over and over again while trying to import and import fails.
