### ISSUE TITLE
Prevent 1 part obfuscated releases from ever entering the releases table

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1236]
My releases table is being cluttered with a crapton of 1 part "releases", all obfuscated. There are auto-deleted after X hours but they make the auto increment go up for no reason and since there are hundreds of thousands of them make queries run slower.

Is there a way to kick these out before ever inserting them into the releases table?

**Comment by DariusIII** [comment]
Maybe set minimum files to form a release to 2?
