### ISSUE TITLE
Does this still work with PHP 5.6+?

### ISSUE THREAD

**Issue by riverar** [NNTmux/newznab-tmux#124]
composer.json enforces a 7+ requirement
https://github.com/NNTmux/newznab-tmux/blob/0.x/composer.json#L66

Documentation all over still claims compatibility with 5.6+. Is this still the case?
https://github.com/NNTmux/newznab-tmux/wiki/Ubuntu-Install-guide

**Comment by DariusIII** [comment]
Docs have not been updated, nntmux is PHP7+ only now.

**Comment by riverar** [comment]
I'll go through and update/submit a PR. Thanks for the quick response.

**Comment by DariusIII** [comment]
I am updating the wiki ATM
