### ISSUE TITLE
Type error /Blacklight/SphinxSearch.php in Blacklight\SphinxSearch::insertRelease at line 75

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1252]
**/Blacklight/SphinxSearch.php in Blacklight\SphinxSearch::insertRelease at line 75**

In function `insertRelease()` the variable `$parameters['categories_id']` needs to be a string because Manticore is expecting a string.

**Comment by DariusIII** [comment]
Just to be sure: are you using latest version of manticore with latest conf provided?
