### ISSUE TITLE
PPA think RAR is JPEG due to filename

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1253]
Specific filename inside rar: ` blablablabla.jpeg.mp4`
Subject inside NZB: `subject="[2/33] - &quot;BLABLABLA.Jpeg.XXX.1080p.MP4-blabla.vol00-01.par2&quot; yEnc (1/3)"`

Because there's `jpeg` in the filename in the NZB NNTmux tries to download the file and run it through Imagick to save as a "sample".

Looks like the regex here is the culprit: https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/post/ProcessAdditional.php#L919

**Comment by DariusIII** [comment]
I checked some releases and they do have names like that and proper samples set for them.

**Comment by DariusIII** [comment]
Regex does match that, that is true.

**Comment by DariusIII** [comment]
I am looking to fix this, but are we ceratin that these are not trully images? This regex specifically looks for jpeg inside the filename, not at thne end of it.
