### ISSUE TITLE
Can't log in or create account

### ISSUE THREAD

**Issue by cyberbabacool** [NNTmux/newznab-tmux#1256]
**Describe the bug**
Fresh install, when opening my browser going to the site and entering the credentials i've set in .env file it just reload the login page

**To Reproduce**
1. open website
2. enter admin credentials
3. press sing in
4. page reloads, not logged in

**Expected behavior**
be logged as an admin

**Installation (please complete the following information):**
 - OS: debian 11
 - PHP version 8.1
 - NNTmux version  : last one]
 - sql : mariadb
 - web server : nginx

I saw others had this problem, I tried changing to local, debug true, changins app url to 127.0.0.1 or localhost or nntmux.mydomain.com no way to make this work

**Comment by DariusIII** [comment]
Try to change caching to file. Or if on file, tro something else.

**Comment by anoteng** [comment]
I experience the exact same failure. caching is set to file.
Apache log shows: AH00128: File does not exist: /var/www/html/boaform/admin/formLogin

**Comment by anoteng** [comment]
Adding a value to app_url seems to have solved it for me.

**Comment by DariusIII** [comment]
> I experience the exact same failure. caching is set to file. Apache log shows: AH00128: File does not exist: /var/www/html/boaform/admin/formLogin

And Apache is right, as this file does not exist at all in newznab-tmux and never did. There is no separate login form for admin user and there never was. Have you maybe changed something?

**Comment by DrakeJones** [comment]
An academic question - if web server : nginx, then why is Apache logging anything?

**Comment by DariusIII** [comment]
> An academic question - if web server : nginx, then why is Apache logging anything?

Oh, wow. I havent noticed that server is nginx. There must be some misconfiguration on OP end.

**Comment by DrakeJones** [comment]
There is no doubt in my mind that you are correct.

**Comment by anoteng** [comment]
Sorry, I just added a mee too to the OP, didn't notice OP used nginx. I use apache, op uses nginx

**Comment by DrakeJones** [comment]
OP might want to try cache=array plus app_url=their website's qdn.

**Comment by cyberbabacool** [comment]
> OP might want to try cache=array plus app_url=their website's qdn.

I already tried that but same login loop^, i'll try to set it up with docker to see if I can have more luck ;)
thanks for all your replies
