### ISSUE TITLE
Cannot page through releases or predb entries in admin view

### ISSUE THREAD

**Issue by tekdoc** [NNTmux/newznab-tmux#1258]
**Describe the bug**
In admin view, clicking on a page number or forward/back arrow in "view releases" or "view pre database" just reloads the first page of the list. It is impossible to change to any other page. The same controls work as expected in the "groups" and "regexes" sub-menus.

**To Reproduce**
1. Go to 'admin > view releases or admin > view pre database '
2. Click on 'any page number, forward or back arrow at the top or bottom of the list'
3. Scroll down to 'the releases or predb list'
4. See error: The first page of the list reloads.

**Expected behavior**
The selected page number should load or the page should advance or go back to the previous one

**Screenshots**
Screen recording available upon request

**Installation (please complete the following information):**
 - OS: [e.g. Ubuntu] FreeBSD 12.3
 - PHP version [e.g. PHP 7.2.12] PHP 8.1
 - NNTmux version or commit [e.g. 1.0] Master

**Additional context**
Same behavior with PHP 7.4 and v1.8.0 release on both FreeBSD and Ubuntu 20.04

**Comment by jjaomni** [comment]
yeap i get this too..

**Comment by DariusIII** [comment]
I am planning to tackle this issue ASAP.
