### ISSUE TITLE
Option to fixreleasenames in misc using RAR content.

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1260]
Going through my misc stuff I see quite few gibberish post names with complete file names showing in "RAR Contains  Files:" like this example from a.b.boneless:

```
[01/40] "Mq5Av2mmTBwQsDLHtU5Dwt.par2" yEnc 

RAR Contains Files: 																								
Hannes Minnaar - 24 Preludes and  Fugues, Op. 87 (2022) FLAC + MP3/Hannes Minnaar - 24 Preludes and  Fugues, Op. 87 (2022)/CD2/21 - 24 Preludes and Fugues, Op. 87_ Prelude  No. 24 in D Minor.mp3

Hannes Minnaar - 24 Preludes and Fugues, Op. 87 (2022) FLAC + MP3/Hannes Minnaar - 24 Preludes and Fugues, Op. 87/CD1/01 - 24 Preludes and Fugues, Op. 87_ Prelude No. 1 in C Major.flac
	No Password 9.87Mb Oct 3, 2022
```

It would be nice to have an option in fixReleaseNames.php to use rar content to rename misc/other/specific groups. 

A lot easier said than done and I can't done it.

Thanks for your time.

**Comment by DariusIII** [comment]
You mean this?

https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/processing/post/ProcessAdditional.php#L1108-L1120

**Comment by DrakeJones** [comment]
Must be that!
