### ISSUE TITLE
500 error when trying to view Books and Audio

### ISSUE THREAD

**Issue by Jonesyj83** [NNTmux/newznab-tmux#1264]
**Describe the bug**
When Trying to view all Books or Audio, click on menu and then Audio or Books I get a 500 error.

**To Reproduce**
Click on Menu Audio or Books in menu

**Installation (please complete the following information):**
 - OS: Ubuntu 20.04
 - PHP version php8.1
 - NNTmux version or commit lastest git cloned master
 - mariadb 10.10 Also tried this on 10.5 same thing

**Additional context**
Have local and debug on:
For Books:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND r.id IN () AND r.categories_id IN (3010, 3020, 3030, 3040, 3060,...' at line 12 (SQL: SELECT r.id, r.rarinnerfilecount, r.grabs, r.comments, r.totalpart, r.size, r.postdate, r.searchname, r.haspreview, r.passwordstatus, r.guid, df.failed AS failed, m.*, r.musicinfo_id, r.haspreview, g.name AS group_name, rn.releases_id AS nfoid FROM releases r LEFT OUTER JOIN usenet_groups g ON g.id = r.groups_id LEFT OUTER JOIN release_nfos rn ON rn.releases_id = r.id LEFT OUTER JOIN dnzb_failures df ON df.release_id = r.id INNER JOIN musicinfo m ON m.id = r.musicinfo_id WHERE m.id IN () AND r.id IN () AND r.categories_id IN (3010, 3020, 3030, 3040, 3060, 3999) GROUP BY m.id ORDER BY r.postdate desc)

For Audio: 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND r.id IN () AND r.categories_id IN (3010, 3020, 3030, 3040, 3060,...' at line 12 (SQL: SELECT r.id, r.rarinnerfilecount, r.grabs, r.comments, r.totalpart, r.size, r.postdate, r.searchname, r.haspreview, r.passwordstatus, r.guid, df.failed AS failed, m.*, r.musicinfo_id, r.haspreview, g.name AS group_name, rn.releases_id AS nfoid FROM releases r LEFT OUTER JOIN usenet_groups g ON g.id = r.groups_id LEFT OUTER JOIN release_nfos rn ON rn.releases_id = r.id LEFT OUTER JOIN dnzb_failures df ON df.release_id = r.id INNER JOIN musicinfo m ON m.id = r.musicinfo_id WHERE m.id IN () AND r.id IN () AND r.categories_id IN (3010, 3020, 3030, 3040, 3060, 3999) GROUP BY m.id ORDER BY r.postdate desc)

not sure if I have forgot to install something, Have been going through everything but can't find anything wrong.

**Comment by Jonesyj83** [comment]
looking into it more domain.com/browse/Books and browse/Audio works, Guess this can just be changed in the headermenu.tpl

**Comment by DariusIII** [comment]
Ids from musicinfo and releases table are empty in those queries. Enable debugging and set app_env to local and you will have more info. Also check error logs in nginx/apache.
