### ISSUE TITLE
PHP syntax error appears when activating tmux configuration

### ISSUE THREAD

**Issue by riverar** [NNTmux/newznab-tmux#127]
Branch: 0.x ecdcbb7

When attempting to launch tmux configuration (via start.php), the following error appears:

```
PHP Parse error: syntax error, unexpected '?' in
/var/www/NNTmux/misc/update/nix/tmux/monitor.php on line 25
```

![image](https://cloud.githubusercontent.com/assets/475132/23569378/d398c8a6-0013-11e7-8b89-839ca9b5cade.png)

**Comment by DariusIII** [comment]
Do you use PHP 7? That is new PHP 7 ternary syntax and will not work on lower versions, which are not supported anymore.

**Comment by riverar** [comment]
Versions
```
MariaDB 10.0.29-MariaDB-1~trusty mariadb.org binary distribution
4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.0.16-4+deb.sury.org~trusty+1 (cli) (built: Mar  2 2017 13:27:03) ( NTS )
Apache/2.4.7 (Ubuntu)
Branch: 0.x
```

**Comment by DariusIII** [comment]
Can you try starting it by 
`php tmux-ui.php start`
command

**Comment by riverar** [comment]
Same issue. Looks like PHP 7's new null coalescing operator (??) didn't make it in PHP 7.0. It's in 7.1.3RC1 and higher https://github.com/php/php-src/commit/2d069f640e6cccfa3ba8b1e4f375ade20fb33f64.

I'll upgrade to 7.1.3+ tonight.

**Comment by DariusIII** [comment]
This should be no issue anymore, as php is at 7.1.4 in ubuntu.

**Comment by DariusIII** [comment]
As NNTmux requires PHP7.1 as minimum i am closing this issue.
