### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by bubundas17** [NNTmux/newznab-tmux#1272]
**Describe the bug**
Docker container not building.
```
core downloading...
 extra downloading...
 community downloading...
 multilib downloading...
error: target not found: php7-fpm
error: target not found: php7-gd
error: target not found: php7-intl
```

**To Reproduce**
Build the docker container

**Expected behavior**
It should build without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/26280146/216774283-d48f37b7-b65e-4cee-a19d-95d876307a87.png)

**Installation (please complete the following information):**
 - OS: Docker
**Additional context**

**Comment by DariusIII** [comment]
Have you followed instructions?
Maybe @wolfgang-s could help you more, as i am not using docker.

**Comment by bubundas17** [comment]
It seems like php7 packages are no longer present in archlinux.  Need to update the Dockerfile.

**Comment by egyptianbman** [comment]
I'm using docker, I'll work on updating my installation and provide a PR.

**Comment by egyptianbman** [comment]
@bubundas17 can you try building #1273 to confirm it resolves your issue?
