### ISSUE TITLE
Can't login to admin

### ISSUE THREAD

**Issue by auskento** [NNTmux/newznab-tmux#1284]
I have attempted a nntmux install following the Ubuntu instructions with no isues

I always get to the end and am unable to login with the credentials used in .env

I have set it to local with debugging on
Where will i see the actual debug logs?

Is it from a file or should i see something on the web page.
So far I am seeing nothing anywhere obvious to try and track down where this is failing

**Comment by DariusIII** [comment]
Logs are located in `storage/logs` folder.

You can check the following issues: https://github.com/NNTmux/newznab-tmux/issues/1221, https://github.com/NNTmux/newznab-tmux/issues/1173

**Comment by auskento** [comment]
Yes, i have been back and forth thru those 2 issues repeatedly

I have a user called nzbindexer in my database
I can use a myql --username=nzbindexer --password=<pass> nntmux and can connect to the database

How should DB_USERNAME be entered?
I have tried
DB_USERNAME=nzbindexer
DB_USERNAME=nzbindexer@localhost
DB_USERNAME=nzbindexer@hostname
I keep seeing this in the log thouugh
SQLSTATE[HY000] [1045] Access denied for user 'nzbindexer@localhost'@'localhost' (using password: YES) at /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)

**Comment by auskento** [comment]
And now the logfile is not generating, no logfile to inspect, which may indicate everything is OK, except i still can't log in :(

**Comment by DariusIII** [comment]
@auskento 
`DB_USERNAME=nzbindexer`

Btw, issue you have is related to DB config, not NNTmux. You need to check security settings for the database. As @Fossil01 wrote already, try connecting to socket and not to TCP port. 
Try something like this:

https://serverfault.com/questions/1099054/mariadb-10-5-12-access-denied-for-root127-0-0-1

**Comment by multipass83** [comment]
@auskento Did you find a solution to your problem? I have the same issue :/

**Comment by auskento** [comment]
No, I haven't returned to trying to resolve it at this point.

I will look at it during the Easter break to see if i can get it working and provide updated info if I do

I'm led to believe it is a DB connection issue more than nntmux
________________________________

**Comment by n4zmz** [comment]
I too have authentication issues after fresh install.

After I rebuilt the auth ui (php artisan ui:auth), I'm getting:
Vite manifest not found at: /var/www/NNTmux/public/build/manifest.json

**Comment by n4zmz** [comment]
Rebuilt the NNTmux directory and updated the .env to set cache to redis.

CACHE_DRIVER=redis
QUEUE_CONNECTION=redis

Thanks to Fossil for the quick find.

Login is working.
