### ISSUE TITLE
NNTmux.ERROR: #0  This just started happening.

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1285]
Release renaming seems to be stuck in a loop for some, but not all releases.  I don't know if the problems are related.

[2023-03-16 08:47:20] NNTmux.ERROR: #0 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/NNTmux/vendor/league/climate/src/Util/Writer/StdOut.php(14): fwrite()
#3 /var/www/NNTmux/vendor/league/climate/src/Util/Output.php(183): League\CLImate\Util\Writer\StdOut->write()
#4 /var/www/NNTmux/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(37): League\CLImate\Util\Output->write()
#5 /var/www/NNTmux/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute()
#6 /var/www/NNTmux/vendor/league/climate/src/CLImate.php(385): League\CLImate\TerminalObject\Router\Router->execute()
#7 /var/www/NNTmux/vendor/league/climate/src/CLImate.php(400): League\CLImate\CLImate->buildTerminalObject()
#8 /var/www/NNTmux/vendor/league/climate/src/CLImate.php(436): League\CLImate\CLImate->routeRemainingMethod()
#9 /var/www/NNTmux/Blacklight/ColorCLI.php(59): League\CLImate\CLImate->__call()
#10 /var/www/NNTmux/Blacklight/Binaries.php(1480): Blacklight\ColorCLI->error()
#11 /var/www/NNTmux/Blacklight/Binaries.php(557): Blacklight\Binaries->log()
#12 /var/www/NNTmux/misc/update/multiprocessing/.do_not_run/switch.php(112): Blacklight\Binaries->scan()
#13 {main}  

Environment ......................................................................................................................................  
  Application Name .......................................................................................................................... NNTmux  
  Laravel Version ........................................................................................................................... 10.3.3  
  PHP Version ............................................................................................................................... 8.1.16  
  Composer Version ........................................................................................................................... 2.5.4  
  Environment ........................................................................................................................... production  
  Debug Mode ................................................................................................................................... OFF  
  Maintenance Mode ............................................................................................................................. OFF  

  Cache ............................................................................................................................................  
  Config ................................................................................................................................ NOT CACHED  
  Events .................................................................................................................................... CACHED  
  Routes ................................................................................................................................ NOT CACHED  
  Views ..................................................................................................................................... CACHED  

  Drivers ..........................................................................................................................................  
  Broadcasting ................................................................................................................................. log  
  Cache ...................................................................................................................................... array  
  Database ................................................................................................................................... mysql  
  Logs ............................................................................................................................... stack / daily  
  Queue ....................................................................................................................................... sync  
  Scout ...................................................................................................................................... mysql  
  Session ..................................................................................................................................... file

**Comment by DariusIII** [comment]
Need to check, but i need more info. Stack trace lists CLImate errors, which does not affect binaries processing, it is just an output package.
