### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException Route [queue] not defined.

### ISSUE THREAD

**Issue by egyptianbman** [NNTmux/newznab-tmux#1290]
After updating to the latest code, composer, database and env configs, I'm getting the following:

![image](https://user-images.githubusercontent.com/323600/226540283-962884ec-3103-44d9-9d16-0bf2067414b9.png)

Has anyone else seen this or have any insight as to what might be the cause? I can't seem to find any reference to a queue route anywhere.

**Comment by DariusIII** [comment]
Try clearing smarty cache and compiled templates by issuing:

`php artisan ytake:smarty-clear-cache` and `php artisan ytake:smarty-clear-compiled`

Support for integrated NZBGet, SABNzbd etc has been dropped.

**Comment by egyptianbman** [comment]
Unfortunately, clearing the cache doesn't seem to help. I even manually deleted `storage/framework/smarty/templates_c/f1a0c2906c5b30768d5e65614bbe72d111a5e4c4_0.file.headermenu.tpl.cache.php`, but it gets recreated on the first page request.

**Comment by egyptianbman** [comment]
Tracked down the problem, it's with my setup. Sorry for the noise!

**Comment by DariusIII** [comment]
@egyptianbman You can join discord, if you wish: https://discord.gg/GjgGSzkrjh

**Comment by egyptianbman** [comment]
Oh, it was a really dumb mistake on my part. Due to the size of the `resources` directory, I mount it into the docker container from a separate drive. I had a bug in my configuration that at times would instead of mounting it from the other drive, would mount it from the code's checkout path. Upon fixing that bug, switching the mount back to the drive led to outdated code in `resources/{views,smarty}`, etc.

To fix, I modified the external drive's holdings to specifically be only the `resources/{covers,logs,nzb}` instead of the whole `resources` directory.

**Comment by egyptianbman** [comment]
Oh wow, thanks for the heads up!
