### ISSUE TITLE
Manticore and Elasticsearch build fail using master

### ISSUE THREAD

**Issue by n4zmz** [NNTmux/newznab-tmux#1294]
Using: https://github.com/NNTmux/newznab-tmux/wiki/Ubuntu-Install-guide

During the search init

$ php artisan nntmux:create-es-indexes

   ErrorException 

  Array to string conversion

  at vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php:304
    300▕      * @return void
    301▕      */
    302▕     public function line($string, $style = null, $verbosity = null)
    303▕     {
  ➜ 304▕         $styled = $style ? "<$style>$string</$style>" : $string;
    305▕ 
    306▕         $this->output->writeln($styled, $this->parseVerbosity($verbosity));
    307▕     }
    308▕ 

$ php artisan nntmux:populate --manticore --releases

   Manticoresearch\Exceptions\ConnectionException 

  Received HTTP/0.9 when not allowed

  at vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Transport/Http.php:106
    102▕         if ($errorno>0) {
    103▕             $error = curl_error($conn);
    104▕ 
    105▕             self::$curl = null;
  ➜ 106▕             throw new ConnectionException($error, $request);
    107▕         }
    108▕ 
    109▕ 
    110▕         $this->logger->debug('Request body:', [

      +4 vendor frames 

  5   Blacklight/ManticoreSearch.php:142
      Manticoresearch\Index::truncate()

  6   app/Console/Commands/NntmuxPopulateSearchIndexes.php:64
      Blacklight\ManticoreSearch::truncateRTIndex()

**Installation (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - PHP version [PHP 8.1.2-1ubuntu2.11]
 - NNTmux version or commit [master]

**Comment by DariusIII** [comment]
Manticore needs updated conf which is located in misc/manticoresearch folder.

**Comment by n4zmz** [comment]
Manticore.conf is identical to file in misc subdirectory.  Issue is probably with Mariadb 10.6 as the search log is responding with a disconnect.

**Comment by DrakeJones** [comment]
I started having connection problems, too:

2023-04-02 12:06:39] NNTmux.ERROR: Failed to connect to 127.0.0.1 port 9308 after 0 ms: Connection refused {"exception":"[object] (Manticoresearch\\Exceptions\\ConnectionException(code: 0): Failed to connect to 127.0.0.1 port 9308 after 0 ms: Connection refused at /var/www/NNTmux/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Transport/Http.php:106)
[stacktrace]
#0 /var/www/NNTmux/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Client.php(366): Manticoresearch\\Transport\\Http->execute()
#1 /var/www/NNTmux/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Client.php(377): Manticoresearch\\Client->request()
#2 /var/www/NNTmux/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Indices.php(217): Manticoresearch\\Client->request()
#3 /var/www/NNTmux/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Index.php(273): Manticoresearch\\Indices->truncate()
#4 /var/www/NNTmux/Blacklight/ManticoreSearch.php(142): Manticoresearch\\Index->truncate()
#5 /var/www/NNTmux/app/Console/Commands/NntmuxPopulateSearchIndexes.php(109): Blacklight\\ManticoreSearch->truncateRTIndex()
#6 /var/www/NNTmux/app/Console/Commands/NntmuxPopulateSearchIndexes.php(44): App\\Console\\Commands\\NntmuxPopulateSearchIndexes->manticorePreDB()
#7 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\NntmuxPopulateSearchIndexes->handle()
#8 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#13 /var/www/NNTmux/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#14 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Console/Command.php(164): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/NNTmux/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#16 /var/www/NNTmux/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/NNTmux/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#19 /var/www/NNTmux/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}
"}

**Comment by n4zmz** [comment]
Elasticsearch logs:
[2023-04-03T12:23:52,315][ERROR][o.e.i.g.GeoIpDownloader  ] [nntmux] exception during geoip databases update
org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
	at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:137) ~[ingest-geoip-7.17.9.jar:7.17.9]
	at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:284) [ingest-geoip-7.17.9.jar:7.17.9]
	at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:100) [ingest-geoip-7.17.9.jar:7.17.9]
	at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:46) [ingest-geoip-7.17.9.jar:7.17.9]
	at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-7.17.9.jar:7.17.9]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.9.jar:
7.17.9]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.9.jar:7.17.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
 
Is 2 shards a problem? shards started [[releases][1], [releases][0]]

**Comment by n4zmz** [comment]
MANTICORESEARCH_PORT  was incorrect in .env, now I'm trying to login but getting failures.
