### ISSUE TITLE
getTVFanart() is never used

### ISSUE THREAD

**Issue by ghost** [NNTmux/newznab-tmux#1296]
https://github.com/NNTmux/newznab-tmux/blob/a30be990a912c86169b1eb0ad44bfea8f654f774/Blacklight/libraries/FanartTV.php#L64

This function is never used in NNTmux. Could be used to greatly improve the number of TV covers found I guess. Only works with TVDB ID's so might be used inside `TVDB` class. Only the `getMovieFanArt` function of Fanart is used right now.

Could be used inside the `getPoster()` function perhaps, but it would also need the TVDB ID for that, now only the VideoID is used for that function.

If used to grab posters, this is a good addition IMHO. It grabs the TV Poster with the most likes, which usually means the original English one:

```php
$poster = collect($fanArt['tvposter'])->sortByDesc('likes')[0]['url'];
```

**Comment by DariusIII** [comment]
Feel free to create a PR and i will gladly accept it.
