### ISSUE TITLE
utf8_encode() is deprecated in PHP 8.2.0

### ISSUE THREAD

**Issue by ghost** [NNTmux/newznab-tmux#1299]
`utf8_encode()` function is deprecated: https://www.php.net/manual/en/function.utf8-encode.php and https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated

Function is used in NZBImport, Binaries, CollectionsCleaning, ReleaseCleaning and ProcessReleases.

Not sure if the encoding is still needed, Spotweb seems to be using `mb_convert_encoding($variable, 'UTF-8', 'ISO-8859-1');` and my editor says:

```
@deprecated 8.2
Consider to use {@link mb_convert_encoding}, {@link UConverter::transcode()} or {@link iconv()}
```

**Comment by DariusIII** [comment]
NNTmux officially still does not support php8.2 but i will look into these and fix them.
