### ISSUE TITLE
missing install.sh file

### ISSUE THREAD

**Issue by dancingmadkefka** [NNTmux/newznab-tmux#1316]
**Describe the bug**
The install.sh file is missing from the docker folder in the NNTmux repository. This prevents the installation of NNTmux using docker-compose.

**To Reproduce**

1. Clone the NNTmux repository from GitHub to a project folder.
2. Navigate to the docker folder inside the newznab-tmux folder.
3. Try to find the install.sh file.
4. See that the install.sh file is not there.

**Expected behavior**
The install.sh file should be present in the docker folder and should be executable. It should run the commands necessary to install NNTmux inside the web container.

**Screenshots**
Not applicable.

**Installation (please complete the following information):**

- OS: Windows 11
- PHP version: Not applicable
- NNTmux version or commit: Latest master branch

**Additional context**
I tried to download the install.sh file from GitHub using curl, but it gave me a 404 not found error. I also tried to run the installation command using Git Bash, but it gave me an error that said “exec: "docker/install.sh": stat docker/install.sh: no such file or directory”. I followed the instructions from the readme file and the wiki page, but they did not work for me. I need help to install NNTmux using docker-compose on Windows.

**Comment by DariusIII** [comment]
It's not missing, docker has been updated and now it uses [Laravel Sail](https://laravel.com/docs/10.x/sail). Wiki needs to be updated to reflect this change.

**Comment by dancingmadkefka** [comment]
> It's not missing, docker has been updated and now it uses [Laravel Sail](https://laravel.com/docs/10.x/sail). Wiki needs to be updated to reflect this change.

Thanks for you reply. So what does that mean in terms of installing? What commands need to be run instead?

**Comment by DariusIII** [comment]
![image](https://github.com/NNTmux/newznab-tmux/assets/3399658/fc6150b5-0ee9-453b-be12-c8fbc994f4b3)

**Comment by DariusIII** [comment]
https://github.com/NNTmux/newznab-tmux/blob/master/README.md#docker
