### ISSUE TITLE
Releases not being renamed post-inclusion of new matching regexes

### ISSUE THREAD

**Issue by nightah** [NNTmux/newznab-tmux#132]
Any releases which have already been processed will not be renamed by a new regex that has been added post initial processing.

**Comment by nightah** [comment]
Not sure if this is intended behaviour, however, you can run misc/testing/Dev/test-ReleaseCleaner.php to both test and rename releases after a new regex has been added.

**Comment by DariusIII** [comment]
It is intended behaviour :).
