### ISSUE TITLE
Warning: Could not select data from your database.

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#141]
When I try to install, I get he following error.  I check the db and I have all the other tables up to where it fails.  Not sure what the issue is.  Any help for this?

root@Ubuntu-1604-xenial-64-minimal /var/www/NNTmux/_install # php install_nntmux.php
File: /var/www/NNTmux/resources/db/schema/data/10-binaryblacklist.tsv
Inserting data into table: 'binaryblacklist'
File: /var/www/NNTmux/resources/db/schema/data/10-categories.tsv
Inserting data into table: 'categories'
File: /var/www/NNTmux/resources/db/schema/data/10-category_regexes.tsv
Inserting data into table: 'category_regexes'
File: /var/www/NNTmux/resources/db/schema/data/10-collection_regexes.tsv
Inserting data into table: 'collection_regexes'
File: /var/www/NNTmux/resources/db/schema/data/10-content.tsv
Inserting data into table: 'content'
File: /var/www/NNTmux/resources/db/schema/data/10-countries.tsv
Inserting data into table: 'countries'
File: /var/www/NNTmux/resources/db/schema/data/10-forumpost.tsv
Inserting data into table: 'forumpost'
File: /var/www/NNTmux/resources/db/schema/data/10-genres.tsv
Inserting data into table: 'genres'
File: /var/www/NNTmux/resources/db/schema/data/10-groups.tsv
Inserting data into table: 'groups'
File: /var/www/NNTmux/resources/db/schema/data/10-menu.tsv
Inserting data into table: 'menu'
File: /var/www/NNTmux/resources/db/schema/data/10-release_naming_regexes.tsv
Inserting data into table: 'release_naming_regexes'
File: /var/www/NNTmux/resources/db/schema/data/10-settings.tsv
Inserting data into table: 'settings'
File: /var/www/NNTmux/resources/db/schema/data/10-tmux.tsv
Inserting data into table: 'tmux'
Warning: Could not select data from your database.
Error: NNTmux installation failed. Fix reported problems and try again

**Comment by DariusIII** [comment]
It is not loading data from .tsv files into the DB. Enable debugging in nntmux/config/settings.php so you have better output.

**Comment by blimeybloke** [comment]
Got past this issue, I think it was file access for db user.  You can close this.
