### ISSUE TITLE
can't add new news groups

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1410]
In latest update from github
I can't add new news groups

**To Reproduce**
1. Go to admin->Groups->Add Group
2. Fill in information of the group you will add
3. Scroll down to save
4. check activated groups or search for it
   nothing is found

**Expected behavior**
by checking activated groups or search for it
I expected to find the one I added

**Installation (please complete the following information):**
 - OS: Ubuntu 22.04
 - PHP version 8.1
 - NNTmux version or commit latest from github

**Additional context**
nothing is written to log file

**Comment by DariusIII** [comment]
I just tried adding one group and had no issues. Have you set group as active before checking active groups?

**Comment by HengeDK** [comment]
Yes and if I search for it
no results

**Comment by DariusIII** [comment]
Have you added it as a.b.groupname or alt.binaries.groupname?

**Comment by HengeDK** [comment]
as
alt.binaries.teevee

**Comment by HengeDK** [comment]
tried both with same results

**Comment by HengeDK** [comment]
it was already there
but only comes in view groups
