### ISSUE TITLE
Details on TV

### ISSUE THREAD

**Issue by HengeDK** [NNTmux/newznab-tmux#1411]
**Describe the bug**
Press details on nzb files in tv series
is returning Error 500

**To Reproduce**
1. Go to TV
2. Click on any nzb files in tv series
3. See error

**Expected behavior**
Detailed view on nzb file

**Screenshots**

**Installation (please complete the following information):**
 - OS: Ubuntu 22.04]
 - PHP version 8.1
 - NNTmux version or commit Latest from github

**Additional context**
From log file
NNTmux.ERROR: After 1 retry to 1 node, connection has failed. No more retries left.

**Comment by DariusIII** [comment]
My guess is that elasticsearch or manticore are not running on your end, based on error you posted.

**Comment by HengeDK** [comment]
I will check

**Comment by HengeDK** [comment]
your right. My bad
