### ISSUE TITLE
Cloning issue

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#142]
Finally after about 15 hours and many restarts I was able to get things installed.  When I did the initial install, I did:

git clone -b 0.x https://github.com/NNTmux/newznab-tmux.git NNTmux

I pulled some headers from 1 newsgroup, and then I went to run php update_releases.php only to see it was not there.  Did I clone something wrong?
Attached is a screenshot of everything in the update directory.

![putty](https://user-images.githubusercontent.com/20652035/27229325-021595c6-5260-11e7-9df7-101bd2f22b19.png)

**Comment by DariusIII** [comment]
There is no more update_releases.php script, you need to run `misc/update/nix/multiprocessing/releases.php`

**Comment by blimeybloke** [comment]
Oh. Gotcha, thank you and sorry for bothering you :)

**Comment by blimeybloke** [comment]
What is the best way then to do a safe backfill?

**Comment by DariusIII** [comment]
Using the backfill script?

**Comment by blimeybloke** [comment]
Sorry, long week.  This is a fresh install since I wanted to upgrade to latest and now I want to backfill 1k days of a few groups but would like to do it 1 day at a time.  I remember there was a script the Johnny made where it would do 1 day, then update releases, then do +1 day and repeat
