### ISSUE TITLE
TV titles with some chars are not parsed properly

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1424]
https://github.com/NNTmux/newznab-tmux/blob/41ac1ca1c6505ea14562eedf6d389252bfc0d18d/Blacklight/processing/tv/TV.php#L429

This regex does not match searchnames which contain stuff like parentheses or brackets for example. `( )` `[ ]` and maybe more.

So something like: `This Showname (Australia) 10x07` won't match.

**Comment by DariusIII** [comment]
Fixed.
