### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#143]
Last issue for today, I promise :)

Everything on the front end seems to load until, I click on any page other than settings.  When I do, it gives error 500.  There is nothing in the error log about the issue.
So <site>/admin/site-edit.php loads fine

However,  <site>admin/tmux-edit.php gives error 500

/browsegroup works but if I click on a group, I get error 500

I have checked the error log but there is nothing pertaining to this issue.

I am viewing: /var/log/apache2/error.log

My conf file has:
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName localhost
    DocumentRoot "/var/www/NNTmux/www"
    LogLevel warn
    ServerSignature Off
    ErrorLog /var/log/apache2/error.log
    <Directory "/var/www/NNTmux/www">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    Alias /covers /var/www/NNTmux/resources/covers
</VirtualHost>

**Comment by pagnutti** [comment]
Also having the same issue on the stable and dev branch.
