### ISSUE TITLE
Use subquery instead of INNER JOIN?

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1463]
Here: https://github.com/NNTmux/newznab-tmux/blob/3afb1634a96b7ad00acb961ca4f885208865449c/Blacklight/processing/ProcessReleases.php#L834

I THINK this query below would yield the same results as the Eloquent query that is used now which uses INNER JOIN, making it a 25 second query if both tables are large. I tried putting an index on release_files.passworded but that did not make the current query faster.

This query with subquery takes only 26ms.

```sql
SELECT
    `id`,
    `guid`
FROM
    `releases`
WHERE
    `passwordstatus` = 1
    AND `id` IN (
        SELECT `releases_id`
        FROM `release_files`
        WHERE `passworded` = 1
    );
```

Please check but I think the according Laravel query would be:

```php
$releases = Release::query()
    ->select(['id', 'guid'])
    ->where('passwordstatus', '=', Releases::PASSWD_RAR)
    ->WhereIn('id', function ($query) {
        $query->select('releases_id')
            ->from('release_files')
            ->where('passworded', '=', Releases::PASSWD_RAR);
    })
    ->get();
```

**Comment by DariusIII** [comment]
This could actually work.
