### ISSUE TITLE
Updating PreDB failure

### ISSUE THREAD

**Issue by nightah** [NNTmux/newznab-tmux#153]
When attempting to run predb_import_daily_batch.php to update the PreDB it fails with the following error:

```
Skipping dump 1498480102, as your minimum unix time argument is 1498480103
Downloading: https://raw.githubusercontent.com/nZEDb/nZEDbPre_Dumps/master/dumps/1481552532/1498566511_predb_dump.csv.gz
Info: Inserting records from temporary table into predb table
PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 4 in /srv/http/NNTmux/nntmux/db/PreDb.php:121
Stack trace:
#0 /srv/http/NNTmux/nntmux/db/PreDb.php(121): PDOStatement->execute()
#1 /srv/http/NNTmux/cli/data/predb_import_daily_batch.php(206): nntmux\db\PreDb->executeInsert()
#2 {main}
  thrown in /srv/http/NNTmux/nntmux/db/PreDb.php on line 121
```

This is running latest dev nntmux with Mariadb 10.2 and PHP 7.1.6 and the DB is running the ROW_FORMAT InnoDB Compressed.

**Comment by DariusIII** [comment]
Testing it ATM but no errors are show and dumps are imported properly.

**Comment by nightah** [comment]
Issue was due to the specific sql_mode of STRICT_TRANS_TABLES being set on my config.
Removed this from my sql-mode dropped the triggers, re-created them and it now inserts successfully.
