### ISSUE TITLE
Docker 8.3 configuration files are blank

### ISSUE THREAD

**Issue by rtgoodwin** [NNTmux/newznab-tmux#1565]
**Describe the bug**
As the title says; seem to have been lost in some commits on the way from 8.2 to 8.3

**To Reproduce**
1. See the `docker/8.3/scheduler` and related files

**Expected behavior**
Less blank? :) 

**Installation (please complete the following information):**
- Just direct git clone from main branch 

**Additional context**
- Reported on Discord as well

**Comment by DariusIII** [comment]
Issue has been fixed in commit 717a425e605724663827b32b91556777ec1280af
