### ISSUE TITLE
[FR] Reprocess releases

### ISSUE THREAD

**Issue by nightah** [NNTmux/newznab-tmux#157]
Would like to add a Reprocess button to Admin -> Regexes -> Test Release Naming Regexes.

This would extend the following script: https://github.com/NNTmux/newznab-tmux/blob/dev/misc/testing/Dev/test-ReleaseCleaner.php

Allowing a user to reprocess existing releases with new regexes that have been added.
The template would need another field added to check the category also.

It might even be worthwhile having two buttons, one for a test reprocess and another to actually reprocess and change names, similar to passing arg3 of false/true into the test-ReleaseCleaner.php script.

**Comment by DariusIII** [comment]
Feel free to do a PR for this feature.
