### ISSUE TITLE
Error while install on Ubuntu 22.04.

### ISSUE THREAD

**Issue by vtk666** [NNTmux/newznab-tmux#1570]
**Describe the bug**
I'm getting this error while install artisan install:

Are you sure you want to install NNTmux? This will wipe your database!! (yes/no) [no]:
 > yes

Migrating tables and seeding them with initial data

  Dropping all tables ............................................................................................ 527.92ms DONE

   INFO  Preparing database.  

  Creating migration table ........................................................................................ 18.77ms DONE

   INFO  Running migrations.  

  2014_05_19_151759_create_forum_table_categories ................................................................ 242.02ms DONE
  2014_05_19_152425_create_forum_table_threads .................................................................... 17.78ms DONE
  2014_05_19_152611_create_forum_table_posts ...................................................................... 13.00ms DONE
  2015_04_14_180344_create_forum_table_threads_read ............................................................... 19.91ms DONE
  2015_07_22_181406_update_forum_table_categories ................................................................. 54.46ms DONE
  2015_07_22_181409_update_forum_table_threads ..................................................................... 8.67ms DONE
  2015_07_22_181417_update_forum_table_posts ...................................................................... 20.80ms DONE
  2016_05_24_114302_add_defaults_to_forum_table_threads_columns ................................................... 15.67ms DONE
  2016_07_09_111441_add_counts_to_categories_table ................................................................ 19.39ms DONE
  2016_07_09_122706_add_counts_to_threads_table ................................................................... 15.78ms DONE
  2016_07_10_134700_add_sequence_to_posts_table ................................................................... 15.21ms DONE
  2017_11_29_223842_create_countries_table ......................................................................... 8.79ms DONE
  2018_11_04_211718_update_categories_table ....................................................................... 34.47ms DONE
  2019_09_07_210904_update_forum_category_booleans ................................................................ 21.31ms DONE
  2019_09_07_230148_add_color_to_categories ........................................................................ 8.28ms DONE
  2020_03_22_050710_add_thread_ids_to_categories .................................................................. 12.71ms DONE
  2020_03_22_055827_add_post_id_to_threads ........................................................................ 11.37ms DONE
  2020_12_02_233754_add_first_post_id_to_threads ................................................................... 9.57ms DONE
  2021_07_31_094750_add_fk_indices ................................................................................ 22.73ms DONE
  2024_03_30_095622_update_forum_category_colors .................................................................. 19.54ms DONE
  2024_04_27_124202_create_media_infos_table ....................................................................... 7.44ms DONE
  2024_05_12_192646_add_uuid_column_to_failed_jobs_table ........................................................... 0.79ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nntmux.failed_jobs' doesn't exist (Connection: mysql, SQL: alter table `failed_jobs` add `uuid` varchar(255) not null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕ 
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

  i   A table was not found: You might have forgotten to run your database migrations. 
      https://laravel.com/docs/master/migrations#running-migrations

      +9 vendor frames 

  10  database/migrations/2024_05_12_192646_add_uuid_column_to_failed_jobs_table.php:14
      Illuminate\Support\Facades\Facade::__callStatic()
      +34 vendor frames 

  45  app/Console/Commands/InstallNntmux.php:58
      Illuminate\Console\Command::call()

**Installation (please complete the following information):**
 - OS: Ubuntu 22.04
 - PHP version: PHP 8.3
 - NNTmux version: 3.0.1

**Comment by DariusIII** [comment]
Change your database driver to mariadb and install again.

**Comment by necromancyr** [comment]
Would be good to add this to the guide as something that needs to be changed given MariaDB is suggested db server.

**Comment by kingsib** [comment]
for anyone wondering what this means, took me a while, 

edit the file:
/var/www/NNTmux/.env

Change the first line from:
DB_CONNECTION=mysql(i)
to:
DB_CONNECTION=mariadb
