### ISSUE TITLE
fixRelNames_standard seems to be stuck

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#159]
I have just done a fresh install, and this seems to be doing the same files over and over again.

The renames (unmatched) just keeps getting bigger and bigger.

Any help would be appreciated.

Thanks

**Comment by DariusIII** [comment]
Enable debugging in nntmux/config/settings.php and paste the stack trace here, if any appears.

**Comment by bert0901** [comment]
Think I have found the problem

On line 112 and I think too many "="

Should be :

if ($release['ishashed'] == 1 && $release['dehashstatus'] >= -6 && $release['dehashstatus'] <= 0) {

Then it will decrease the dehastatus by 1 until it gets too -7 and then does not get selected in the query.

Not sure if this is correct but it does decrease the queue.
