### ISSUE TITLE
Return actual data

### ISSUE THREAD

**Issue by ghost** [NNTmux/newznab-tmux#1596]
https://github.com/NNTmux/newznab-tmux/blob/3007ebf30ec023d8eccbde7ff1e8ffac38142c00/Blacklight/processing/tv/TVDB.php#L304

$response will still be false. So might want to rename this to $return so it returns the array.

Probably same thing for TMDB etc.

**Comment by DariusIII** [comment]
Actually it does not need to be renamed, as it is checked later and $return is being generated.
