### ISSUE TITLE
Route names should always be unique.

### ISSUE THREAD

**Issue by Kcchouette** [NNTmux/newznab-tmux#1604]
https://github.com/NNTmux/newznab-tmux/blob/83122f9dd7389a41526938bee3e6c912f79d6cfe/routes/web.php#L79-L80

**To Reproduce**
1. run `php artisan route:cache`
2. See the error `Unable to prepare route [forgottenpassword] for serialization. Another route has already been assigned name [forgottenpassword].`

**Expected behavior**

**Additional context**
https://laravel.com/docs/11.x/routing#named-routes:
>  Route names should always be unique.

**Comment by Kcchouette** [comment]
There are multiples non-unique route name (series, search, logout, profile_delete, profiledit, ...)

**Comment by jjaomni** [comment]
woooooooooo!!!! thanks..
