### ISSUE TITLE
when downloading via Cart or RSS NZBs do not contain any NZB information , just the path/to/nzb/5/f/c/0/5fc009c9-e21b-4960-90dd-3305756e511f.nzb.gz

### ISSUE THREAD

**Issue by nakedgoat** [NNTmux/newznab-tmux#1651]
When downloading or using the cart, via RSS the NZB's contain no NZB data. Instead they just include 
/var/www/html/storage/nzb/5/f/c/0/5fc009c9-e21b-4960-90dd-3305756e511f.nzb.gz for example.

**Comment by DariusIII** [comment]
Whast happens if you use the download button? Is the nzb ok then?

**Comment by nakedgoat** [comment]
No either way, and I checked permissions on my tmpunrar and tmpunzip, it sends the nzb, the only thing in it is the path, to the .gz which I uncompressed one and looked at while, reserving the original, and it's fine, there in there there is just an issue the getnzb function maybe, or my .tpls? I did download the Gentele dir from GitHub recenelty and copied the .tpl to the server, long story :)

**Comment by nakedgoat** [comment]
This is from a curl -v "https://hellamx.com/getnzb?id=8f3087ae-c299-4ce6-96ec-8e64f8d8ed57&apikey=<apikeyremoved>&user_id=1" -o test.nzb

 [5 bytes data]
< HTTP/2 200 
< server: nginx/1.24.0 (Ubuntu)
< content-type: text/xml; charset=UTF-8
< content-length: 91
< cache-control: no-cache, private
< date: Fri, 22 Nov 2024 01:49:57 GMT
< x-nntmux: API ERROR [200] Missing parameter
< set-cookie: XSRF-
{ [91 bytes data]
100    91  100    91    0     0    572      0 --:--:-- --:--:-- --:--:--   575
* Connection #0 to host hellamx.com left intact

**Comment by nakedgoat** [comment]
I also ran a curl, to get a test nzb , curl -v "http://127.0.0.1:8000/getnzb?id=8f3087ae-c299-4ce6-96ec-8e64f8d8ed57&apikey=<removed>"

$ cat test.nzb 
<?xml version="1.0" encoding="UTF-8"?>
<error code="200" description="Missing parameter"/>

**Comment by DrakeJones** [comment]
Hmm.

**Comment by DariusIII** [comment]
I did not have time to check what is going on, will be on it ASAP.

**Comment by DrakeJones** [comment]
Thanks.  I didn't mean to be pushy.

**Comment by nakedgoat** [comment]
Not trying to rush anyone either; just wanted to update, I did a clean install on new box and have the same error/issue.

**Comment by nakedgoat** [comment]
I fixed it, I think maybe, I mean download button works now, tested rss feed to sab, worked.
here's the mess I made of your GetNzbController.php 
https://pastebin.com/X42vqyug
here' s a quick diff -u of the two files afterwords.
https://pastebin.com/TLXviWfH

maybe it'll help to fix it?

**Comment by DariusIII** [comment]
What is your site nzb path setting?

https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/NZB.php#L68

https://github.com/NNTmux/newznab-tmux/blob/master/.env.example#L198

**Comment by nakedgoat** [comment]
/var/www/NNTmux/storage/nzb
