### ISSUE TITLE
Issue when clean install

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#221]
Doing a clean install, the value for "title" in the create xxxinfo cause it to stop and not complete the sql script.

Had to lower from 1024 to 255 for it to work as its an index.

Do I need to do anything somewhere to allow the full 1024?

Cheers

**Comment by DariusIII** [comment]
You need to run Innodb, set file format to barracuda and enable large prefix support.

**Comment by bert0901** [comment]
Thanks, it was the barracuda bit that was missing.
