### ISSUE TITLE
Previews and samples

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#223]
There is an issue where the value "$userdata.canpreview" in the pages is not being found so they are not being shown as available.

I have checked and they are being generated okay.

Could be related that in the user profile the role is blank.

Many Many thanks

**Comment by DariusIII** [comment]
I think i have, or i wanted to, remove the canpreview setting, as i think everyone should be able to preview.

Role not being there is a pure presentation, not functional issue. 

It has been fixed in dev.

**Comment by bert0901** [comment]
Many Thanks for that.
