### ISSUE TITLE
[feature req] redis monitor in tmux

### ISSUE THREAD

**Issue by Stifler6996** [NNTmux/newznab-tmux#248]
Add a pane to tmux as option for redis monitor.
Should be configurable (in the same way nmon is)

Replicate:
sudo apt-get install redis-server php-redis

sudo apt-get install rubygems ruby-dev
sudo gem install redis-stat

sudo nano /etc/redis/redis.conf
maxmemory 128mb
maxmemory-policy allkeys-lru

sudo systemctl restart redis-server.service
sudo systemctl enable redis-server.service

RUN (and default settings for tmux page) : redis-stat --verbose --server=63790

web server is optional, will output to CLI anyway. 
See: https://github.com/junegunn/redis-stat for other option.

note this is a good lightweight monitor for redis; it used built in INFO command, meaning little impact to server overall.

**Comment by DariusIII** [comment]
Feature added in commit 5d6ca10d7a94bcec60f3082f77bfafe8374b68e4
