### ISSUE TITLE
Release processing error

### ISSUE THREAD

**Issue by Boinkers** [NNTmux/newznab-tmux#367]
/var/www/NNTmux/misc/update/multiprocessing$ php releases.php
No work to do!
Process Releases -> Attempting to find complete collections.
3 collections were found to be complete. Time: 0 second(s)

Process Releases -> Calculating collection sizes (in bytes).
3 collections set to filecheck = 3(size calculated)
0 second(s)

Process Releases -> Delete collections smaller/larger than minimum size/file count from group/site setting.
Deleted 0 collections:
0 smaller than, 0 bigger than, 0 with less files than site/group settings in: 0 second(s)

Process Releases -> Create releases from complete collections.
45 Collections ready to be converted to releases.

In Regexes.php line 362:

  preg_match(): Unknown modifier 'd'

Multi-processing for releases finished in 0.7112889289856 seconds at Wed, 31 Jan 2018 11:19:11 +0200.

riaanh@ubuntu02:/var/www/NNTmux/misc/update/multiprocessing$

**Comment by DariusIII** [comment]
This issue happens if you have a.b.cores group enabled and collection regex 602 is the cause. Just disable usage of that regex.

**Comment by Boinkers** [comment]
sure it's collection regex 602 as I disabled it and still the same error?

**Comment by Boinkers** [comment]
Error with release naming regex number 1152, disabled it and working fine now.
