### ISSUE TITLE
PostProcessing.php ama error

### ISSUE THREAD

**Issue by Boinkers** [NNTmux/newznab-tmux#377]
/var/www/NNTmux/misc/update/multiprocessing$ php postprocess.php ama
No book releases to process for categories id 7010
No console releases to process.
Processing 9 games release(s).
Looking up: Treasure Adventure World (PC)
SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list (SQL: select * from `gamesinfo` where MATCH(title) AGAINST(Treasure Adventure World) limit 20)

**Comment by Boinkers** [comment]
MariaDB [nntmux]> ALTER TABLE gamesinfo ADD FULLTEXT ix_title_ft(title);
ERROR 1061 (42000): Duplicate key name 'ix_title_ft'

**Comment by DariusIII** [comment]
I have forgotten that the old index on those needs to be dropped:

```
ALTER TABLE gamesinfo DROP INDEX ix_title_ft;
ALTER TABLE gamesinfo ADD FULLTEXT ix_title_ft(title);
```

**Comment by Boinkers** [comment]
Now I get this error:
SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list (SQL: select `name`, `appid` from `steam_apps` where MATCH(name) AGAINST(*masked*) limit 20)

**Comment by DariusIII** [comment]
Same procedure as above, and i will have to take a look at those indexes again.

**Comment by Boinkers** [comment]
ALTER TABLE steam_apps DROP INDEX ix_title_ft;
ALTER TABLE steam_apps ADD FULLTEXT ix_title_ft(name);

**Comment by Boinkers** [comment]
ALTER TABLE musicinfo DROP INDEX ix_musicinfo_artist_title_ft;
ALTER TABLE musicinfo ADD FULLTEXT ix_musicinfo_artist_title_ft(artist,title);

**Comment by Boinkers** [comment]
ALTER TABLE consoleinfo DROP INDEX ix_consoleinfo_title_platform_ft;
ALTER TABLE consoleinfo ADD FULLTEXT ix_consoleinfo_title_platform_ft(title,platform);
