### ISSUE TITLE
Problem with $groups

### ISSUE THREAD

**Issue by shempe** [NNTmux/newznab-tmux#398]
Fresh Install latest dev.

/var/www/NNTmux/misc/update$ php postprocess.php  all true show

 ErrorException  : Undefined property: Blacklight\processing\PostProcess::$groups
at /var/www/NNTmux/Blacklight/processing/PostProcess.php: 283

or

var/www/NNTmux/misc/update$ php backfill.php all

Backfilling: 8 group(s) - Using compression? No
ErrorException  : Undefined property: Blacklight\Backfill::$_groups
 at /var/www/NNTmux/Blacklight/Backfill.php: 132

any idear ?

**Comment by DariusIII** [comment]
Don't use these scripts as they are not maintained. Use ones from misc/update/multiprocessing folder

**Comment by shempe** [comment]
This one ?

/var/www/NNTmux/misc/update/multiprocessing$ php backfill.php
Multi-processing started at Tue, 20 Feb 2018 15:24:27 +0100 for backfill with 55 job(s) to do using a max of 1 child process(es).

Backfilling: 1 group(s) - Using compression? No

ErrorException  : Undefined property: Blacklight\Backfill::$_groups

  at /var/www/NNTmux/Blacklight/Backfill.php: 132
  128:                 ColorCLI::doEcho(ColorCLI::header($dMessage), true);

Look like the same Problem.

**Comment by DariusIII** [comment]
Ahh, i see now where the problem comes from.

**Comment by shempe** [comment]
Yep fixed.
