### ISSUE TITLE
Update binaries safe.php

### ISSUE THREAD

**Issue by Boinkers** [NNTmux/newznab-tmux#456]
Hi,

Get the following error when updating binaries:

Received 193KB from group (alt.binaries.u-4all).
.

   ErrorException  : Undefined offset: 1

  at /var/www/NNTmux/Blacklight/Binaries.php: 822
  818:
  819:         // Loop articles, figure out files/parts.
  820:         foreach ($headers as $this->header) {
  821:             // Set up the info for inserting into parts/binaries/collections tables.
  822:             if (! isset($articles[$this->header['matches'][1]])) {
  823:
  824:                 // check whether file count should be ignored (XXX packs for now only).
  825:                 $whitelistMatch = false;
  826:                 if ($this->_ignoreFileCount($this->groupMySQL['name'], $this->header['matches'][1])) {
  827:                     $whitelistMatch = true;

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 1", "/var/www/NNTmux/Blacklight/Binaries.php")
      /var/www/NNTmux/Blacklight/Binaries.php : 822

  2   Blacklight\Binaries::storeHeaders()
      /var/www/NNTmux/Blacklight/Binaries.php : 740

**Comment by DariusIII** [comment]
That error pops out because there is no match at all for that group. Will look into the issue.

**Comment by DariusIII** [comment]
Fixed in commit 641c5822b8db4f2a9dca9c478b5b1546e3b18fcf
