### ISSUE TITLE
releases.php error

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#472]
when I run:
`php /var/www/NNTmux/misc/update/multiprocessing/releases.php`

I get the following error:
`
   ErrorException  : connection error

  at /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php: 76
  72:         try {
  73:             $con = new \Pdo($dsn);
  74:         } catch (\PDOException $exception) {
  75:             if (!$suppress_error && !$this->silence_connection_warning) {
  76:                 trigger_error('connection error', E_USER_WARNING);
  77:             }
  78:
  79:             throw new ConnectionException($exception->getMessage());
  80:         }
  81:

  Exception trace:

  1   trigger_error("connection error")
      /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php : 76

  2   Foolz\SphinxQL\Drivers\Pdo\Connection::connect()
      /var/www/NNTmux/vendor/foolz/sphinxql-query-builder/src/Drivers/ConnectionBase.php : 153

  Please use the argument -v to see more details.

`

**Comment by DariusIII** [comment]
You don't have sphinx installed and/or running. Sphinx is mandatory for NNTmux.

**Comment by blimeybloke** [comment]
hah, you beat me to it.  I was just about to come back here and edit the post saying that.  Once I installed sphinx, all is working again.
