### ISSUE TITLE
Bug or doc needed

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#473]
`
/var/www/NNTmux/misc/update/tmux # php start.php
Info: Starting the tmux server and monitor script.
Error:
Your database is not up to date. Reported patch levels
   Db: 343
file: 344
Please update.
 php /var/www/NNTmux/./tmux nntmux:db

   RuntimeException  :
Your database is not up to date. Reported patch levels
   Db: 343
file: 344
Please update.
 php /var/www/NNTmux/./tmux nntmux:db`

I have tried running that and I get not found.  I then edited the line to be:
php /var/www/NNTmux/misc/update/tmux nntmux:db
It then comes right back to the command prompt but did not update anything.

**Comment by DariusIII** [comment]
Hah. I did not edit that message. What you should do is : 

`php artisan nntmux:all  `

from root of your indexer

**Comment by blimeybloke** [comment]
You sir, are a genius!

**Comment by DariusIII** [comment]
I am waiting for next issue. As you are on dev, and i have some weird things going on.
