### ISSUE TITLE
update_releases.php

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#474]
Sorry for all the questions today.  I am just trying to get the new dev going.  It appears I am missing update_releases.php

`/var/www/NNTmux/misc/update # ls
backfill.php        match_prefiles.php  postprocess.php  tmux
decrypt_hashes.php  multiprocessing     README.txt       update_binaries.php
`

I normally run, update_binaries, then update_releases, then all the postprocess stuff.

**Comment by DariusIII** [comment]
You are not missing them, they do not exist anymore.

**Comment by blimeybloke** [comment]
So what is the proper method now?
update_binaries, then in multiprocessing, releases.php, and then postprocess?

TIA

**Comment by DariusIII** [comment]
Proper method is to use tmux, and not run things manually.

To start tmux:

`php artisan tmux-ui:start`

To stop tmux without killing the tmux session:

`php artisan tmux-ui:stop false`

and to stop it and kill active tmux session:

`php artisan tmux-ui:stop true`
