### ISSUE TITLE
Page expired

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#555]
Just done a clean install of dev branch. Followed all instructions as in wiki.

Issue I have is that after login, I get the following error with debug on.

Done the php artisan nntmux:install .

/var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#70

Page expired at top of the page.

Any advice?

Many Thanks

**Comment by bert0901** [comment]
Have resolved it.

Had to add domain name of server to both APP_URL and SESSION_DOMAIN

Might need to change wiki for this info.

Thanks for all the good work.

**Comment by DariusIII** [comment]
That means that session has not been properly started and that you have csrf_token mismatch.

As nntmux is using laravel's sessions and routing, also uses the csrf_token (Cross Site Request Forgery prevention token) to validate user session and requests (in forms).

**Comment by bert0901** [comment]
Cheers for the reply.

I better get reading about laravel.

Thanks for developing all this.
