### ISSUE TITLE
[dev-controllers] Incorrect category results displayed

### ISSUE THREAD

**Issue by nightah** [NNTmux/newznab-tmux#582]
The following categories appear to be showing the same data as [All Categories](https://example.com/browse/all) as opposed to their respective top level categories data.

The Music categories below also all appear as Home / Music / All, which I believe is implying they're all the same category.

- [Console / All](https://example.com/browse/console/Console)
- [Music / Audiobook](https://example.com/browse/music/Audiobook)
- [Music / Foreign](https://example.com/browse/music/Foreign)
- [Music / Lossless](https://example.com/browse/music/Lossless)
- [Music / MP3](https://example.com/browse/music/MP3)
- [PC / All](https://example.com/browse/pc/PC)
- [XXX / All](https://example.com/browse/xxx/XXX)
- [Books / All](https://example.com/browse/books/Books)

**Comment by DariusIII** [comment]
This should have been fixed now.

**Comment by nightah** [comment]
Correct this was fixed by 647ccc06ca9ba357b808214109795b766009a73e.
