### ISSUE TITLE
[dev-controllers] Check all box in Gentele

### ISSUE THREAD

**Issue by nightah** [NNTmux/newznab-tmux#585]
Only the Console and Games templates for Gentele have the "Check All" box in the Covers view.

- Should this not be available for all Cover views
- The button doesn't work in Cover view mode when selected none of the other NZBs on the page are selected

**Comment by DariusIII** [comment]
Select all on cover views is, for me, a useless feature, as who in clear state of mind would select all of the releases presented on a page.
