### ISSUE TITLE
Dev clean install wont connect to nntp server

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#609]
Just done a clean install. Tried to do a pull of headers for a group.

It just sits there and times out at the stage of saying "Getting first/last for all your active groups."

The shortgroup doesn't get updated or any values in the group tables.

Any advice welcome.

many Thanks

**Comment by DariusIII** [comment]
Check logs for any possible hint.

**Comment by DariusIII** [comment]
Stupid question, but have you copied .env.example to .env and edited that file?

**Comment by bert0901** [comment]
Yep done all that.

Tried both ssl and non ssl. Tried 2 different providers.

APP_NAME=NNTmux
APP_ENV=local
APP_DEBUG=true

Set those to local and debug.

Its when I use "complete threaded update" same message.

When I use "Simple" just loops to end without any headers. That's why tried to run the update_groups.php so that would work as it seems to rely on short_groups values.

**Comment by bert0901** [comment]
Just used the old test_nntp_server.php file to see if getting a connection.

php test_nntp_server.php alt.binaries.teevee 595751142
Array
(
    [group] => alt.binaries.teevee
    [first] => 2
    [last] => 1466060586
    [count] => 1466060585
)

So looks like the .env file is all okay as getting results.

**Comment by bert0901** [comment]
Gone back before updates few days ago and all working fine. So must be something around that time.

**Comment by bert0901** [comment]
Sorry, before the blacklight\nntp file was changed

**Comment by bert0901** [comment]
Been looking into this issue, and resetting the "Fix wrong size in substr check in NNTP class " push to the original value seems to solve the issue.

**Comment by bert0901** [comment]
Thanks for resolving that
