### ISSUE TITLE
sphinx error when generating releases

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#610]
When I try to update release to generate them, sphinx seems to have an issue.

php create_se_tables.php 0 9312
This works fine

php populate_rt_indexes.php releases_rt
This generates the following :

 Exception trace:

  1   trigger_error("connection error")
      /var/www/zenplus/vendor/foolz/sphinxql-query-builder/src/Drivers/Pdo/Connection.php:76

  2   Foolz\SphinxQL\Drivers\Pdo\Connection::connect()
      /var/www/zenplus/vendor/foolz/sphinxql-query-builder/src/Drivers/ConnectionBase.php:153

Had a look and it is trying to connect through a different port :
mysql:host=127.0.0.1;port=9306;

Where do I configure sphinx ports?

Many Thanks

**Comment by bert0901** [comment]
Think found issue. On ubuntu need to make sure that /run/sphinxsearch folder exists.

ran searchd and showed that /run/sphinxsearch does not exist

May want to add this to install instructions.

Thanks

**Comment by DariusIII** [comment]
I never had to configure anthing remotely related to /run/sphinxsearch folder.

Have you compiled sphinxsearch on your own?

**Comment by bert0901** [comment]
Nope, it was straight from your instructions. It looks like it is a official bug in the release.

In that link shows you what to do to rectify the issue.

Just thought it may be useful if anybody else has that issue if they do a clean install.

Many Thanks
