### ISSUE TITLE
artisan install not finding folder "vendor"

### ISSUE THREAD

**Issue by raysv** [NNTmux/newznab-tmux#619]
Hi, trying to install nntmux With artisan. 
Failing with the error that it can't load some files due to the fact that folder "vendor" dosn't exit.

**Comment by DariusIII** [comment]
You need to run composer install first, as stated in [ubuntu install guide](https://github.com/NNTmux/newznab-tmux/wiki/Ubuntu-Install-guide) and [composer install guide](https://github.com/NNTmux/newznab-tmux/wiki/Installing-Composer).

Then run the artisan command.

**Comment by raysv** [comment]
Great, that seem to do the trick. 

Site seems to be up aswell, allthough i'm getting the login screen, when entering password / username it only jumps immidiatly to a blank white screen, with a "Page expired" error... hum hum

**Comment by DariusIII** [comment]
Check site cookies, session and cache. X-CSRF-Token is most likely not set, so it fails validation.

**Comment by raysv** [comment]
Don't find anything i can see is wrong with the cookies, however not sure what the correct way should be in this case :)

**Comment by raysv** [comment]
Seems like its happening for all pages as soon as i "submit" anything.

**Comment by DariusIII** [comment]
What is your session store set at?
If it is file, you need to fix permissions on  `storage/framework/` folder.

**Comment by raysv** [comment]
The session driver is file, secure cookie = false, session encrypt = false 
Storage/framework = 777

**Comment by DariusIII** [comment]
When you check cookies, do you have the CSRF_Token one?

**Comment by raysv** [comment]
where do i see that?

**Comment by raysv** [comment]
i can confirm that the site is working if i use "localhost" as url, but using ip or any other dns name it gets the page expire. So guess its the CSRF_Token thing that is the problem. Any suggestion on how to fix that?
