### ISSUE TITLE
Blank searchname

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#621]
Have an issue with quite a few releases having blank searchname.

E.g.

Sesame Street [01/15] - "Sesame.Street.S48E28.Oscar.the.Kind.720p.AMZN.WEB-DL.DDP2.0.H.264-monkee.nfo" yEnc

Jim Jefferies [09/12] - "The.Jim.Jefferies.Show.S02E09.Why.Scared.White.People.Keep.Calling.911.1080p.CC.WEB-DL.AAC2.0.x264-monkee.rar" yEnc

John Oliver [12/16] - "Last.Week.Tonight.with.John.Oliver.S05E11.720p.WEB-DL.AAC2.0.H.264-doosh.rar" yEnc

They all seem to have similar format before the "[12/16]" part.

Is this a regex issue?

Many Thanks

**Comment by DariusIII** [comment]
I am still trying to find out why is this happening.

**Comment by bert0901** [comment]
It seems to be something to do with the cleaned name in ProcessRelease.php.

For some reason the $cleanedName is null

I added this just so it would fill in something before the insert. I know not pretty but it temporary fix :

                    if ($cleanedName === NULL) {
                        $cleanedName=$cleanRelName;
                    }
                    $releaseID = Release::insertRelease(…….

Hope this helps in diagnosis

**Comment by DariusIII** [comment]
Thanks, 
will have a look tonight.

**Comment by bert0901** [comment]
Many Thanks, that resolved the issue. Ran the test-releasecleaner.php file and it renamed all the blanks.
