### ISSUE TITLE
New install - update binaries not working / doing anything

### ISSUE THREAD

**Issue by raysv** [NNTmux/newznab-tmux#622]
Hi, 
Fresh installed NNtmux, but update_binaries will not run.

If i use tmux, it just says "Getting first/last for all your active groups" and there it stays. 

If i try and run the update_binaries.php manually. 

It shows the information of what group, how many headers, and how many in cue, drops to the line where it says Getting articles... but nothing more happends. 

Not able to find any errors anywhere.... Open for suggestions :D

**Comment by bert0901** [comment]
I had similar issue. #609 

If you change line 1062 in Blacklight/NNTP.php  to:

 if (substr($buffer, -2) === ".\r\n") {

Basically change the -3 to -2.

That solved it for me

**Comment by raysv** [comment]
thats not it :( Already -2 here

**Comment by raysv** [comment]
Thanks :) that seems to do the trick. 

Any other bugs you have encountered? seems like the list is long, because now update releases here is doing nothing... and getting db erros it seems when i try to view the tables... but no errors is showing when inserting stuff. The monitor says 0 on every thing.... damn, this was buggy to be from "master"
