### ISSUE TITLE
Send to downloader.

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#623]
When I click on send to downloader button, nothing seems to happen on any of the pages. 

Had a look a chrome developer details and it is showing this error.

http://*********.comsendtoqueue/add398ff-acf1-4f90-b1d8-1a29c740b342

No "/" between the domain name and the "sendtoqueue".

Any advice welcome.

**Comment by DariusIII** [comment]
What theme do you use?
add{guid} is not used anywhere in any of the themes, NNTmux uses guid{guid}.
If its your custom theme, it is your responsibility to fix it to match current code.

**Comment by bert0901** [comment]
This is on the standard Gentele theme on a clean install.

/sendtoqueue/319cfd75-eafe-4a02-91df-651bf004cd3b

Download works so know it exists.

Send to queue doesn't and just gives a 404 error
