### ISSUE TITLE
Help with themes

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#624]
Just want to pick your brains on themes.

What I can see is that the themes are in the /resources/views/themes

But the css and js stuff is in /public/assets/ 

I have a self designed theme that I use where all the files are in single folder. I want to use this if possible.

The issue is the paths, as they point to the public folder

 
{{Html::style("{$smarty.const.WWW_ASSETS}/{$theme}/dist/css/AdminLTE.css")}} 

Want to keep the assets as normal, but be able to redirect to the theme folder for specific changes, like the css and js location if required.

What would be the syntax for the above to be in the same folder as the themes file?

Any help much appreciated.

**Comment by DariusIII** [comment]
As far as i know, js and css need to be in public folder, accessible by browser.

**Comment by bert0901** [comment]
Thanks for response.

Just trying to work out a way of creating the theme without changing too much of the original setup.

Was doing a separate repo for the them, had to structure it so it doesn't conflict with the original git pull.

Again, thanks for the response.
