### ISSUE TITLE
Part repairs large

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#625]
When doing a few days backfill, I seem to be getting lots of repairs appearing.
The repair runs when getting new headers only.

Is it possible, to run the repairs loop after the backfill has run?
Or put into a separate tmux screen to run continuously?

What would be the downside of doing either of these?

Cheers

**Comment by DariusIII** [comment]
Partrepair works in a way that it fetches headers, and then applies parts from partrepair table (missed_parts). It cannot be run continuosly. 

If you have many parts in missed_parts table(s) i would rather disable partrepair for backfill.

**Comment by bert0901** [comment]
Cheer for the response. That's what I thought would be the case.
