### ISSUE TITLE
Clean install, matchprefiles doing nothing.

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#638]
Sorry to be always bad news guy.

Just done a clean install from dev, and the matching from the predb is doing nothing.

It used to read all the filenames and things, now it just says 'nothing to do'.

Has this changed in the past 2 weeks in the way it does this?

Cheers

**Comment by DariusIII** [comment]
Yeah, it has changed, will have a look into it.

**Comment by DariusIII** [comment]
What script do you use?

**Comment by bert0901** [comment]
I have used the one in Tmux, also tried to run manually from the update folder to do a "all".

**Comment by bert0901** [comment]
Cheers last update solved the issue.

**Comment by DariusIII** [comment]
Great.
