### ISSUE TITLE
No release when using groups and not multigroup.

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#698]
Sorry didn't know how to reopen previous issue. #658 

It seems only to be happening when using non multigroup setup. 

Have 3 groups enabled. Does a single process release only. Does nothing as all values are 0 as shown in previous issue.

Its like the group isn't being passed to this process. Added a echo to see what group it was working on and its blank.

Any ideas?

Many thanks

**Comment by DariusIII** [comment]
Nowadays multigroup is a must, so i am closing this issue.
