### ISSUE TITLE
New install - web just showing php code

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#724]
I have tried both dev and stable with same results.

I am redoing my install "again" as I like to keep current for me and my mates. I decided to blow my install away and redo from scratch. Using Ubuntu 16.04 I followed the guide to a T. Everything went very smooth till I was ready to goto the actual site to finalise setup. I get this on the screen and nothing else:

**********
require_once dirname(DIR).DIRECTORY_SEPARATOR.'resources/views/themes/smarty.php';

$kernel = $app->make(\Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle($request = \Illuminate\Http\Request::capture()); $response->send(); $kernel->terminate($request, $response);
**********

I have tried 2 installs, first was dev, and second was stable, both with same results.

**Comment by blimeybloke** [comment]
Adding to this.  I just looked and it is echoing /var/www/NNTmux/public/index.php

**Comment by DariusIII** [comment]
As with previous issue (https://github.com/NNTmux/newznab-tmux/issues/700), this has something to do with misconfigured web server.

**Comment by blimeybloke** [comment]
It was a brand new server ubuntu 16.04.  I followed the guide exactly.  I am using apache, but will attempt to use nginx to see if the issue still persists.  Like I said though, a brand new server, well fresh install after a format.

**Comment by DariusIII** [comment]
Have you installed all the extensions required?

**Comment by blimeybloke** [comment]
I followed the guide exactly.  I just got home from the market so restored the VM from right before I did apache.  I will attempt nginx and will let you know in about 15 minutes

**Comment by blimeybloke** [comment]
the short code I will test in a few.  I just found 4 extensions not installed:
apt-get install zip unzip php7.2-zip php7.2-intl

**Comment by blimeybloke** [comment]
Same issue using apache2.  I have turned short_open_tags = On and then those 4 extensions and still get the php code, not any webpage.  :(

**Comment by blimeybloke** [comment]
going to attempt this again but this time I will try ubuntu 18 instead of 16.

**Comment by blimeybloke** [comment]
I think I have this tracked down, it looks like apache config is not loading the php modules.  Kind of strange on a new install.  Now I can't seem to find httpd.conf even using locate.  Where is httpd.conf on ubuntu?  Its like the file never was created.

**Comment by blimeybloke** [comment]
And fixed...

so here is what I did:
apt-get remove libapache2-mod-php7.2 ; apt-get purge libapache2-mod-php7.2; apt-get install libapache2-mod-php7.2

I then had to redo my php.ini configs but all was working.  It looks like the php modules are never being loaded into the config.  I verified this by doing:  a2query -m php7.2

Initially there was nothing being returned but after I ran those 3 things, I now see:
php7.2 (enabled by maintainer script)

**Comment by blimeybloke** [comment]
Just when I thought I was out of the woods, I get pulled back in.  Site works but now when I goto log in I get:
419
Sorry, your session has expired. Please refresh and try again.

**Comment by blimeybloke** [comment]
Here is the error from error log:
PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php:767\nStack trace:\n#0 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('view')\n#1 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('view')\n#2 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('view', Array)\n#3 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('view', Array)\n#4 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(1210): Illuminate\\Foundation\\Application->make('view')\n#5 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(161): Illuminate\\Container\\Container->offsetGet('view')\n#6 /var/www/NNTmux/vendor/laravel/frame in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767, referer: http://rikers3.firefoxbackup.com/login

**Comment by blimeybloke** [comment]
Here is the error log:

PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php:767\nStack trace:\n#0 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('view')\n#1 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('view')\n#2 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('view', Array)\n#3 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('view', Array)\n#4 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(1210): Illuminate\\Foundation\\Application->make('view')\n#5 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(161): Illuminate\\Container\\Container->offsetGet('view')\n#6 /var/www/NNTmux/vendor/laravel/frame in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767,

**Comment by ashmck73** [comment]
Hello Blimeybloke - did you fix this error. I followed the install word for word and I am getting the same error. The site loads up to a login screen and when I put in a username and password I immediately get a 419 session expired page come up. I'be been through the error-log files but doesn't show any problems.. 

Hoping you have progressed with this and can point me in the right direction.

**Comment by DariusIII** [comment]
I reckon you are on master. This has been fixed in dev and will be released later today.

**Comment by Sweepr** [comment]
I had the exact same issue, and somehow i managed to get past the 419 error by adding https:// infront of the URL, it has something to do with CSRF token which isn't getting set properly in certain browsers.

CSRF tokens mismatch
This error message is caused by privacy extensions. If you are running any privacy extensions such as Ghostery or Privacy Badger, make sure to add todoist.com as a trusted website.

https://get.todoist.help/hc/en-us/articles/208951085-CSRF-token-error-messages

**Comment by DariusIII** [comment]
I have pushed a new release that among other things addresses this issue.
