### ISSUE TITLE
Api error when downloading

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#735]
Setting up my sonarr system, I noticed it was not grabbing any nzbs.  I then tested it manually, and can confirm there is an issue.  The format I used to test manually is:  

domain/api/v2/getnzb?id=858c65fb-520d-4256-a63b-b02cd0d78da4&api_token=my_api_key

When I looked at the error log I saw:  Response header name 'X-DNZB-NFO ' contains invalid characters, aborting request

Is this a setting or a bug?

**Comment by DariusIII** [comment]
As far as i know, no software yet supports NNTmux version 2 api, just v1.

**Comment by blimeybloke** [comment]
Thanks for the response.  I get the same thing though, when I try v1:
/api/v1/api?t=get&id=858c65fb-520d-4256-a63b-b02cd0d78da4&apikey=my_api_key

And then it redirects me to: getnzb?i=1&r=my_api_key&id=858c65fb-520d-4256-a63b-b02cd0d78da4

**Comment by DariusIII** [comment]
Because that is how it works, it redirects you to getnzb page. I am using nzbhydra and never had an issue with getting nzbs. You must be doing something wrong.

**Comment by blimeybloke** [comment]
I probably am.  I will isolate my server in hydra and run a test with that.  Not sure what I could be doing wrong but probably am.  I will update.

**Comment by blimeybloke** [comment]
same.  I click the download icon in hydra and it goes error 500 on my box.  Permission issue?  Not sure why the error log says what it does about header name though.

**Comment by DariusIII** [comment]
Edit .env, enable debugging and try again.

**Comment by DariusIII** [comment]
Just tried getting the nzb through nzbhydra and it works without an issue.

**Comment by blimeybloke** [comment]
Strange, I get error 500 on the server so debug is not helping.  Only thing I see in /var/log/apache/error.log is:  Response header name 'X-DNZB-NFO ' contains invalid characters, aborting request

Should I check another log now that debug is on?

**Comment by blimeybloke** [comment]
<img width="361" alt="muxi" src="https://user-images.githubusercontent.com/20652035/46380088-03124a80-c66f-11e8-85f4-fcaef4c82c48.png">

That is what I am clicking on in Hydra.

**Comment by DariusIII** [comment]
Even if the nzb does not exist you should not receive 500 error, but specific message that nzb does not exist.

**Comment by blimeybloke** [comment]
I guess I didn't figure it out then.  It works if there is an nzb file for the release but if there is none/missing it gives the error 500 and the only thing in the log is what I wrote earlier.

**Comment by DariusIII** [comment]
You should receive the following error:

https://github.com/NNTmux/newznab-tmux/blob/master/app/Http/Controllers/GetNzbController.php#L104

**Comment by blimeybloke** [comment]
yep, but I am seeing line 135

**Comment by DariusIII** [comment]
Ahh, damn, dual /, aka //. WIll fix that.

**Comment by blimeybloke** [comment]
nice, glad I could help :)  Let me know and I will do a pull and report back

**Comment by DariusIII** [comment]
Unfortunately, thing i mentioned above is not a real problem, something else is. 
And i can't figure out what. I need to do more extensive testing to find a cause.

**Comment by DariusIII** [comment]
Fun fact, release that is failing in Chrome, downloads properly in Firefox.

**Comment by blimeybloke** [comment]
No problem.  Its not that important as others download just fine.  I did test the same one that fails in Chrome with FF and same:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

**Comment by DariusIII** [comment]
Can you send me the link to bad release by email so i can check?
