### ISSUE TITLE
Unable to add admin user! NNTmux installation failed. Fix reported problems and try again

### ISSUE THREAD

**Issue by zcworld** [NNTmux/newznab-tmux#736]
OS ubuntu 16.04 LTS
mariadb 10.3

Database updated successfully
Settings table updated successfully
Adding admin user to database
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'rate_limit' cannot be null (SQL: insert into `users` (`username`, `password`, `email`, `host`, `roles_id`, `api_token`, `invites`, `invitedby`, `userseed`, `notes`, `rate_limit`, `updated_at`, `created_at`) values (admin, $argon2i$v=19$m=1024,t=2,p=2$MmgxeGt2MGF6ZWFGY3g0UA$S42ltYvylJ9p3ZYM0YFtqkryY1/lMhmF+4yO/N7HLE0, admin@admin.com, , 2, f88e4357c486f1df56c20806f6badc9a, , NULL, 2d04050dcd4295d89fc2374b67af4637, , , 2018-10-07 10:54:06, 2018-10-07 10:54:06))Unable to add admin user!
NNTmux installation failed. Fix reported problems and try again

**Comment by DariusIII** [comment]
What branch and version you are using?

**Comment by zcworld** [comment]
using the lastest branch
but i think i got it fix now

deleted /var/lib/mysql 
did a mysql_install_db than it worked
