### ISSUE TITLE
Many releases not being renamed, special configuration needed?

### ISSUE THREAD

**Issue by gkoh** [NNTmux/newznab-tmux#757]
Hello, thanks for making this.
I've had an NNTmux install running off master (092987c9) for a few days and started comparing with releases with tabula-rasa.

I've noticed quite a number of releases are being properly renamed there, but not on my install.
Everything appears to be working fine, some releases are being properly renamed, but not all.

Is there some special magic that is needed to get the awesome results that tabula-rasa produces?

Note: I can see the release being created with the hashed name, but it doesn't appear to find any predb matches, so never renames it.

**Comment by DariusIII** [comment]
I have pushed a new version (https://github.com/NNTmux/newznab-tmux/releases/tag/v1.0.10) . Maybe try that and see what happens, as there are changes related to renaming in there.

**Comment by gkoh** [comment]
OK, I've just updated. Everything seems to running well, but still no releases.

If I manually run match_prefiles, I get this:
```
# php match_prefiles.php full show

Match PreFiles full Started at 2018-10-26 21:02:05
Matching predb filename to cleaned release_files.name.

4,062 releases to process.

Renamed 0 releases in 5 seconds.
```

And the number of releases to process just keeps increasing, it seems to rarely find anything to rename.

**Comment by DariusIII** [comment]
Your predb table needs to be populated with many, many rows for scripts to rename stuff properly.

**Comment by gkoh** [comment]
OK, that makes sense, it's only been running for a few days.
Is the daily import from nzedb still supported? Would it make a difference?

**Comment by DariusIII** [comment]
It is but it's broken in NNTmux ATM.

**Comment by gkoh** [comment]
For reference, I have 6900 entries in my predb table. I'm guessing that's not considered much.

**Comment by gkoh** [comment]
I've been looking through the NameFixer code.
Is predb matching via hash still supported?
The primary entry point looks like parseTitles() (which calls matchPredbHash()), but there doesn't seem to be any code that calls it.

**Comment by gkoh** [comment]
Closing, not sure if there's anything more I can do to improve the renames in my configuration. Thanks for the help.

**Comment by gkoh** [comment]
For anyone who happens upon this in future, I found my issue after poking about for a while.
Postprocess was crashing out parsing mediainfo output, I had installed some crappy version (v0.7.x).
So some releases were being processed, until it hit media processing stage.

When the guide tells you to get mediainfo from the project site, do it!
(Currently running mediainfo v18.0.x, no more errors)
