### ISSUE TITLE
Releases not showing up on site. Fresh install. Debian Stretch

### ISSUE THREAD

**Issue by DemetryRomanowski** [NNTmux/newznab-tmux#802]
Under site stats I see a release qty. 
Eg:
```
Category                  | Releases
Other > Hashed            | 30
Other > Misc              | 13
TV > Foreign              | 8

```

But looking anywhere else I do not see any releases. etc...

I am viewing under an admin account, and the server is not public (yet) but I have it set as a production server in .env

Any ideas? 
Thanks!

**Comment by DariusIII** [comment]
What is the version of PHP used? 
Is Sphinx installed and running? 
What is your caching setting in .env file?

**Comment by DemetryRomanowski** [comment]
PHP 7.2.12-1
Sphinx is running
Im not sure what you mean by caching settings... please elaborate :)

CACHE_DRIVER=file

**Comment by DemetryRomanowski** [comment]
I re ran the sphinx install for the fun of it and when I run 
```php populate_rt_indexes.php releases_rt```

It outputs
```
 Starting to populate sphinx RT index releases_rt with 52 releases.
 connection error ```
Could this be the root cause of my issue ?

**Comment by DariusIII** [comment]
It definitely is. Check in your database if SPHINX engine is enabled by logging in and typing:

`show engines;`

**Comment by DemetryRomanowski** [comment]
I have done so it is listed in the database as SPHINX.

**Comment by DariusIII** [comment]
Since the connection is refused, then the port must be wrong. Have you followed the instructions from wiki?

**Comment by DemetryRomanowski** [comment]
Yes I have followed the Wiki

**Comment by DariusIII** [comment]
Then check logs to find reasons connection is being refused, enabling debugging could also help.

**Comment by DemetryRomanowski** [comment]
I will do that now, any ideas what logs I should look at ?

Using:
```
lsof -Pnl +M -i4 
```
I dont see sphinx (idk if I should be) 
but 
mysql is on 3306
php7.2 is on 9017 and 21473



I'm not sure what service I should be pointing to when using 
```
php create_se_tables.php 0 9312
```

**Comment by DariusIII** [comment]
That command creates releases_se table and connects it to sphinxQl instance running on port 9312.

**Comment by DemetryRomanowski** [comment]
Ok I see...

**Comment by DemetryRomanowski** [comment]
So I got ``` php populate_rt_indexes.php releases_rt ``` to work by running

```
sudo chmod 777 /var/lib/sphinxsearch
```

I came to that conclusion by trying to run 
```searchd```

This solved my issue, closing!. 

Thanks for you all your help.
