### ISSUE TITLE
Use of undefined constant PASSWORD_ARGON2I

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#825]
**Describe the bug**

I can't get passed the password hashing (argon2) part, i got this error message:?

php artisan nntmux:install

 Are you sure you want to install NNTmux? This will wipe your database!! (yes/no) [no]:
 > yes

Migrating tables and seeding them with initial data
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_01_07_073615_create_tagged_table
Migrated:  2014_01_07_073615_create_tagged_table
Migrating: 2014_01_07_073615_create_tags_table
Migrated:  2014_01_07_073615_create_tags_table
Migrating: 2014_02_01_311070_create_firewall_table
Migrated:  2014_02_01_311070_create_firewall_table
Migrating: 2016_06_29_073615_create_tag_groups_table
Migrated:  2016_06_29_073615_create_tag_groups_table
Migrating: 2016_06_29_073615_update_tags_table
Migrated:  2016_06_29_073615_update_tags_table
Migrating: 2017_11_29_223842_create_countries_table
Migrated:  2017_11_29_223842_create_countries_table
Migrating: 2018_01_16_195548_create_users_table
Migrated:  2018_01_16_195548_create_users_table
Migrating: 2018_01_17_150719_create_permission_tables
Migrated:  2018_01_17_150719_create_permission_tables
Migrating: 2018_01_17_154034_create_categories_table
Migrated:  2018_01_17_154034_create_categories_table
Migrating: 2018_01_18_101314_create_category_regexes_table
Migrated:  2018_01_18_101314_create_category_regexes_table
Migrating: 2018_01_18_102213_create_collection_regexes_table
Migrated:  2018_01_18_102213_create_collection_regexes_table
Migrating: 2018_01_18_102716_create_binaryblacklist_table
Migrated:  2018_01_18_102716_create_binaryblacklist_table
Migrating: 2018_01_18_103104_create_content_table
Migrated:  2018_01_18_103104_create_content_table
Migrating: 2018_01_18_103520_create_forumpost_table
Migrated:  2018_01_18_103520_create_forumpost_table
Migrating: 2018_01_18_103816_create_genres_table
Migrated:  2018_01_18_103816_create_genres_table
Migrating: 2018_01_18_104345_create_groups_table
Migrated:  2018_01_18_104345_create_groups_table
Migrating: 2018_01_18_104710_create_menu_table
Migrated:  2018_01_18_104710_create_menu_table
Migrating: 2018_01_18_105455_create_release_naming_regexes_table
Migrated:  2018_01_18_105455_create_release_naming_regexes_table
Migrating: 2018_01_18_105834_create_settings_table
Migrated:  2018_01_18_105834_create_settings_table
Migrating: 2018_01_20_195500_create_collections_table
Migrated:  2018_01_20_195500_create_collections_table
Migrating: 2018_01_20_195528_create_releases_table
Migrated:  2018_01_20_195528_create_releases_table
Migrating: 2018_01_20_195604_create_anidb_episodes_table
Migrated:  2018_01_20_195604_create_anidb_episodes_table
Migrating: 2018_01_20_195615_create_anidb_info_table
Migrated:  2018_01_20_195615_create_anidb_info_table
Migrating: 2018_01_20_195624_create_anidb_titles_table
Migrated:  2018_01_20_195624_create_anidb_titles_table
Migrating: 2018_01_20_195636_create_audio_data_table
Migrated:  2018_01_20_195636_create_audio_data_table
Migrating: 2018_01_20_195648_create_binaries_table
Migrated:  2018_01_20_195648_create_binaries_table
Migrating: 2018_01_20_195703_create_bookinfo_table
Migrated:  2018_01_20_195703_create_bookinfo_table
Migrating: 2018_01_20_195716_create_consoleinfo_table
Migrated:  2018_01_20_195716_create_consoleinfo_table
Migrating: 2018_01_20_195728_create_dnzb_failures_table
Migrated:  2018_01_20_195728_create_dnzb_failures_table
Migrating: 2018_01_20_195739_create_gamesinfo_table
Migrated:  2018_01_20_195739_create_gamesinfo_table
Migrating: 2018_01_20_195752_create_invitations_table
Migrated:  2018_01_20_195752_create_invitations_table
Migrating: 2018_01_20_195801_create_logging_table
Migrated:  2018_01_20_195801_create_logging_table
Migrating: 2018_01_20_195812_create_missed_parts_table
Migrated:  2018_01_20_195812_create_missed_parts_table
Migrating: 2018_01_20_195822_create_movieinfo_table
Migrated:  2018_01_20_195822_create_movieinfo_table
Migrating: 2018_01_20_195832_create_musicinfo_table
Migrated:  2018_01_20_195832_create_musicinfo_table
Migrating: 2018_01_20_195846_create_multigroup_collections_table
Migrated:  2018_01_20_195846_create_multigroup_collections_table
Migrating: 2018_01_20_195858_create_multigroup_posters_table
Migrated:  2018_01_20_195858_create_multigroup_posters_table
Migrating: 2018_01_20_195915_create_par_hashes_table
Migrated:  2018_01_20_195915_create_par_hashes_table
Migrating: 2018_01_20_195925_create_parts_table
Migrated:  2018_01_20_195925_create_parts_table
Migrating: 2018_01_20_195934_create_predb_table
Migrated:  2018_01_20_195934_create_predb_table
Migrating: 2018_01_20_195946_create_predb_hashes_table
Migrated:  2018_01_20_195946_create_predb_hashes_table
Migrating: 2018_01_20_195954_create_predb_imports_table
Migrated:  2018_01_20_195954_create_predb_imports_table
Migrating: 2018_01_20_200005_create_release_comments_table
Migrated:  2018_01_20_200005_create_release_comments_table
Migrating: 2018_01_20_200018_create_releases_groups_table
Migrated:  2018_01_20_200018_create_releases_groups_table
Migrating: 2018_01_20_200030_create_release_regexes_table
Migrated:  2018_01_20_200030_create_release_regexes_table
Migrating: 2018_01_20_200038_create_release_unique_table
Migrated:  2018_01_20_200038_create_release_unique_table
Migrating: 2018_01_20_200046_create_releaseextrafull_table
Migrated:  2018_01_20_200046_create_releaseextrafull_table
Migrating: 2018_01_20_200056_create_release_files_table
Migrated:  2018_01_20_200056_create_release_files_table
Migrating: 2018_01_20_200104_create_release_nfos_table
Migrated:  2018_01_20_200104_create_release_nfos_table
Migrating: 2018_01_20_200124_create_release_subtitles_table
Migrated:  2018_01_20_200124_create_release_subtitles_table
Migrating: 2018_01_20_200135_create_sharing_table
Migrated:  2018_01_20_200135_create_sharing_table
Migrating: 2018_01_20_200142_create_sharing_sites_table
Migrated:  2018_01_20_200142_create_sharing_sites_table
Migrating: 2018_01_20_200151_create_short_groups_table
Migrated:  2018_01_20_200151_create_short_groups_table
Migrating: 2018_01_20_200200_create_steam_apps_table
Migrated:  2018_01_20_200200_create_steam_apps_table
Migrating: 2018_01_20_200211_create_tv_episodes_table
Migrated:  2018_01_20_200211_create_tv_episodes_table
Migrating: 2018_01_20_200218_create_tv_info_table
Migrated:  2018_01_20_200218_create_tv_info_table
Migrating: 2018_01_20_200237_create_users_releases_table
Migrated:  2018_01_20_200237_create_users_releases_table
Migrating: 2018_01_20_200248_create_user_downloads_table
Migrated:  2018_01_20_200248_create_user_downloads_table
Migrating: 2018_01_20_200318_create_user_movies_table
Migrated:  2018_01_20_200318_create_user_movies_table
Migrating: 2018_01_20_200328_create_user_requests_table
Migrated:  2018_01_20_200328_create_user_requests_table
Migrating: 2018_01_20_200336_create_user_series_table
Migrated:  2018_01_20_200336_create_user_series_table
Migrating: 2018_01_20_200346_create_video_data_table
Migrated:  2018_01_20_200346_create_video_data_table
Migrating: 2018_01_20_200353_create_videos_table
Migrated:  2018_01_20_200353_create_videos_table
Migrating: 2018_01_20_200403_create_videos_aliases_table
Migrated:  2018_01_20_200403_create_videos_aliases_table
Migrating: 2018_01_20_200417_create_xxxinfo_table
Migrated:  2018_01_20_200417_create_xxxinfo_table
Migrating: 2018_01_20_200431_create_multigroup_binaries_table
Migrated:  2018_01_20_200431_create_multigroup_binaries_table
Migrating: 2018_01_20_200442_create_multigroup_parts_table
Migrated:  2018_01_20_200442_create_multigroup_parts_table
Migrating: 2018_01_20_200451_create_multigroup_missed_parts_table
Migrated:  2018_01_20_200451_create_multigroup_missed_parts_table
Migrating: 2018_01_22_220858_add_stored_procedures
Migrated:  2018_01_22_220858_add_stored_procedures
Migrating: 2018_04_24_132758_create_cache_table
Migrated:  2018_04_24_132758_create_cache_table
Migrating: 2018_09_13_070520_add_verification_to_user_table
Migrated:  2018_09_13_070520_add_verification_to_user_table
Migrating: 2018_12_20_221744_create_check_insert_trigger
Migrated:  2018_12_20_221744_create_check_insert_trigger
Migrating: 2018_12_20_222607_create_check_update_trigger
Migrated:  2018_12_20_222607_create_check_update_trigger
Migrating: 2018_12_20_222736_create_check_rfinsert_trigger
Migrated:  2018_12_20_222736_create_check_rfinsert_trigger
Migrating: 2018_12_20_222836_create_check_rfupdate_trigger
Migrated:  2018_12_20_222836_create_check_rfupdate_trigger
Migrating: 2018_12_20_222936_create_insert_hashes_trigger
Migrated:  2018_12_20_222936_create_insert_hashes_trigger
Migrating: 2018_12_20_223037_create_update_hashes_trigger
Migrated:  2018_12_20_223037_create_update_hashes_trigger
Migrating: 2018_12_20_223131_create_delete_hashes_trigger
Migrated:  2018_12_20_223131_create_delete_hashes_trigger
Seeding: Bhuvidya\Countries\CountriesSeeder
Seeding: CategoriesTableSeeder
Seeding: CategoryRegexesTableSeeder
Seeding: CollectionRegexesTableSeeder
Seeding: BinaryblacklistTableSeeder
Seeding: ContentTableSeeder
Seeding: GenresTableSeeder
Seeding: GroupsTableSeeder
Seeding: MenuTableSeeder
Seeding: ReleaseNamingRegexesTableSeeder
Seeding: SettingsTableSeeder
Seeding: RolesAndPermissionsSeeder
Database seeding completed successfully.
Settings table updated successfully
Adding admin user to database
Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I' (this will throw an Error in a future version of PHP)Unable to add admin user!
NNTmux installation failed. Fix reported problems and try again

php -v
ea-php-cli Copyright 2017 cPanel, Inc.
PHP 7.2.13 (cli) (built: Dec 10 2018 18:08:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

php -m
[PHP Modules]
**argon2**
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
imagick
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
zlib

[Zend Modules]
Xdebug

Please help

**To Reproduce**

**Expected behavior**

Add admin user to the database.

**Screenshots**

![h](https://user-images.githubusercontent.com/2857865/50514679-1a12de00-0aa0-11e9-8d10-ca8ae65b9ef2.jpg)

**Installation (please complete the following information):**
 - OS: CentOS release 6.10 (Final)
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [e.g. 1.0]

**Additional context**

**Comment by DariusIII** [comment]
I have added an option for users to change password hashing algorithm in their .env file in commit 32e950f8995e894cc5e8579f18a6e69f204bab73

**Comment by Sweepr** [comment]
Ah that's great, which password hashing algorithm do you suggest for my configuration or should most certainly work?

**Comment by DariusIII** [comment]
You can use only 3: bcrypt, argon and argon2id (which is supported by php 7.3 so that is not usable). 
Try bcrypt, that should work for you.

**Comment by Sweepr** [comment]
Database seeding completed successfully.
Settings table updated successfully
Adding admin user to database
Generating application key
Application key set successfully.
NNTmux installation completed successfully

Perfect!.. thank you.
