### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: file_put_contents(/home/public_html/NNTmux/public/storage/framework/views

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#826]
**Describe the bug**

.env set:

VIEW_COMPILED_PATH=/home/public_html/NNTmux/storage/framework/views

rm -rf vendor
composer global require hirak/prestissimo
composer install
then
php artisan nntmux:install

**Problem**

After logging in, i get a white screen and error_log show's me this:

I don't understand why there's a folder called public in the Path, it shouldn't be there.

/home/public_html/NNTmux/**public**/storage/framework/views/b6b50e7b1de8209068d4b88197846ac55e6d4609.php

Should be:

/home/public_html/NNTmux/storage/framework/views/b6b50e7b1de8209068d4b88197846ac55e6d4609.php

[28-Dec-2018 16:12:11 Europe/Amsterdam] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/home/public_html/NNTmux/**public**/storage/framework/views/b6b50e7b1de8209068d4b88197846ac55e6d4609.php): failed to open stream: No such file or directory in /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122

Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/...', 122, Array)

#1 /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/home/...', '<?php $__env->s...', 0)

#2 /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/home/...', '<?php $__env->s...')

#3 /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/home/...' in /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 122

**Comment by DariusIII** [comment]
There should be no public there. But when i think about it, what is the URL from which you access your indexer? What is your apache/nginx path to it?

**Comment by Sweepr** [comment]
/home/public_html/NNTmux/public is where the index.php resides, which is document root for the domain.


DocumentRoot /home/public_html/NNTmux/public

**Comment by Sweepr** [comment]
I edited the httpd.conf removing the /public

So it reflects: DocumentRoot /home/public_html/NNTmux

[28-Dec-2018 17:08:57 Europe/Amsterdam] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/home/public_html/NNTmux/nzbnab/storage/framework/views/b6b50e7b1de8209068d4b88197846ac55e6d4609.php): failed to open stream: No such file or directory in /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/...', 122, Array)

#1 /home/public_html/NNTmux/nzbnab/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/home/...', '<?php $__env->s...', 0)

#2 //home/public_html/NNTmux/nzbnab/vendor/laravel/framework/src/Illuminate/View/Compilers
/BladeCompiler.php(122): Illuminate\Filesystem\Filesystem->put('/home/...', '<?php $__env->s...')

#3 /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/View/Engines
/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/home/...')

#4 /h in /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 122

**Comment by Sweepr** [comment]
cd into /home/public_html/NNTmux/nzbnab/storage/framework/views doesn't exist, 

cd into /home/public_html/NNTmux/nzbnab/storage/framework exists

**Comment by Sweepr** [comment]
Changed the .env file into VIEW_COMPILED_PATH=/home/public_html/NNTmux/resources/views

rm -rf vendor
composer install
php artisan nntmux:install
php artisan config:cache


When logging in to the website results in:

 419

Sorry, your session has expired. Please refresh and try again. 

But the error is gone now, not sure what the correct folder should be?

**Comment by DariusIII** [comment]
Just remove that VIEW_COMPILED_PATH from .env, it will work then.

**Comment by Sweepr** [comment]
Done so, but into something else now:

[28-Dec-2018 19:14:38 Europe/Amsterdam] PHP Fatal error:  Uncaught InvalidArgumentException: Please provide a valid cache path. in /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:36
Stack trace:

#0 /home/public_html/NNTmux/nzbnab/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(141): Illuminate\View\Compilers\Compiler->__construct(Object(Illuminate\Filesystem\Filesystem), false)

#1 /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}(Object(Illuminate\Foundation\Application), Array)

#2 /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build(Object(Closure))

#3 /home/public_html/NNTmux/nzbnab/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('blade.compiler', Array)

#4 /home/public_html/NNTmux/nzbnab/vendor/laravel/framework/src/Illu in /home/public_html/NNTmux/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php on line 36

Giving up for today ;-)
Continue tomorrow.

**Comment by Sweepr** [comment]
Searching the for that error message i found this:

https://stackoverflow.com/questions/38483837/please-provide-a-valid-cache-path
Upon reading i found that storage/framework didn't contain those folder so i created them and gave correct permissions.

Created these folders under storage/framework:

    sessions
    views
    cache

In sessions folder i now see files random filenames being populated, like: ZLiWFuOBsuxkG7djxEA3bMVIURxl0dvpFqacbSif etc

In cache folder there are these folders: \data\85\5f\ 

In views folder there are 3 .php files populated with random name's

So, i see the login page, i login with my admin user/pass and still get confronted with:

 **419

Sorry, your session has expired. Please refresh and try again.** 

Domain error_log is empty.

Any suggestion's?

**Comment by Sweepr** [comment]
Lol.. ;_0

Adding just https:// to the URL made me login, case closed.
