### ISSUE TITLE
 predb_import_daily_batch.php - ErrorException  : PDOStatement::execute() 

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#827]
When running:

php predb_import_daily_batch.php 1 local true 

ea-php-cli Copyright 2017 cPanel, Inc.
Downloading: https://raw.githubusercontent.com/nZEDb/nZEDbPre_Dumps/master/dumps/1404152742/1404152742_predb_dump.csv.gz

   ErrorException  : PDOStatement::execute() expects parameter 1 to be array, string given

  at /home/public_html/nntmux/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
    113|      */
    114|     public function execute($params = null)
    115|     {
    116|         try {
  > 117|             return parent::execute($params);
    118|         } catch (\PDOException $exception) {
    119|             throw new PDOException($exception);
    120|         }
    121|     }

  Exception trace:

  1   PDOStatement::execute("/home/public_html/nntmux/resources/1404152742_predb_dump.csv")
      /home/public_html/nntmux/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

  2   Doctrine\DBAL\Driver\PDOStatement::execute("/home/public_html/nntmux/resources/1404152742_predb_dump.csv")
      /home/public_html/nntmux/Blacklight/db/PreDb.php:164

  Please use the argument -v to see more details.   

Using: Server version: 10.2.20-MariaDB MariaDB Server

**Comment by DariusIII** [comment]
What are your server specs, as i see this right on start:

`ea-php-cli Copyright 2017 cPanel, Inc.`

and i don't like it at all. Some kind of shared hosting?

**Comment by sinistra** [comment]
Its a unmanaged VPS with 4GB RAM, currently on CentOS 6.9, Mariadb 10.2.20. multiple
support for PHP 7.2.13 and under.

**Comment by actionhenkt** [comment]
I had the same problem:
git reset --hard
git pull
php artisan nntmux:all

fixed it for me

**Comment by Sweepr** [comment]
Ah, but git reset --hard is really dangerous, you shouldn't just use that.

Apart from that since i didn't use any other git commands other then a "git pull" yesterday to solve another issue has somehow solved this problem. https://github.com/NNTmux/newznab-tmux/issues/840

The predb_import_daily_batch.php is working like expected, so closing.
