### ISSUE TITLE
SmartyException Unable to load template 'file:/login.tpl'

### ISSUE THREAD

**Issue by micknolans** [NNTmux/newznab-tmux#833]
fresh install

dev also master

problem:
SmartyException
Unable to load template 'file:/login.tpl'

/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php
` // checks if template exists
        if (!$this->source->exists) {
            throw new SmartyException(
                "Unable to load template '{$this->source->type}:{$this->source->name}'" .
                ($this->_isSubTpl() ? " in '{$this->parent->template_resource}'" : '')
            );
        }`

main site 500 page
thanks

mariadb 10.2
php 7.2

**Comment by DariusIII** [comment]
Was the install successful?
Are permissions set properly?

And please use the issue template when it pops out.

**Comment by micknolans** [comment]
seems to have installed ok, did notice when populating database:

Seeding: GenresTableSeeder
Seeding: GroupsTableSeeder
`Seeding: MenuTableSeeder

   ReflectionException  : Class MenuTableSeeder does not exist

  at /home/*/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
    775|         if ($concrete instanceof Closure) {
    776|             return $concrete($this, $this->getLastParameterOverride());
    777|         }
    778|
  > 779|         $reflector = new ReflectionClass($concrete);
    780|
    781|         // If the type is not instantiable, the developer is attempting to resolve
    782|         // an abstract type such as an Interface or Abstract Class and there is
    783|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   ReflectionClass::__construct("MenuTableSeeder")
      /home/****/vendor/laravel/framework/src/Illuminate/Container/Container.php:779

  2   Illuminate\Container\Container::build("MenuTableSeeder")
      /home/****/vendor/laravel/framework/src/Illuminate/Container/Container.php:658
`
 Please use the argument -v to see more details.
Settings table updated successfully
Adding admin user to database
Generating application key
Application key set successfully.
NNTmux installation completed successfully

**Comment by DariusIII** [comment]
Ahh, need to fix that. It looks like it installed properly, but it did not.

**Comment by DariusIII** [comment]
I have pushed a fix to dev branch.

**Comment by micknolans** [comment]
thank you
