### ISSUE TITLE
Backfill processing takes a long time > 60s

### ISSUE THREAD

**Issue by HybridFox** [NNTmux/newznab-tmux#836]
**Describe the bug**
I recently switched from nZEDb to NNTmux because of the framework being laravel and the tmux setup being greatly the same. I only noticed one tiny thing and that is that processing takes 60s+ for 20,000 articles [https://echo.akxis.io/223.png](screenshot). I'm running the same server / setup as i had with nZEDb. Is there a reason / setting the processing takes this long?

**To Reproduce**
1. Clean install run tmux

**Expected behavior**
Processing should not take this long. I am sure it is just some setting though.

**Screenshots**
https://echo.akxis.io/223.png

**Installation (please complete the following information):**
 - OS: Ubuntu 16.04
 - PHP version: PHP 7.2.13-1+ubuntu16.04.1+deb.sury.org+1
 - NNTmux version or commit: 1.0.13

**Additional context**
The tmux window also looks different. With nZEDb i had on the right hand side 3 panels instead of one big

**Comment by DariusIII** [comment]
Can you add a screenshot of the whole window?

**Comment by HybridFox** [comment]
Here ya go, https://echo.akxis.io/702.png

**Comment by DariusIII** [comment]
You are running sequential, switch to full threaded.

**Comment by HybridFox** [comment]
Thanks! That brought back the 3 windows. The processing still takes around avarage 60s though.

**Comment by DariusIII** [comment]
What are your server specs?

**Comment by HybridFox** [comment]
CPU: Intel Core i7-3770 CPU @ 3.9GHz
RAM: 16GB
DISK: is 2 raid 0 HDDs

**Comment by DariusIII** [comment]
How much is given to mysql?

**Comment by HybridFox** [comment]
I have not specifically configured anything for resource allocation to MySQL

**Comment by DariusIII** [comment]
Innodb needs to be tuned for your server, otherwise it performs very badly.

**Comment by HybridFox** [comment]
Alright, thank you! i will have a quick look at that

**Comment by DariusIII** [comment]
Check this:
http://www.mysqlperformanceblog.com/2013/09/20/innodb-performance-optimization-basics-updated/

**Comment by DariusIII** [comment]
Release processing, yes.

**Comment by DariusIII** [comment]
If you are on a provider that uses Omicron as their backend (most of current USPs), Omicron had issues with headers and missing Bytes value from them. That is what triggers this error. Nothing i can do about it.

**Comment by HybridFox** [comment]
Alright thank you anyway! I'll close this issue. Again thanks for the loads of help :)
