### ISSUE TITLE
Monitor shows v1.0.13 (master) after nntmux:all / CBP parts show 0 in monitor.

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#840]
**Describe the bug**

Update to latest master using: php artisan nntmux:all

php artisan nntmux:all

Application is now in maintenance mode.
Stopping tmux scripts and waiting 30 seconds for all panes to shutdown
Killing active tmux session: nntmux
Tmux session killed successfully
Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> Blacklight\build\ComposerScripts::postInstall
> Blacklight\build\ComposerScripts::postInstallCmd
Updating database
Nothing to migrate.
The Smarty compiled template cache has been cleaned for you
Application is now live.
Starting the tmux server and monitor script.
Starting Tmux...
Resetting expired collections dateadded to now. This could take a minute or two. Really.
0 collections reset.

git checkout master

Already on 'master'
Your branch is up to date with 'origin/master'.

**To Reproduce**

**Expected behavior**

Shouldn't the monitor show v1.0.14?

![image](https://user-images.githubusercontent.com/2857865/51036938-f1fea100-15ae-11e9-857c-6d8e7c75d0a6.png)

**Installation (please complete the following information):**

 - OS: Centos 6.10
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit 1.0.14 (latest master)

**Comment by DariusIII** [comment]
That is not a bug, it just did not pull the tag. Just do a plain old `git pull` and it will pull the tags.
As for zeroes, it happens to me on test VM and not in production but everything works so i don't realy look at it :)

**Comment by DariusIII** [comment]
Try to drop multigroup_ tables (collections, binaries, parts, missed_parts, posters) and see if that helps.

**Comment by Sweepr** [comment]
git pull solved the tagging, now show's Monitor shows v1.0.14 .

**Comment by Sweepr** [comment]
Like suggested i dropped all multigroup_tables (collections, binaries, parts, missed_parts, posters) restarted Tmux, open Tmux start it showed "160 collections reset." but still Monitor pane stay;'s at 0. also CBP's do exist in database, everything works fine.

Nfo, Renames, PreDB show numbers under Unmatched and Matched.

Also In Database and In Process Category show's numbers.

**Comment by Sweepr** [comment]
Closing this, and creating another bug report for the C.B.P. = 0 in Monitor pane
