### ISSUE TITLE
Tag's not updated when using git pull origin master (nntmux:git)

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#842]
** Problem description **

When updating using nntmux:all the script run's "git pull origin master", but this doesn't update the tag's automagically.

**Describe the solution you'd like**

Like in https://github.com/NNTmux/newznab-tmux/issues/840 i had to manually run "git pull" to fetch the tag's, this isn't such a big deal but would be nice to have to keep track of update's.

So:

'git pull origin master' fetches a copy of the master branch from the original repository, and merges it with the current branch you have checked out.

'git pull' by default merges your checked out, local branch with the remote branch you created your local branch from.

In terms of use-cases, I imagine you would use the 'git pull origin master' form when you want to merge your current branch with a different branch than the one you created your local one with originally. If you just want to merge the latest changes on the remote copy of your current branch (the one you used to create your local copy of the branch), you would use the 'git pull' form.

Would it cause problem's to other users to invoke "git pull" right after the "git pull origin master"?

Similar issue found here: https://github.com/magit/magit/issues/2599#issuecomment-202450552

**Comment by Sweepr** [comment]
Reading the changelog i found this:

2016-04-25 DariusIII
* Upd: Update composer, composer will handle git pull, no need for manual git pull

https://github.com/NNTmux/newznab-tmux/blob/24e50c583acd76a484b4a54e9b3f0c6813f68fce/Changelog#L3748

So if i understand right according the changelog, composer should handle a "git pull" when running php artisan nntmux:all but for some reason it does not?

**Comment by Sweepr** [comment]
Ah, you already applied a fix for that ;-)

**Comment by DariusIII** [comment]
This was something completely different and now is irrelevant.

**Comment by Sweepr** [comment]
Great!, closing.
