### ISSUE TITLE
Update binaries encountered non numeric value

### ISSUE THREAD

**Issue by actionhenkt** [NNTmux/newznab-tmux#844]
Have installed a new ubuntu server 16.04 and configured nntmux on it using the guide on the wiki page. Configured a few groups to test with (10 days backfill on first run). Some groups show an error when updating binaries:"a non numeric value was encountered.". This happens when running update_binaries manually or through tmux. The script stops processing/downloading headers when this error occurs

It doesnt happen on all groups, of the 4 groups i added i saw it on a.b.dvd and a.b.teevee. is this an issue with nntmux/database not allowing non numeric values in a specific field assigned for header info ? If so, can I change it to allow non numerics ?

**Comment by DariusIII** [comment]
This is an issue with Omicron based resellers. Omicron had problems with headers where 'Bytes' header was empty (essentially that header had no value or was completely missing) and indexing expects this value to be set to function properly. 

You will encounter this problem when backfilling, as they fixed new headers, but old ones are missing this, hence you see the error. 

There is nothing to fix, it is not NNTmux error.
