### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY'

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#846]
**Describe the bug**

running php predb_import_daily_batch.php 0 local true

Or php predb_import_daily_batch.php progress local true gives me:

[2019-01-16 14:26:47] NNTmux.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '\xCE\xF7\xA7\xCC\x87\xDF\x01{\xEA\xE0\x96\xE0s\xB1\x82\xA9' for key 'PRIMARY' (SQL: INSERT INTO predb (title, nfo, size, files, f$
                        SELECT pi.title, pi.nfo, pi.size, pi.files, pi.filename, pi.nuked, pi.nukereason, pi.category, pi.predate, pi.source, pi.requestid, groups_id
                        FROM predb_imports AS pi
                        ON DUPLICATE KEY UPDATE predb.nfo = IF(predb.nfo IS NULL, pi.nfo, predb.nfo),
                            predb.size = IF(predb.size IS NULL, pi.size, predb.size),
                            predb.files = IF(predb.files IS NULL, pi.files, predb.files),
                            predb.filename = IF(predb.filename = '', pi.filename, predb.filename),
                            predb.nuked = IF(pi.nuked > 0, pi.nuked, predb.nuked),
                            predb.nukereason = IF(pi.nuked > 0, pi.nukereason, predb.nukereason),
                            predb.category = IF(predb.category IS NULL, pi.category, predb.category),
                            predb.requestid = IF(predb.requestid = 0, pi.requestid, predb.requestid),
                            predb.groups_id = IF(predb.groups_id = 0, pi.groups_id, predb.groups_id)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Dupli$
                        SELECT pi.title, pi.nfo, pi.size, pi.files, pi.filename, pi.nuked, pi.nukereason, pi.category, pi.predate, pi.source, pi.requestid, groups_id
                        FROM predb_imports AS pi
                        ON DUPLICATE KEY UPDATE predb.nfo = IF(predb.nfo IS NULL, pi.nfo, predb.nfo),
\t                    predb.size = IF(predb.size IS NULL, pi.size, predb.size),
\t                    predb.files = IF(predb.files IS NULL, pi.files, predb.files),
\t                    predb.filename = IF(predb.filename = '', pi.filename, predb.filename),
\t                    predb.nuked = IF(pi.nuked > 0, pi.nuked, predb.nuked),
\t                    predb.nukereason = IF(pi.nuked > 0, pi.nukereason, predb.nukereason),
\t                    predb.category = IF(predb.category IS NULL, pi.category, predb.category),
\t                    predb.requestid = IF(predb.requestid = 0, pi.requestid, predb.requestid),
\t                    predb.groups_id = IF(predb.groups_id = 0, pi.groups_id, predb.groups_id)) at /home/public_html/nntmux/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOExcepti$
[stacktrace]
#0 /home/public_html/nntmux/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('INSERT INTO pre...', Array, Object(Closure))
#1 /home/public_html/nntmux/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('INSERT INTO pre...', Array, Object(Closure))
#2 /home/public_html/nntmux/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('INSERT INTO pre...', Array)
#3 /home/public_html/nntmux/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\\Database\\Connection->insert('INSERT INTO pre...')
#4 /home/public_html/nntmux/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Database\\DatabaseManager->__call('insert', Array)
#5 /home/public_html/nntmux/cli/data/predb_import_daily_batch.php(170): Illuminate\\Support\\Facades\\Facade::__callStatic('insert', Array)
#6 {main}
"}

**To Reproduce**

I truncated all 3 predb_tables but still complains about duplicates.

**Installation (please complete the following information):**
 - OS: [6.10]
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [e.g. 1.0.16

**Comment by Sweepr** [comment]
Scraper is complaining:

Unknown column 'source' [REPLACE INTO predb_rt (id, title, filename, source) VALUES , how to fix that?

**Comment by DariusIII** [comment]
What are your DB and predb table collations set to?

**Comment by Sweepr** [comment]
Shouldn't https://github.com/NNTmux/newznab-tmux/blob/master/misc/sphinxsearch/create_se_tables.php create a 'source' column in table predb_se?

Thats why i was getting an error earlier, i fixed that manually adding the column to that table.

**Comment by DariusIII** [comment]
No.Predb_se table has nothing to do with that column. You need to stop sphinx, delete all predb_rt files from /var/lib/sphinxsearch/data/ folder, copy new sphinx.conf , start sphinx and populate indexes.

**Comment by Sweepr** [comment]
@DariusIII i was reffering to this error earlier:

Unknown column 'source' [REPLACE INTO predb_rt (id, title, filename, source) VALUES , 

I already did like you suggested but still resulted in the above error,  copied the new sphinx.conf to the correct location and stopped tmux and Sphinx, deleted the data folder contents, re-created se+rt , but still missing that column so started looking and found it missing, so i added that and the error about Unknown column 'source' [REPLACE INTO predb_rt (id, title, filename, source) VALUES , is go e now.. weird.

**Comment by bert0901** [comment]
I had that issue.

When I looked at the predb table  insert_hashes trigger, the insert one was ticked on "update" and not "insert".

This was a new db install when this happens. Changed that to the insert option and it did all the predb_hashes with no error.

Not guarantee this is the solution but seemed to solve it for me.

**Comment by Sweepr** [comment]
Yep, that solved it, no more complains about duplicate entry's.
