### ISSUE TITLE
'a.b.boneless' Added by predb import script / Groups does not exist when running update_binaries.php

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#847]
**Describe the bug**

Very strange issue, Added by predb import script but they don't exist.

'a.b.boneless'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
'a.b.cd.image'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.console.ps3'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.erotica'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.games.wii'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.games.xbox360'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.inner-sanctum'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.mom'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.moovee'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.movies.divx'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.sony.psp'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.sounds.flac'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.sounds.mp3.complete_cd'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.teevee'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge
'a.b.warez'						 Added by predb import script | n/a |   | n/a ago | Activate | Activate |   | n/a | n/a | 1 | Reset						\|						 Delete						\|						 Purge

**To Reproduce**

Updating: 5 group(s) - Using compression? Yes [Blacklight\Binaries::updateAllGroups]
Starting group 1 of 5 [Blacklight\Binaries::updateAllGroups]
Code 411: No such news group on server
Skipping group: 'alt.binaries.boneless'

   Symfony\Component\Debug\Exception\FatalThrowableError  : Cannot use object of type PEAR_Error as array

  at /home/public_html/nntmux/Blacklight/Binaries.php:323
    319|         $groupNNTP = $this->_nntp->selectGroup($groupMySQL['name']);
    320|         if ($this->_nntp->isError($groupNNTP)) {
    321|             $groupNNTP = $this->_nntp->dataError($this->_nntp, $groupMySQL['name']);
    322|
  > 323|             if (isset($groupNNTP['code']) && (int) $groupNNTP['code'] === 411) {
    324|                 Group::disableIfNotExist($groupMySQL['id']);
    325|             }
    326|             if ($this->_nntp->isError($groupNNTP)) {
    327|                 return;

  Exception trace:

  1   Blacklight\Binaries::updateGroup(Object(App\Models\Group))
      /home/public_html/nntmux/Blacklight/Binaries.php:276

  2   Blacklight\Binaries::updateAllGroups()
      /home/public_html/nntmux/misc/update/update_binaries.php:35

**Screenshots**

**Installation (please complete the following information):**
 - OS: [e.g. Centos 6.10]
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [e.g. 1.0.16]

**Additional context**

**Comment by DariusIII** [comment]
There was an error in import script, i missed to add a part of needed query so data was imported without quotes skipped, so instead of alt.binaries.boneless, group (and rest of the needed data like titles, filenames, dates etc) were added as 'alt.binaries.boneless' etc.
I have updated the script and pushed the change.
It is best to remove those entries from predb and group tables:

SQL:

`delete from predb where title REGEXP "^'";`

`delete from groups where name REGEXP "^'";`

**Comment by Sweepr** [comment]
Ok. will do so. thnx

**Comment by DariusIII** [comment]
Don't forget to run the populate script again.

**Comment by Sweepr** [comment]
Also fixed, closing.
