### ISSUE TITLE
Match 

### ISSUE THREAD

**Issue by actionhenkt** [NNTmux/newznab-tmux#849]
This is not so much of a problem with nntmux/bug i think but I dont know where else I can ask this so sorry if this is not supposed to be on here. Having problems with the predb matching, nntmux has been running for a while and it is getting alot of work which is not being processed, releases/parts seem to be stuck in the match prefiles/predb. It shows me it has 2600 releases to process (match prefiles) but its not processing them. I tried to run match_prefiles manually but that also says 2600 releases to process. Tried all combinations in fixreleasenames.php it says "nothing to fix". Can I manually force this process ? How do I find out where it is getting hold back ?

Have 2662 waiting in prefiles and 5489 in total waiting to be processed.

Thanks!

**Comment by DariusIII** [comment]
That is just how much it tries to match, not real number of releases waiting to be matched.

**Comment by actionhenkt** [comment]
Allright, thanks!
