### ISSUE TITLE
editing releases - data not loading

### ISSUE THREAD

**Issue by actionhenkt** [NNTmux/newznab-tmux#863]
**Describe the bug**
When trying to edit releases from the webinterface using list view the release data fails to load and editing is not possible.

**To Reproduce**
1. Go to 'movies->movies->list'
2. Click on a check box next to a release
3. Click on 'edit' at the top of the list page
4. See error: "this content failed to load"

**Screenshots**
![image](https://user-images.githubusercontent.com/46613117/51785930-8b0beb00-215d-11e9-97ea-1d7a8560edd3.png)

**Installation (please complete the following information):**
 - OS: ubuntu 18.04
 - PHP version PHP 7.2.10-0ubuntu0.18.04.1
 - NNTmux version or commit: latest master

**Additional context**

**Comment by Sweepr** [comment]
Same here, also when clicking on "NFO" it's showing the same from list view.

On the Details page "Edit" and "NFO" are working fine.

**Comment by DariusIII** [comment]
The front end will be converted to blade template engine  in near future, so i will not be fixing this issue for now (unless something gets in the way).
