### ISSUE TITLE
Process releases / Not removing from disabled category.

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#865]
**Describe the bug**

I have disabled some category's in Admin-Site edit, but in Tmux i'm seeing them still being added in the database, 

Removed releases: 0 from disabled category

I have disabled audio for example, I see releases being added still to that category in the database.

**Expected behavior**

Remove/Delete disabled category's.

**Screenshots**

![image](https://user-images.githubusercontent.com/2857865/51817720-2cb14a80-22cc-11e9-833e-ee471dd52b45.png)

**Installation (please complete the following information):**
 - OS: CentOS 6.10
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [e.g. 1.0.16]

P.S

nZEDb has a script which can remove releases from disabled category's., does nntmux feature such script?

https://github.com/nZEDb/nZEDb/blob/0.x/misc/testing/Release/delete_disabled_category_releases.php

**Comment by Sweepr** [comment]
Please correct me if i'm misunderstanding, but does setting a catergory to "active" = 0 only disable the view on website? or does it also make sure they are not added to DB? 

since i have a few category's disabled but in Tmux monitor i'm still seeing releases being added in disabled category's. is that intended behaviour?

**Comment by DariusIII** [comment]
As description on top of that page says:

> Make a category inactive to remove it from the menu. This does not prevent binaries being matched into an appropriate category.

**Comment by Sweepr** [comment]
I'm blind as a bat, i didn't see that.

:flushed:

**Comment by Sweepr** [comment]
Is it not possible disable a unwanted category?

nZEDb does feature such option.

**Comment by DariusIII** [comment]
Can you point me to where in nZEDb is that?

**Comment by Sweepr** [comment]
Same place as nntmux where you can edit the category. theres an extra option. "disable" yes/no

**Comment by Sweepr** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/www/admin/category-edit.php

**Comment by DariusIII** [comment]
Should be fixed in commit 6a31eb036059042d7f1566f0350913f307093f2c

**Comment by Sweepr** [comment]
Thnx, closing.  :+1:
