### ISSUE TITLE
Call to a member function isNotEmpty() on array 

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#871]
**Describe the bug**

When opening a release on the website i get presented with an expection:

 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function isNotEmpty() on array

Blacklight/Releases.php

                $whereSql
            );
            $sql = sprintf(
                'SELECT * FROM (
                    %s
                ) r
                ORDER BY r.%s %s
                LIMIT %d OFFSET %d',
                $baseSql,
                $orderBy[0],
                $orderBy[1],
                $limit,
                $offset
            );
            $releases = Cache::get(md5($sql));
            if ($releases !== null) {
                return $releases;
            }
            $releases = ! empty($searchResult) ? Release::fromQuery($sql) : [];
            if ((\is_array($releases) && ! empty($releases)) || $releases->isNotEmpty()) {
                $releases[0]->_totalrows = $this->getPagerCount($baseSql);
            }
            $expiresAt = now()->addMinutes(config('nntmux.cache_expiry_medium'));
            Cache::put(md5($sql), $releases, $expiresAt);
     
            return $releases;
        }
     
        /**
         * Search function for API.
         *
         *
         * @param       $searchName
         * @param       $groupName
         * @param int   $offset
         * @param int   $limit
         * @param int   $maxAge
         * @param array $excludedCats
         * @param array $cat
         * @param int   $minSize

Arguments

    "Call to a member function isNotEmpty() on array"

**To Reproduce**

Error started to appear after pull latest master v1.0.17.1

**Expected behavior**

**Screenshots**

**Installation (please complete the following information):**
 - OS: Centos 6.10
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [master v1.0.17.1]

**Additional context**

No sure if it's a bug or something with my install, any suggestions?

**Comment by actionhenkt** [comment]
This happens also when searching for a release (predb search is OK) and there is no match found using the site search functionality. Tried repopulating releases_rt but that did not help.

**Comment by DariusIII** [comment]
This a bug 1.0.17.1 should have fixed. Will fix it ASAP.

**Comment by DariusIII** [comment]
I have pushed a possible fix to dev.

**Comment by Sweepr** [comment]
Implemented the fix into 1.0.17.1 and the error's doesn't appear anymore, can open and search releases without error's.

**Comment by Sweepr** [comment]
Closing this as it's resolved.
