### ISSUE TITLE
NZB > Details / RAR Contains Files: remains empty ?

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#872]
**Describe the bug**

NZB > Details / RAR Contains Files: remains empty ?

**To Reproduce**

Open details view of release.

**Expected behavior**

Show file contents

**Screenshots**

![untitled](https://user-images.githubusercontent.com/2857865/52163923-bc4e6300-26e9-11e9-9441-d288f3f71ce9.jpg)

**Installation (please complete the following information):**
 - OS: [e.g. CentOS 6.10]
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [e.g. 1.0.17.1 / 1.0.17.2 ]

**Additional context**

**Comment by Sweepr** [comment]
This happens on all releases, do you think a reset PP would do any good?

**Comment by DariusIII** [comment]
If it happens on all releases, then something is not configured right on your server. 

Have you edited your .env to include TEMP_UNRAR_PATH?  [ENV example](https://github.com/NNTmux/newznab-tmux/blob/master/.env.example#L118)

**Comment by Sweepr** [comment]
Yes.

.env reads:

TEMP_UNRAR_PATH=/home/public_html/nntmux/resources/tmp/unrar/
TEMP_UNZIP_PATH=/home/public_html/nntmux/resources/tmp/unzip/

config.php reads:

  'laravel-directory-cleanup' => 
  array (
    'directories' => 
    array (
      '/home/public_html/nntmux/resources/tmp/unrar/' => 
      array (
        'deleteAllOlderThanMinutes' => 240,
      ),
      '/home/public_html/nntmux/resources/tmp/unzip/' => 
      array (
        'deleteAllOlderThanMinutes' => 240,
      ),
    ),

But now you mention, I did however create a entry yesterday in /etc/fstab to make a tmpfs in ram for faster processing, could this be an issue?

none /home/public_html/nntmux/resources/tmp/unrar   tmpfs  nodev,nodiratime,noexec,nosuid,size=100M 0 0

none /home/public_html/nntmux/resources/tmp/unzip   tmpfs  nodev,nodiratime,noexec,nosuid,size=100M 0 0

#mount:

none on /home/public_html/nntmux/resources/tmp/unrar type tmpfs (rw,noexec,nosuid,nodev,nodiratime,size=100M)

none on /home/public_html/nntmux/resources/tmp/unzip type tmpfs (rw,noexec,nosuid,nodev,nodiratime,size=100M)

**Comment by DariusIII** [comment]
Nothing changed in code related to that.

**Comment by Sweepr** [comment]
Closing this, problem was on my end.
