### ISSUE TITLE
Latest Sphinx 3.1.1 gives warnings about key 'mva_updates_pool' and 'dict' removed from Sphinx conf

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#878]
**Describe the bug**

Sphinx 3.1.1 (commit 612d99f)
Copyright (c) 2001-2018, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/usr/local/etc/sphinx.conf'...
WARNING: key 'dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'mva_updates_pool' was permanently removed from Sphinx configuration. Refer to documentation for details.

**To Reproduce**

Copy https://github.com/NNTmux/newznab-tmux/blob/master/misc/sphinxsearch/sphinx.conf into Searchd path -> /usr/local/etc/sphinx.conf

Start searchd 

**Expected behavior**

No warnings

**Installation (please complete the following information):**

Linux x64 binaries glibc 2.12 (Centos 6 etc) | 3.1.1
Latest Sphinx 3.1.1 (commit 612d99f)

**Comment by DariusIII** [comment]
SPhinx 3.1.1 is not publicly available to download, nor in any PPA, just on their site and we switched to manticoresearch for that reason. 

I can remove those lines and see what happens with what we support.

**Comment by DariusIII** [comment]
Unfortunately, it cannot be removed from sphinx.conf, but you can remove all lines that are marked as deprecated on your own.

**Comment by Sweepr** [comment]
Ok, thanks for the info, seems to work ok using sphinx 3.1.1 except for the warnings.

I need to see if i can get manticore working for my OS since last time i tried it required a higher version Glibc 2.17 which CentOS 6 doesn't support.

**Comment by DariusIII** [comment]
I have updated sphinx.conf in dev to address this issue.

**Comment by Sweepr** [comment]
Cool, thnx i'll check it out later.

**Comment by Sweepr** [comment]
I just copied over the new sphinx.conf to my env, upon reload there's still one mention of dict = keywords here: https://github.com/NNTmux/newznab-tmux/blob/3c6aeef668cc845b97411ce4cbe5cb2fe375bacf/misc/sphinxsearch/sphinx.conf#L61

is it safe to comment that line ?

**Comment by DariusIII** [comment]
Yes it is safe, i missed it, although it should have been commented out.

**Comment by Sweepr** [comment]
:+1:
