### ISSUE TITLE
Random numbers (GUID) - Appears to be missing NZB file, Skipping

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#885]
**Describe the bug**

Releases do get renamed and matched, but sometimes i get this message in the Tmux panel.

![match](https://user-images.githubusercontent.com/2857865/52619850-25c93100-2ea3-11e9-843e-a5de5fc24570.jpg)

Random numbers (GUID) - Appears to be missing NZB file, Skipping, reported by Tmux pane ( No mention of missing NZB files? unless to is normal behaviour.

**To Reproduce**

Unknown

**Expected behavior**

No mention of missing NZB files? unless to is normal behaviour.

**Screenshots**

![missing](https://user-images.githubusercontent.com/2857865/52619623-78561d80-2ea2-11e9-89a3-73fd8a264093.jpg)

**Installation (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - PHP version [e.g. PHP 7.2.13]
 - NNTmux version or commit [e.g. 1.0.17.2]

**Additional context**

**Comment by DariusIII** [comment]
Renaming releases is not related to missing nzb. Renaming is done purely from database, while some other processes check if the nzb is actually present. Release being renamed does not mean that for some reason nzb is not created (or maybe release is deleted already).

**Comment by Sweepr** [comment]
That's what i was thinking aswell, could it be the NZB get's deleted because it's passworded and this is the result of that?

**Comment by DariusIII** [comment]
Very likely.

**Comment by Sweepr** [comment]
Is it possible to remove the release GUID from the database when it's passworded anyway so we don't get bothered with those messages?

**Comment by DariusIII** [comment]
It should be removed already, but i will have a look at the code and see if something is not working right.

**Comment by Sweepr** [comment]
Issue fixed in dev: https://github.com/NNTmux/newznab-tmux/commit/d01dcb5507b1ac57ea79b3d06080cef0e9d4d18c

Closing.
