### ISSUE TITLE
differences indexing/regexes

### ISSUE THREAD

**Issue by actionhenkt** [NNTmux/newznab-tmux#890]
Hello, not an issue more a few questions on how to work with nntmux/regexes, I was comparing results between nntmux and a random indexer (paid), I noticed nntmux is missing releases which are on the paid one and vice versa. Guess this is mostly due to ability to rename releases (regexes ?). Would having a different, or multiple usenet providers on different networks (I noticed there is an option for a second usenet provider in the conf file) generate more releases (would it download headers not on network A but are on B) or is it just down to putting in more regexes to help with renaming ? Can you explain what nntmux does when a regex match occurs ? Im having some problems understanding the process nntmux is doing and what a release will be renamed to if a regex matches .. 

Are there ways to improve release renaming ?

Thanks for your time!

**Comment by DariusIII** [comment]
Sorry for the late reply.

To get answer to this question, you should join our official support channel #tmux on synirc.
