### ISSUE TITLE
Client error: `GET https://webservice.fanart.tv`  `404 Not Found` logged in error log.

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#922]
**Describe the bug**

Laravel appends error into the error log:

NNTmux.ERROR: Client error: `GET https://webservice.fanart.tv/v3/movies/tt1773368?api_key=************apikeyremoved**********` resulted in a `404 Not Found` response:
{
    "status": "error",
    "error message": "Not found"
}
  
**To Reproduce**

The result is valid, but shouldn't be logged when there's no result.

**Expected behavior**

Silently accept no result, and continue.

**Comment by DariusIII** [comment]
This is actually not an issue, but i have added a code in dev that logs errors from getRawHtml helper function only if debug is enabled.

**Comment by Sweepr** [comment]
You are right, not a real issue, i'll close this one.

Thanks for the fix.
