### ISSUE TITLE
cannot add admin

### ISSUE THREAD

**Issue by lloot** [NNTmux/newznab-tmux#930]
Ubuntu 18.04, PHP 7.3.2, Apache, MariaDB 10.3

follwed guide step by step
DMIN_USER=lloot
ADMIN_PASS=123456
ADMIN_EMAIL=lloot66@gmail.com

on,    php artisan nntmux:install
i get error:
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.Unable to add admin user!
NNTmux installation failed. Fix reported problems and try again

using latest composer etc

**Comment by DariusIII** [comment]
This is duplicate of #928 .
