### ISSUE TITLE
htacsess 

### ISSUE THREAD

**Issue by lloot** [NNTmux/newznab-tmux#932]
Hey all site installed perfect with new commits afteer few tries now , the moment i login i get error 500 any ideas how to work around it??

<IfModule mod_rewrite.c>
RewriteEngine on
#RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On
    # Do not process images or CSS files further
    RewriteRule \.(css|eot|gif|gz|ico|inc|jpe?g|js|ogg|png|svg|ttf|txt|woff|woff2|xml)$ - [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

# Block MySQL injections, RFI, base64, etc.
#RewriteCond %{QUERY_STRING} [a-zA-Z0-9_]=http:// [OR]
#RewriteCond %{QUERY_STRING} [a-zA-Z0-9_]=(\.\.//?)+ [OR]
#RewriteCond %{QUERY_STRING} [a-zA-Z0-9_]=/([a-z0-9_.]//?)+ [NC,OR]
#RewriteCond %{QUERY_STRING} \=PHP[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12} [NC,OR]
#RewriteCond %{QUERY_STRING} (\.\./|\.\.) [OR]
#RewriteCond %{QUERY_STRING} ftp\: [NC,OR]
#RewriteCond %{QUERY_STRING} http\: [NC,OR]
#RewriteCond %{QUERY_STRING} https\: [NC,OR]
#RewriteCond %{QUERY_STRING} \=\|w\| [NC,OR]
#RewriteCond %{QUERY_STRING} ^(.*)/self/(.*)$ [NC,OR]
#RewriteCond %{QUERY_STRING} ^(.*)cPath=http://(.*)$ [NC,OR]
#RewriteCond %{QUERY_STRING} (\<|%3C).*script.*(\>|%3E) [NC,OR]
#RewriteCond %{QUERY_STRING} (<|%3C)([^s]*s)+cript.*(>|%3E) [NC,OR]
#RewriteCond %{QUERY_STRING} (\<|%3C).*iframe.*(\>|%3E) [NC,OR]
#RewriteCond %{QUERY_STRING} (<|%3C)([^i]*i)+frame.*(>|%3E) [NC,OR]
#RewriteCond %{QUERY_STRING} base64_encode.*\(.*\) [NC,OR]
#RewriteCond %{QUERY_STRING} base64_(en|de)code[^(]*\([^)]*\) [NC,OR]
#RewriteCond %{QUERY_STRING} GLOBALS(=|\[|\%[0-9A-Z]{0,2}) [OR]
#RewriteCond %{QUERY_STRING} _REQUEST(=|\[|\%[0-9A-Z]{0,2}) [OR]
#RewriteCond %{QUERY_STRING} ^.*(\[|\]|\(|\)|<|>).* [NC,OR]
#RewriteCond %{QUERY_STRING} (NULL|OUTFILE|LOAD_FILE) [OR]
#RewriteCond %{QUERY_STRING} (\./|\../|\.../)+(motd|etc|bin) [NC,OR]
#RewriteCond %{QUERY_STRING} (localhost|loopback|127\.0\.0\.1) [NC,OR]
#RewriteCond %{QUERY_STRING} (<|>|'|%0A|%0D|%27|%3C|%3E|%00) [NC,OR]
#RewriteCond %{QUERY_STRING} concat[^\(]*\( [NC,OR]
#RewriteCond %{QUERY_STRING} union([^s]*s)+elect [NC,OR]
#RewriteCond %{QUERY_STRING} union([^a]*a)+ll([^s]*s)+elect [NC,OR]
#RewriteCond %{QUERY_STRING} (;|<|>|'|"|\)|%0A|%0D|%22|%27|%3C|%3E|%00).*(/\*|union|select|insert|drop|delete|update|cast|create|char|convert|alter|declare|order|script|set|md5|benchmark|encode) [NC,OR]
#RewriteCond %{QUERY_STRING} (sp_executesql) [NC]
#RewriteRule ^(.*)$ - [F,L]
</IfModule>

**Comment by DariusIII** [comment]
Check apache error log?

**Comment by lloot** [comment]
from other_vhost-accsses.log

localhost:80 127.0.0.1 - - [09/Mar/2019:23:00:45 +0200] "GET /index.php HTTP/1.1" 500 11276 "http://localhost/index.php/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
localhost:80 127.0.0.1 - - [09/Mar/2019:23:00:46 +0200] "GET /svg/500.svg HTTP/1.1" 304 182 "http://localhost/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
localhost:80 127.0.0.1 - - [09/Mar/2019:23:00:47 +0200] "GET /index.php HTTP/1.1" 500 11276 "http://localhost/index.php/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
localhost:80 127.0.0.1 - - [09/Mar/2019:23:00:47 +0200] "GET /svg/500.svg HTTP/1.1" 304 182 "http://localhost/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
localhost:80 127.0.0.1 - - [09/Mar/2019:23:00:48 +0200] "GET /index.php HTTP/1.1" 500 11274 "http://localhost/index.php/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
localhost:80 127.0.0.1 - - [09/Mar/2019:23:00:49 +0200] "GET /svg/500.svg HTTP/1.1" 304 182 "http://localhost/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"

Apache Log:

[Sat Mar 09 21:21:47.374319 2019] [php7:warn] [pid 868] [client 127.0.0.1:57422] PHP Warning:  require_once(/var/www/NNTmux/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/NNTmux/bootstrap/autoload.php on line 3
[Sat Mar 09 21:21:47.374355 2019] [php7:error] [pid 868] [client 127.0.0.1:57422] PHP Fatal error:  require_once(): Failed opening required '/var/www/NNTmux/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/NNTmux/bootstrap/autoload.php on line 3
[Sat Mar 09 21:59:26.252564 2019] [mpm_prefork:notice] [pid 831] AH00169: caught SIGTERM, shutting down
[Sat Mar 09 21:59:26.399163 2019] [mpm_prefork:notice] [pid 4548] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sat Mar 09 21:59:26.399213 2019] [core:notice] [pid 4548] AH00094: Command line: '/usr/sbin/apache2'
[Sat Mar 09 22:26:27.280723 2019] [core:alert] [pid 4553] [client 127.0.0.1:58116] /var/www/NNTmux/public/.htaccess: Invalid command ';#', perhaps misspelled or defined by a module not included in the server configuration, referer: http://localhost/login
[Sat Mar 09 22:26:29.695773 2019] [core:alert] [pid 4552] [client 127.0.0.1:58118] /var/www/NNTmux/public/.htaccess: Invalid command ';#', perhaps misspelled or defined by a module not included in the server configuration, referer: http://localhost/login
[Sat Mar 09 22:33:29.586810 2019] [mpm_prefork:notice] [pid 4548] AH00169: caught SIGTERM, shutting down
[Sat Mar 09 22:33:29.732284 2019] [mpm_prefork:notice] [pid 5630] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sat Mar 09 22:33:29.732347 2019] [core:notice] [pid 5630] AH00094: Command line: '/usr/sbin/apache2'

php log

**Comment by DariusIII** [comment]
Have you ran `composer instal`l at all?

**Comment by lloot** [comment]
i did yes, i deleted the VM trying again,

**Comment by DariusIII** [comment]
Check your config, as this does not look ok to me: 

> "http://localhost/index.php/login"

**Comment by lloot** [comment]
did news install on dev version, not a single problem, headed to "http://localhost/index.php/login" to login, after login i get 
500
Server Error, only way to get site on local host again is to run php artisan nntmux:install again.

<?php

require_once dirname(__DIR__).DIRECTORY_SEPARATOR.'resources/views/themes/smarty.php';

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle($request = Illuminate\Http\Request::capture());
$response->send();
$kernel->terminate($request, $response);

**Comment by DariusIII** [comment]
Off course you have problems, there is no such page, you need to go to `http://localhost/login`

**Comment by lloot** [comment]
thank you darius fiixed
