### ISSUE TITLE
cross posted release deleted

### ISSUE THREAD

**Issue by micknolans** [NNTmux/newznab-tmux#943]
only noticed since latest updated
in tmux panel (update releases)
I have noticed its deleting 1 releases every time it runs (1 cross posted release deleted)

this happens until all releases are finally gone.

centos 7
php 7.2
mariadb 10.2

**Comment by DariusIII** [comment]
Crossposted release deletion should not remove all existing releases. 
Can you provide a screenshot of the pane? 

How many groups are you indexing? Are you sure that releases are not deleted because they are being bad releases?

**Comment by micknolans** [comment]
![tmux](https://user-images.githubusercontent.com/39907789/54530546-fe222880-497a-11e9-9df1-0e1823fad9d5.png)
have 3 groups added.
it just shows in the window 1 removed each run until releases are all removed.

**Comment by DariusIII** [comment]
What groups have you enabled?

**Comment by micknolans** [comment]
teevee, albums.mp3,alt.binaries.movies.
it seems to create the releases sort covers out etc as every time update releases runs in panel deletes everyone one by one as you can see them disappear from browse and you can see numbers go down one by one in tmux

**Comment by DariusIII** [comment]
That is definitely not how crossposted works. Are yous sure those releases are not deleted in postprocess additional pane? 
I am asking because i have added code to delete releases that do not have proper nzb associated with them, 

Crossposted just seeks duplicate posts.

**Comment by micknolans** [comment]
i just assumed it was cross posted as says it in tmux window.
on the tmux window remove crap releases i have disable.

**Comment by DariusIII** [comment]
Check post process additional pane, and see if releases are being deleted there. If they are, those are bad releases anyway.

**Comment by micknolans** [comment]
post process additional pane nothing being deleted
will run for 4-5 hours and get back to you :)
but as far as it s going now still doing the same,

**Comment by DariusIII** [comment]
Those 3 groups you added have many bad releases, can you add some other groups too, like:
`alt.binaries.mom, alt.binaries.misc, alt.binaries.etc` and see if those get deleted too?

**Comment by micknolans** [comment]
same problem with those groups.
all i can see different maybe is i am use sphinx Sphinx 2.2.11  and tmux 2.8
maybe causing problem for me
