### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by Sweepr** [NNTmux/newznab-tmux#965]
Dev-branch: v1.0.19-142-gfd9367a61

**Describe the bug**

php test-ReleaseCleaner.php alt.binaries.misc 50 false 7010

   Symfony\Component\Debug\Exception\FatalThrowableError  : Cannot use object of type stdClass as array

  at /home/public_html/nntmux/misc/testing/Dev/test-ReleaseCleaner.php:46
    42| if ($group === false) {
    43|     exit('No group with name '.$argv[1].' found in the database.');
    44| }
    45|
  > 46| $releases = DB::select(sprintf('SELECT name, searchname, fromname, size, id FROM releases WHERE groups_id = %d %s ORDER BY postdate LIMIT %d', $group['id'], $category, $argv[2]));
    47|
    48| if (\count($releases) === 0) {
    49|     exit('No releases found in your database for group '.$argv[1].PHP_EOL);
    50| }

**Comment by DariusIII** [comment]
I have to "revisit" this script as it has never been updated.
