### ISSUE TITLE
predb_import_daily_batch.php not working

### ISSUE THREAD

**Issue by sensei73** [NNTmux/newznab-tmux#970]
predb import is impossible

error:

   ErrorException  : json_decode() expects parameter 1 to be string, array given

  at /var/www/NNTmux/cli/data/predb_import_daily_batch.php:56
    52| $filePattern = '(?P<filename>(?P<stamp>\d+)_predb_dump\.csv\.gz)';
    53| 
    54| $result = getDirListing($url);
    55| 
  > 56| $dirs = json_decode($result, true);
    57| 
    58| if ($dirs === null || (isset($dirs['message']) && strpos($dirs['message'], 'API rate limit exceeded for') === 0)) {
    59|     exit("Error: $result");
    60| }

  Exception trace:

  1   json_decode()
      /var/www/NNTmux/cli/data/predb_import_daily_batch.php:56

**Comment by Sweepr** [comment]
Confirmed commit fixes the issue, may be closed.
