### ISSUE TITLE
Not able to create another user

### ISSUE THREAD

**Issue by RaymondSchnyder** [NNTmux/newznab-tmux#972]
**Describe the bug**
Cannot add a new user, error 500 is being thrown.
Location in code: /var/www/NNTmux/vendor/league/climate/src/Util/System/Linux.php:90 
![grafik](https://user-images.githubusercontent.com/12892508/56419596-15ff0c00-629b-11e9-8e76-6bb87b4ac9ac.png)

**To Reproduce**
1. Go to the admin panel -> add new user
2. fill in random data
3. try to create user by clicking submit

**Expected behavior**
User gets created and no error is thrown

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12892508/56419519-bd2f7380-629a-11e9-961c-3103318ea957.png)

**Installation (please complete the following information):**
 - OS: Debian 9
 - PHP version: PHP 7.3-FPM
 - Webserver: NGINX
 - NNTmux version: v1.0.19

**Additional context**
Nothing

**Comment by DariusIII** [comment]
I am closing this issue, if this problem is not fixed for you, feel free to reopen it.
