### ISSUE TITLE
Nette\DI\Definitions\ServiceDefinition' not found

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#973]
seems i cannot get tmux to start, maybe my fault again :)

debian 9

* fresh install dev

`PHP Warning:  Class 'Nette\DI\Definitions\ServiceDefinition' not found in /var/www/vhosts/***/vendor/nette/di/src/compatibility.php on line 12
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/vhosts/***/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php on line 43`

thanks

**Comment by DariusIII** [comment]
What version of php are you using?
As this is PHP version problem.

**Comment by m0rse** [comment]
php 7.3.4
thanks
