### ISSUE TITLE
preg match compilation failed

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#974]
![tmux problem](https://user-images.githubusercontent.com/3258413/57228479-cabf5a00-700b-11e9-8b73-b3b750bd68e3.png)

problem running tmux as picture only just noticed.
reading on other posts could be regex ?

thanks

**Comment by DariusIII** [comment]
Not that it could be, but it is regex. If this is new install, it should not happen. But, if this is just an updated installation, you need to run following commands:

`php artisan fixtures:down --table=collection_regexes --table= release_naming_regexes` 

and 

`php artisan fixtures:up --table=collection_regexes --table= release_naming_regexes`

**Comment by m0rse** [comment]
Thank you  :)
