### ISSUE TITLE
Grabbing binaries fails due to timezone issues

### ISSUE THREAD

**Issue by langerak** [NNTmux/newznab-tmux#978]
Hi,

I'm trying to set this up but after the installation and enabling a group it seems that it's constantly failing when looking from within tmux with:

DateTime::__construct(): Failed to parse time string (backfill_target) at position 0 (b). The timezone could not be found in the database2019-06-05 10:50:00

I'm on Ubuntu 18.04 with MariaDB 10.4 (tried 10.3 as well) and PHP 7.2. I've inserted the TZ information in MySQL and use Europe/Amsterdam in PHP/Apache/MySQL and .env as timezone.

What can I do to solve this issue?

**Comment by DariusIII** [comment]
Backfill is buggy, choose different type of backfill, as i need to fix it, but is not a priority.

**Comment by langerak** [comment]
Thanks for the quick reply. What type of backfill do you recommend at this point?

**Comment by DariusIII** [comment]
Use backfill by date, not number of days defined in group.
