### ISSUE TITLE
password/ no password

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#980]
maybe a problem, maybe not :)

![tmux33](https://user-images.githubusercontent.com/3258413/59156258-daf5a980-8a8f-11e9-8255-d9742cdbc229.png)

lot of posts, show that its passworded but looking at it its showing the .mkv file ?? 
on this post for example

**Comment by DariusIII** [comment]
I will be refactoring this, completely. I will simplify this to be either passworded or not. Currently code handles it as not passworded, possibly passworded, couple of values in between and definitely passworded.

This is complicating things too much.

**Comment by Fossil01** [comment]
Wasn't this fixed a while ago?

**Comment by DariusIII** [comment]
@Fossil01 No, this is still an issue.
