### ISSUE TITLE
Profile edit

### ISSUE THREAD

**Issue by m0rse** [NNTmux/newznab-tmux#981]
profileedit page 

changing any setting , clicking on save gives 419 error page expired

**Comment by DariusIII** [comment]
What is your setting for APP_URL and SESSION_DOMAIN in .env?

**Comment by m0rse** [comment]
problem was happening to me , so checked yours and its the 419 error.

 APP_URL and SESSION_DOMAIN are set to domain in mine and i get the 500 error

array_key_exists(): The first argument should be either a string or an integer
