### ISSUE TITLE
On profile save it complains email already exists

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#982]
As per title. The stored e-mail is auto-filled back into the e-mail form field, when the profile is saved it complains the e-mail already exists. Which makes sense because it does, but it's the same e-mail for the same user so it should be allowed.

**Comment by DariusIII** [comment]
Well, NNTmux has an current email field that is filled, email in profile form is empty. You should adapt your custom theme to NNTmux:

**Comment by Fossil01** [comment]
Ah, never thought of that. Cheers.
