### ISSUE TITLE
Wrong covers assigned to TV shows

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#988]
Some TV shows always get the wrong cover assigned when the show is first indexed.

On mine it's mostly a cover from How it's Made but it also happened on `Bar.Rescue.S06E42` where it had a cover from a show called `Kids Baking Championship.`

The TVDB/TMDB etc. ID's in the DB are correct and the corresponding websites have the correct covers.

The rest of the information (title, summary etc.) is also correct. It's just the cover that's wrong.

**Comment by Fossil01** [comment]
This seemed to be fixed but I'm again getting wrong covers. All other TV info is correct, just the cover is wrong. Maybe because TVDB API is crap right now it's pulling more from TMDB, TVMaze etc and the cover fix wasn't placed there?

Seems to be an issue with mainly TVMaze processed shows now. (Source = 2) but likely also other sources.

**Comment by Wally73** [comment]
the tvdb api still has issues so its waiting til they have fixed their crap

**Comment by DariusIII** [comment]
This has nothing to do with tvdb api, issue is in data caching.
