### ISSUE TITLE
Fresh Install - ErrorException Undefined index: Date

### ISSUE THREAD

**Issue by moloquin** [NNTmux/newznab-tmux#989]
**Describe the bug**
Fresh install on both Debian 10, and Debian 8 using the Ubuntu install guide.  Have gone through it 3 times now.  It's probably something simple but can't get past this error when running update_binaries.php or running in tmux.  Have a single group enabled.

**To Reproduce**
1. php misc/update/update_binaries.php or php artisan tmux-ui:start
2. Error Below.  Is the same whether update_binaries or tmux

**Expected behavior**
Expected binaries to be updated and inserted in the DB

**Screenshots**
Error from stdout:
Updating: 1 group(s) - Using compression? Yes [Blacklight\Binaries::updateAllGroups]
Starting group 1 of 1 [Blacklight\Binaries::updateAllGroups]
Processing alt.binaries.misc
New group alt.binaries.misc starting with 100,000 messages worth. Leaving 20,000 for next pass.
Server oldest: 4,596,550,135 Server newest: 4,772,470,954 Local newest: 0

Getting 20,000 articles (4,772,350,955 to 4,772,370,954) from alt.binaries.misc - (80,000 articles in queue).
Received 892KB from group (alt.binaries.misc).
   ErrorException  : Undefined index: Date

  at /var/www/NNTmux/Blacklight/Binaries.php:953
    949|         $iterator2 = $msgCount - 1;
    950|         while (true) {
    951|             if (! isset($returnArray['firstArticleNumber']) && isset($headers[$iterator1]['Number'])) {
    952|                 $returnArray['firstArticleNumber'] = $headers[$iterator1]['Number'];
  > 953|                 $returnArray['firstArticleDate'] = $headers[$iterator1]['Date'];
    954|             }
    955| 
    956|             if (! isset($returnArray['lastArticleNumber']) && isset($headers[$iterator2]['Number'])) {
    957|                 $returnArray['lastArticleNumber'] = $headers[$iterator2]['Number'];

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: Date", "/var/www/NNTmux/Blacklight/Binaries.php", [])
      /var/www/NNTmux/Blacklight/Binaries.php:953

  2   Blacklight\Binaries::getHighLowArticleInfo(["4772350955"])
      /var/www/NNTmux/Blacklight/Binaries.php:616

Error from storage/logs/laravel*.log
[2019-08-17 15:10:31] NNTmux.ERROR: Undefined index: Date {"exception":"[object] (ErrorException(code: 0): Undefined index: Date at /var/www/NNTmux/Blacklight/Binaries.php:953)
[stacktrace]
#0 /var/www/NNTmux/Blacklight/Binaries.php(953): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/NNTmux...', 953, Array)
#1 /var/www/NNTmux/Blacklight/Binaries.php(616): Blacklight\\Binaries->getHighLowArticleInfo(Array, Array, 20000)
#2 /var/www/NNTmux/Blacklight/Binaries.php(456): Blacklight\\Binaries->scan(Object(App\\Models\\UsenetGroup), 4772350955, '4772370954')
#3 /var/www/NNTmux/Blacklight/Binaries.php(278): Blacklight\\Binaries->updateGroup(Object(App\\Models\\UsenetGroup), 1000000)
#4 /var/www/NNTmux/misc/update/update_binaries.php(35): Blacklight\\Binaries->updateAllGroups(1000000)
#5 {main}
"} 

**Installation (please complete the following information):**
 - OS: Debian 10
 
PHP 7.3.4-2 (cli) (built: Apr 13 2019 19:05:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4-2, Copyright (c) 1999-2018, by Zend Technologies

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

mariadb --version
mariadb  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

 - NNTmux version or commit 
v1.2.1 Master

**Comment by DariusIII** [comment]
Which usenet provider do you use?

**Comment by moloquin** [comment]
Primary is newsgroupdirect.com and alternate is usenetserver.com

**Comment by DariusIII** [comment]
That is why i asked. As far as i know, newsgroupdirect switched from Omicron backend to be separate usenet provider with their own servers. 
Could you try and switch to usenetserver as primary?

**Comment by moloquin** [comment]
Switched it over and looks like it's working now.  Thanks

Guessing newsgroupdirect won't work as secondary either?

**Comment by DariusIII** [comment]
It would work, as it downloads different kind of data as secondary. Primary is used for headers, secondary for additional postprocessing.

**Comment by moloquin** [comment]
Awesome.  Thanks for the info.

I'll close out the ticket.
