### ISSUE TITLE
Add proper check for existence of sudo command

### ISSUE THREAD

**Issue by CptChaos** [NNTmux/newznab-tmux#990]
**Describe the bug**
install_tmux.sh assumes sudo is installed or required, but it should check if it's required to use and/or available.

**To Reproduce**
Try to run install_tmux.sh without sudo installed (like on Debian)

**Expected behavior**
Not requiring to use sudo

**Screenshots**
None

**Installation (please complete the following information):**
 - OS: Debian
 - PHP: 7.3
 - NNTmux latest (bcc8f42 as of now)

**Comment by DariusIII** [comment]
On ubuntu, which is our only officially supported platform,  sudo is installed by default and required as running our scripts as root is a very bad idea. 
On Debian you can install sudo, or you can make a PR with suggested changes to install_tmux.sh.
