### ISSUE TITLE
Opening a show with "special" chars throws error

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#999]
When opening /details/guid a.k.a viewnzb.tpl:

`SQLSTATE[42000]: Syntax error or access violation: 1064 index releases_rt: syntax error, unexpected ')' near ' \- \-)' [SELECT * FROM releases_rt WHERE MATCH('(@searchname \\- \\-)') ORDER BY id DESC LIMIT 0, 10000 OPTION max_matches = 10000, ranker = 'sph04', sort_method = 'pq']`

The shows name startts with `9-1-1.S03E04.1080p` so I guess the hyphens are the issue.

**Comment by DariusIII** [comment]
Yes, hyphens cause an issue with sphinx/manticore search.

**Comment by DariusIII** [comment]
This has been fixed in dev, with commit 54a71fd160ee2b070f2fbeec536e7c09c60dcf0a
